Repository StareAbyss/FoodsVsMiceAutoAssistant, pull requests merged in 2024-11, with the labels that each got.

#422 docs(README): 更新文档内容和结构, 移动大量内容至网页文档
  README.md
  battle_plan/1卡组-通用-1P.json
  battle_plan/非标卡组-通用-追踪电棍花火.json
  md_img/任务列表.png
  md_img/关卡一览.png
  md_img/战斗方案编辑器.png
  md_img/流程配置.png
  md_img/窗口名和游戏名称.png
  md_img/运行主页.png
  md_img/高级功能.png
  md_img/高级选项.png
Labels: Git-Docs

#423 docs(README): 更新文档首页信息
  README.md
Labels: Git-Docs

#424 fix: 物品使用. 修复该功能在背包较大的用户中遗落物品的Bug.
  README.md
  function/core/FAA.py
  function/core/Todo.py
  resource/image/item/物品-双暴卡.png
Labels: Git-Fix

#426 refactor(目标识别): 重构识图点击功能. 极大降低部分高密度识图操作的等待时间.
  function/common/bg_img_match.py
  function/core/FAA.py
  function/core/QMW_3_service.py
  resource/ui/FAA_3.0.ui
Labels: Git-Feat, Module-MatcImg

#427 feat: 新增UI, 允许用户清除FAA卡片状态自学习记忆.
  function/core/QMW_1_log.py
  function/globals/g_resources.py
  logs/item_ranking_dag_graph.json
  打包 - 资源文件.py
Labels: Git-Feat, Module-UI

#428 perf: 公会任务流程. 领取完成后, 会额外领取一次普通任务. 确保不漏公会贡献.
  function/core/Todo.py
Labels: Git-Perf

#430 refactor: 将主窗口的弹窗, 输出文本等信号直接注册到全局.
  function/core/FAA.py
  function/core/FAA_ActionQuestReceiveRewards.py
  function/core/FAA_BattleARoundPreparation.py
  function/core/QMW_1_log.py
  function/core/QMW_2_load_settings.py
  function/core/QMW_3_service.py
  function/core/Todo.py
  function/globals/SIGNAL.py
  test/match_png/__init__.py
Labels: Git-Feat

#431 fix: 修复同时使用多种复制类卡片, 未选中放卡队列模式, 复制位置撞车的问题.
  function/core_battle/Card.py
Labels: Git-Fix, Module-Battle

#432 perf: 优化使用任务卡功能, 现在将更多的目标位置覆盖为任务卡, 并在12P分配, 以确保完成.
  function/core/FAA.py
Labels: Module-Battle, Git-Perf

#434 docs 将FAA内置入门文档删除, 指引用户前往线上文档.
  [入门]FAA从入门到神殿.pdf
  打包 - 资源文件.py
  新手入门 看我!!! 看我!!! 看我!!!.txt
Labels: Git-Docs

#437 perf(图像识别): 允许直接输入图像, 而不使用句柄截图以进行识图. 调优代码逻辑和参数顺序并添加注释.
  function/common/bg_img_match.py
Labels: Module-MatcImg, Git-Perf

#438 perf(图像识别): 多目标识别, 允许短路模式优化性能.
  function/common/bg_img_match.py
  function/core/QMW_0_load_ui_file.py
  function/core/Todo.py
Labels: Git-Perf

#440 perf(点击频率): 修改默认值160Hz -> 120Hz
  config/settings_template.json
  function/core/QMW_2_load_settings.py
  resource/ui/FAA_3.0.ui
Labels: Git-Perf

#442 perf(战斗内核): 火苗识别-不再额外识图, 优化性能.
  function/core_battle/CardManager.py
  function/core_battle/FAA_Battle.py
Labels: Module-Battle, Git-Perf

#444 fix(界面跳转): 服务区切换, 操作延时提高, 应对近期的服务器卡顿.
  function/core/FAA_ActionInterfaceJump.py
  task_sequence/transformer_of_todo_json_from_excel.py
  test/image/__init__.py
Labels: Git-Fix

#445 fix(界面跳转): 修复单号运行需刷新功能后, 再运行多号功能, 两个号随机数种子不一致, 导致进入不同区域的问题.
  function/core/FAA.py
Labels: Git-Fix

#446 feat(战斗方案编辑器): 更新战斗方案协议. 新增多波次变阵编辑功能.
  function/core/QMW_EditorOfBattlePlan.py
Labels: Git-Feat, Module-Battle

#447 feat(战斗方案检测): 兼容新版按波变阵版战斗方案协议.
  battle_plan/1卡组-NO-4-5.json
  battle_plan/1卡组-通用-1P.json
  battle_plan/1卡组-通用-2P.json
  battle_plan/1卡组-通用-变阵测试.json
  battle_plan/1卡组-通用-花火-1P.json
  battle_plan/1卡组-通用-花火-2P.json
  battle_plan/1卡组-通用-花瓶.json
  battle_plan/2卡组-速刷-生煎电棍-1P.json
  battle_plan/2卡组-速刷-生煎电棍-2P.json
  battle_plan/2卡组-速刷-生煎电棍花火-1P.json
  battle_plan/2卡组-速刷-生煎电棍花火-2P.json
  battle_plan/3卡组-难关-1P+2P.json
  battle_plan/3卡组-难关-魔塔双人-100-1P.json
  battle_plan/3卡组-难关-魔塔双人-100-2P.json
  battle_plan/星际卡组-NO-6-3至4 苏打.json
  battle_plan/星际卡组-NO-6-5 汉堡.json
  battle_plan/星际卡组-NO-6-6至7 巴旦.json
  battle_plan/星际卡组-NO-6-8至9 冷萃.json
  battle_plan/雪山卡组-EX-3-N(通解)-1P.json
  battle_plan/雪山卡组-EX-3-N(通解)-2P.json
  battle_plan/雷城卡组-EX-4-1至4-1P.json
  battle_plan/雷城卡组-EX-4-1至4-2P.json
  battle_plan/雷城卡组-EX-4-5-1P.json
  battle_plan/雷城卡组-EX-4-5-2P.json
  battle_plan/雷城卡组-EX-4-6-1P.json
  battle_plan/雷城卡组-EX-4-6-2P.json
  battle_plan/非标卡组-EX-1-6.json
  battle_plan/非标卡组-萌新-冷萃莓果.json
  battle_plan/非标卡组-萌新-煮蛋忍坤.json
  battle_plan/非标卡组-通用-追踪电棍花火.json
  function/core/QMW_2_load_settings.py
  function/core/QMW_EditorOfTaskSequence.py
  function/scattered/check_battle_plan.py
  function/scattered/check_uuid_in_battle_plan.py
Labels: Git-Feat, Module-Battle

#448 refactor(战斗执行器): 优化多线程通信逻辑, 提高可读性. 优化代码逻辑, 通过共享识图和截图结果, 降低战斗开销.
  function/core/Todo.py
  function/core_battle/CardManager.py
  function/core_battle/CardQueue.py
Labels: Module-Battle, Git-Perf

#449 feat(战斗执行器): 完成按波次变阵的开发, 包括波次识别, 内部切换策略, 根据策略变化自动铲卡.
  function/core/FAA.py
  function/core_battle/CardManager.py
  function/core_battle/FAA_Battle.py
Labels: Git-Feat, Module-Battle

#450 fix(战斗执行器): 增加铲卡操作时延, 并将铲掉全部目标卡的动作上锁战斗锁, 以保护该操作的完整性.
  function/core_battle/FAA_Battle.py
Labels: Git-Fix, Module-Battle

#451 fix(战斗执行器): 卡片状态图像自学习. 修复罕见情况下复制类卡片无限尝试学习但失败导致卡死的问题.
  function/core/QMW_2_load_settings.py
  function/core/QMW_EditorOfBattlePlan.py
  function/core/Todo.py
  function/core_battle/Card.py
  function/scattered/read_json_to_stage_info.py
Labels: Git-Fix, Module-Battle

#452 fix(界面跳转): 跨服副本进入流程. 降低执行速度, 以提高稳定性.
  function/core/FAA_ActionInterfaceJump.py
Labels: Git-Fix

#453 fix(战斗方案编辑器): 修复切换当前战斗方案时, 总是错误弹出"未选择一张卡片"的问题.
  config/stage_info_online.json
  function/core/QMW_EditorOfBattlePlan.py
  logs/item_ranking_dag_graph.json
Labels: Git-Fix

#454 perf(米苏物流): 降低url有效性测试的超时时间 5s->1.5s. 提高用户体验.
  function/scattered/test_route_connectivity.py
Labels: Git-Feat

#456 docs(致谢名单): 例行更新
  致谢名单.png
Labels: Git-Docs

#457 fix: 修复因误操作导致的线程Bug, 并优化多线程执行步骤.
  function/core/QMW_3_service.py
  function/core/Todo.py
  function/core_battle/CardManager.py
Labels: Git-Fix

#458 fix(界面跳转): 修复由于过于宽泛的错误捕捉, 导致关卡代号错误的弹窗和终止线程效果异常触发的问题.
  function/core/FAA.py
Labels: Git-Fix

#459 perf: 更新启动时的文本输出. 更新外部链接和赞助信息.
  function/core/QMW_1_log.py
Labels: Module-UI, Git-Perf

#460 fix(战斗执行器):换波次铲卡时, 忽略护罩类卡片换位写反成了仅铲卡护罩类, 该问题已得到修复.
  function/core_battle/FAA_Battle.py
Labels: Git-Fix, Module-Battle

#461 perf(战斗执行器): 铲卡选中铲子后点击棋盘时, 会点击(1->2)次. 以提高铲卡稳定性.
  function/core/QMW_SettingsMigrator.py
  function/tools/calculation_grind_chest.py
  resource/ui/FAA_3.0.ui
  test/image/match_loots/match_items_in_blocks.py
Labels: Module-Battle, Git-Perf

#462 fix(战斗方案编辑器): 保存为json时, 错误的将波次方案中和默认相同的都剔除, 现改为, 和上一个有效波次方案相同的方案被剔除.
  function/core/QMW_EditorOfBattlePlan.py
Labels: Git-Fix

#464 build(战斗方案): 重新制定3号内置卡组, 为花火海星冷萃电棍流派. 并修改双人魔塔100方案.
  battle_plan/3卡组-难关-1P+2P.json
  battle_plan/3卡组-难关-魔塔双人-100-1P.json
  battle_plan/3卡组-难关-魔塔双人-100-2P.json
Labels: Git-Build

#466 build(关卡信息): 修复魔塔单人155-160承载卡的错误. 并新增Extra用法示例.
  config/stage_info.json
  config/stage_info_extra.json
Labels: Git-Build

#467 build(文字OCR): 新增美食大赛一个字的识别"曲".
  battle_plan/1卡组-通用-变阵测试.json
  battle_plan/2卡组-速刷-生煎电棍-1P.json
  battle_plan/2卡组-速刷-生煎电棍-2P.json
  battle_plan/2卡组-速刷-生煎电棍花火-1P.json
  battle_plan/2卡组-速刷-生煎电棍花火-2P.json
  battle_plan/3卡组-通用-花火追踪电棍.json
  battle_plan/3卡组-难关-花火追踪电棍驻场.json
  battle_plan_not_active/雷城卡组Plus-EX-4-6-1P.json
  battle_plan_not_active/雷城卡组Plus-EX-4-6-2P.json
  battle_plan_not_active/非标卡组-MT-1-151至155-海星冷萃.json
  logs/item_ranking_dag_graph.json
  resource/image/ocr/美食大赛/曲.png
Labels: Module-OCR, Git-Build

#468 perf(用户界面): 删去工会管理器的周数；将工会管理器表格的未知值修改为0
  function/core/QMW_3_service.py
  resource/ui/FAA_3.0.ui
Labels: Module-UI, Git-Perf

#472 build(战斗方案): 音乐节夜 - SSS方案
  battle_plan/EX-4-6-1P.json
  battle_plan/EX-4-6-2P.json
  battle_plan/雷城卡组-EX-4-6-1P.json
  battle_plan/雷城卡组-EX-4-6-2P.json
Labels: Git-Build

#473 feat(全局关卡方案): 重大更新. 允许用户勾选使用全局关卡方案, 接管目前关卡的战斗方案和卡组策略.
  function/core/FAA.py
  function/core/QMW_2_load_settings.py
  function/core/Todo.py
  resource/ui/FAA_3.0.ui
Labels: Git-Feat, Module-Battle

#474 perf(全局关卡方案编辑器): 重新布局UI. 修改输入输出格式. 并新增默认方案, 与默认方案相同的关卡信息不进行保存以节省空间.
  function/core/QMW_EditorOfStagePlan.py
  resource/ui/StagePlanEditor.ui
Labels: Git-Perf

#475 feat(自动带卡): 新增, 允许用户在卡组策略中设置自动带卡后, 根据战斗方案的name字段自动带卡. 仅完成事项处理, 未实现动作函数.
  function/core/FAA.py
  function/core/Todo.py
Labels: Git-Feat, Module-Battle

#476 refactor(自动带卡): 完全重构携带任务卡函数, 重构为自动带卡功能. 大幅优化逻辑, 极大加速运行速度.
  function/core/FAA_BattleARoundPreparation.py
Labels: Git-Feat, Module-Battle

#478 perf(识图核心): 循环识别并点击功能, 查找失败后, 也会激活 AfterSleep
  function/common/bg_img_match.py
Labels: Module-MatchImg

#479 perf(物品识别): 当识别结果均为识别失败时, 视为无效数据.
  function/core/Todo.py
Labels: Git-Perf

#480 build(配置模板): 更新'全局关卡方案'设置, 更新'自动带卡'设置.
  config/settings_template.json
  function/globals/g_resources.py
Labels: Module-Battle, Git-Build

#481 perf(公会/情侣任务扫描): 生成的方案支持自动带卡.
  function/core/FAA.py
Labels: Git-Perf

#482 build(公会任务扫描): 跟随游戏更新, 感谢夏夜和LTPTR的支持~
  resource/image/quest_guild/10/EX-2-9.png
  resource/image/quest_guild/10/EX-3-5.png
  resource/image/quest_guild/10/EX-4-6.png
  resource/image/quest_guild/10/NO-5-7.png
  resource/image/quest_guild/11/NO-6-10.png
  resource/image/quest_guild/11/NO-6-5_带#微波炉爆弹-0.png
  resource/image/quest_guild/11/NO-6-6_禁#香辣年糕蟹.png
  resource/image/quest_guild/2/NO-1-10_带#双层小笼包-0.png
  resource/image/quest_guild/2/NO-1-13_带#酒瓶炸弹-0.png
  resource/image/quest_guild/2/NO-2-6_带#油灯.png
  resource/image/quest_guild/2/NO-4-12_带#热狗大炮-0.png
  resource/image/quest_guild/2/NO-4-3_带#肥牛火锅-0.png
  resource/image/quest_guild/2/NO-4-9_带#香肠-0.png
  resource/image/quest_guild/4/EX-2-6.png
  resource/image/quest_guild/4/NO-5-1_a.png
  resource/image/quest_guild/4/NO-5-1_b.png
  resource/image/quest_guild/4/NO-5-1_c.png
  resource/image/quest_guild/4/NO-5-2_a.png
  resource/image/quest_guild/4/NO-5-2_b.png
  resource/image/quest_guild/4/NO-5-2_c.png
  resource/image/quest_guild/4/NO-5-3_a.png
  resource/image/quest_guild/4/NO-5-3_b.png
  resource/image/quest_guild/4/NO-6-1_带#香辣年糕蟹.png
  resource/image/quest_guild/4/NO-6-5.png
  resource/image/quest_guild/5/CS-6-5.png
  resource/image/quest_guild/5/CS-6-6.png
  resource/image/quest_guild/6/EX-1-1.png
  resource/image/quest_guild/6/EX-1-3.png
  resource/image/quest_guild/6/NO-2-2_a.png
  resource/image/quest_guild/6/NO-2-2_b.png
  resource/image/quest_guild/7/NO-1-15_a.png
  resource/image/quest_guild/7/NO-1-15_b.png
Labels: Git-Build

#484 fix: 拆分[战前准备工作]为[确定进入房间]和[带卡]两步. 使用自动带卡且进入房间失败时, 会直接跳过本关所有次数的问题已修复.
  function/core/FAA.py
  function/core/FAA_BattlePreparation.py
  function/core/Todo.py
Labels: Git-Fix

#485 perf(UI): 为[战斗方案编辑器]和[配置迁移工具]设置初始大小,以将他们与主窗口自动中心对齐.
  function/core/QMW_3_service.py
  function/core/QMW_EditorOfBattlePlan.py
  function/core/QMW_SettingsMigrator.py
Labels: Module-UI, Git-Perf

#486 perf(公会贡献扫描器): 修改默认空值(0->∅), 并清空当天没有扫描到的数据而不显示默认空值. 以优化排序效果.
  function/core/QMW_3_service.py
Labels: Module-UI, Git-Perf

#488 build: 美食大赛OCR, 自动带卡, 战利品识别图优化. 资源文件补充.
  logs/item_ranking_dag_graph.json
  resource/image/card/准备房间+/三向冰冻小笼包-0.png
  resource/image/card/准备房间+/棕榈吹风机-0.png
  resource/image/card/准备房间+/棕榈吹风机-1.png
  resource/image/card/准备房间+/防风草沙拉-0.png
  resource/image/card/准备房间+/防风草沙拉-1.png
  resource/image/ocr/美食大赛/个.png
  resource/image/ocr/美食大赛/务.png
  resource/image/ocr/美食大赛/完.png
  resource/image/ocr/美食大赛/常.png
  resource/image/ocr/美食大赛/成.png
Labels: Module-Battle, Module-OCR, Git-Build, Module-Drop

#491 build(版本号更新): v1.6.1
  function/globals/EXTRA.py
Labels: Git-Build

#492 perf(自动带卡): 其与任务带卡完成兼容.
  config/card_type.json
  function/core/FAA_BattlePreparation.py
  function/core/QMW_EditorOfStagePlan.py
  function/core/Todo.py
  resource/ui/StagePlanEditor.ui
Labels: Git-Perf

#493 build(requirement.txt): Update
  requirements.txt
Labels: Git-Build

#494 build(战斗方案): 更新内置激活方案中, 所有卡片name字段, 以支持自动带卡
  battle_plan/1卡组-通用-1P.json
  battle_plan/1卡组-通用-2P.json
  battle_plan/1卡组-通用-变阵测试.json
  battle_plan/1卡组-通用-花火-1P.json
  battle_plan/1卡组-通用-花火-2P.json
  battle_plan/2卡组-速刷-生煎电棍-1P.json
  battle_plan/2卡组-速刷-生煎电棍-2P.json
  battle_plan/2卡组-速刷-生煎电棍花火-1P.json
  battle_plan/2卡组-速刷-生煎电棍花火-2P.json
  battle_plan/3卡组-通用-花火追踪电棍.json
  battle_plan/3卡组-难关-花火追踪电棍驻场.json
  battle_plan/3卡组-难关-魔塔双人-100-1P.json
  battle_plan/3卡组-难关-魔塔双人-100-2P.json
  battle_plan/EX-3-N(通解)-1P.json
  battle_plan/EX-3-N(通解)-2P.json
  battle_plan/EX-4-1to4-1P 街区钟楼.json
  battle_plan/EX-4-1to4-2P 街区钟楼.json
  battle_plan/MT-1-151to155.json
  battle_plan/MT-1-156to160.json
  battle_plan/NO-4-5 花园.json
  battle_plan/NO-6-3to4 苏打水.json
  battle_plan/NO-6-5 汉堡王.json
  battle_plan/NO-6-6to7 巴旦木.json
  battle_plan/NO-6-8to9 冷萃星环.json
  battle_plan/萌新专用-冷萃莓果.json
  battle_plan/萌新专用-煮蛋忍坤.json
  function/core/FAA.py
  function/core/QMW_EditorOfStagePlan.py
Labels: Module-Battle, Git-Build

#496 perf(自定义任务事项): 兼容新版全局关卡战斗方案, 兼容自动带卡.
  function/core/QMW_EditorOfTaskSequence.py
Labels: Git-Perf

#497 perf(自动带卡): 不重复进行图片叠加处理. 略微优化性能.
  function/core/FAA_BattlePreparation.py
Labels: Git-Perf

#498 perf(自动带卡): 因找不到必须要带的卡片而失败时, 输出所有没找到的卡片的名称.
  function/core/FAA_BattlePreparation.py
Labels: Git-Perf

#499 build(战斗方案): 优化部分内置方案, 新增SSS巴旦木禁年糕蟹, SSS星冰乐方案.
  battle_plan/1卡组-通用-1P.json
  battle_plan/1卡组-通用-2P.json
  battle_plan/EX-2-9-1P 金字塔 SSS.json
  battle_plan/EX-2-9-2P 金字塔 SSS.json
  battle_plan/EX-3-5 1P 星冰乐 SSS.json
  battle_plan/EX-3-5 2P 星冰乐 SSS.json
  battle_plan/EX-3-N-1P 雪山通解.json
  battle_plan/EX-3-N-2P 雪山通解.json
  battle_plan/EX-4-1to4-1P 街区钟楼.json
  battle_plan/EX-4-1to4-2P 街区钟楼.json
  battle_plan/EX-4-5-1P 音乐节-日 低配.json
  battle_plan/EX-4-5-2P 音乐节-日 低配.json
  battle_plan/EX-4-6-1P 音乐节-夜 SSS.json
  battle_plan/EX-4-6-2P 音乐节-夜 SSS.json
  battle_plan/NO-6-5 汉堡王 带微波炉 SSS.json
  battle_plan/NO-6-6to7 巴旦木 禁年糕蟹 SSS.json
  battle_plan/萌新专用-冷萃莓果.json
Labels: Module-Battle, Git-Build

#500 fix(战斗方案): 修复战斗方案读取时, 如果名称中有多个 . 符号, 会读取出错的问题
  function/scattered/get_list_battle_plan.py
Labels: Git-Fix

#501 build(界面跳转): 等级较低的玩家, 火山岛未完全开放时, 无法进入未开放交界处低等级关卡的问题已修复.
  resource/image/stage/NO-2-1.png
  resource/image/stage/NO-2-10.png
  resource/image/stage/NO-2-11.png
  resource/image/stage/NO-2-12.png
  resource/image/stage/NO-2-13.png
  resource/image/stage/NO-2-14.png
  resource/image/stage/NO-2-2.png
  resource/image/stage/NO-2-3.png
  resource/image/stage/NO-2-4.png
  resource/image/stage/NO-2-5.png
  resource/image/stage/NO-2-8.png
  resource/image/stage/NO-2-9.png
Labels: Git-Build

#502 build(OCR): 关卡名称OCR资源补充.
  config/stage_info.json
  config/stage_info_online.json
  config/stage_plan.json
  logs/item_ranking_dag_graph.json
  resource/image/card/特殊对策卡/3x3非即时出伤/微波炉爆弹_10_300.png
  resource/image/ocr/关卡名称/一.png
  resource/image/ocr/关卡名称/串.png
  resource/image/ocr/关卡名称/凡.png
  resource/image/ocr/关卡名称/包.png
  resource/image/ocr/关卡名称/峡.png
  resource/image/ocr/关卡名称/平.png
  resource/image/ocr/关卡名称/忆.png
  resource/image/ocr/关卡名称/思.png
  resource/image/ocr/关卡名称/滴.png
  resource/image/ocr/关卡名称/点.png
  resource/image/ocr/关卡名称/绪.png
  resource/image/ocr/关卡名称/袭.png
  resource/image/ocr/关卡名称/记.png
  resource/image/ocr/关卡名称/跃.png
  resource/image/ocr/关卡名称/跳.png
  resource/image/ocr/关卡名称/道.png
  task_sequence/营地通刷.json
  task_sequence/默认.json
Labels: Module-OCR, Git-Build

#504 fix(自动带卡): 降低执行速度, 以防止卡顿造成选卡失败.
  function/core/FAA_BattlePreparation.py
Labels: Git-Fix, Module-Battle

#505 fix(自动带卡): 修复携带任务卡时, 携带位置和战斗中选卡位置不对应的问题.
  function/core/FAA_BattlePreparation.py
Labels: Git-Fix

#506 perf(自动带卡): 单本连战时, 若战斗顺利, 下次开始前不再重新选卡.
  function/core/Todo.py
Labels: Git-Perf

#507 fix(波次变阵): 修复一个Bug, 该Bug导致 变阵中的 瓜皮类卡片的 变化位置将被视为无效 的 特性 失效.
  function/core_battle/FAA_Battle.py
Labels: Git-Fix, Module-Battle

#509 build(自动带卡): 支持更多卡片, 修复太阳神的四转图像错误. 雷神视为投手. 修复蓝莓塔和水果塔名称错误.
  config/card_type.json
  resource/image/card/准备房间+/元气牛-0.png
  resource/image/card/准备房间+/元气牛-1.png
  resource/image/card/准备房间+/元气牛-2.png
  resource/image/card/准备房间+/勺勺兔-0.png
  resource/image/card/准备房间+/勺勺兔-1.png
  resource/image/card/准备房间+/勺勺兔-2.png
  resource/image/card/准备房间+/太阳神-2.png
  resource/image/card/准备房间+/太阳神-3.png
  resource/image/card/准备房间+/巨神-0.png
  resource/image/card/准备房间+/巨神-1.png
  resource/image/card/准备房间+/巨神-2.png
  resource/image/card/准备房间+/爱心便当-0.png
  resource/image/card/准备房间+/生煎锅-0.png
  resource/image/card/准备房间+/生煎锅-1.png
  resource/image/card/准备房间+/生煎锅-2.png
  resource/image/card/准备房间+/窃蛋龙-0.png
  resource/image/card/准备房间+/窃蛋龙-1.png
  resource/image/card/准备房间+/窃蛋龙-2.png
  resource/image/card/准备房间+/美味水果塔-0.png
  resource/image/card/准备房间+/美味水果塔-1.png
  resource/image/card/准备房间+/美味水果塔-2.png
  resource/image/card/准备房间+/能量喵-0.png
  resource/image/card/准备房间+/能量喵-1.png
  resource/image/card/准备房间+/能量喵-2.png
  resource/image/card/准备房间+/萌虎高压锅-0.png
  resource/image/card/准备房间+/蓝莓信号塔塔-0.png
  resource/image/card/准备房间+/赤帝-0.png
  resource/image/card/准备房间+/赤帝-1.png
  resource/image/card/准备房间+/赤帝-2.png
  resource/image/card/准备房间+/赤帝-3.png
  resource/image/card/准备房间+/逗猫棒-0.png
  resource/image/card/准备房间+/逗猫棒-1.png
  resource/image/card/准备房间+/逗猫棒-2.png
  resource/image/card/准备房间+/铛铛虎-0.png
  resource/image/card/准备房间+/铛铛虎-1.png
  resource/image/card/准备房间+/铛铛虎-2.png
  resource/image/card/准备房间+/黑暗神-0.png
  resource/image/card/准备房间+/黑暗神-1.png
  resource/image/card/准备房间+/黑暗神-2.png
Labels: Git-Build

#510 perf(UI): 战斗方案编辑器和全局关卡方案编辑器中, 选择关卡按钮支持所有关卡, 并为stage_info.json完全覆盖name字段.
  config/stage_info.json
  config/stage_info_extra.json
  config/stage_info_online.json
  function/core/QMW_EditorOfBattlePlan.py
  function/core/QMW_EditorOfStagePlan.py
Labels: Module-UI, Git-Perf

#511 feat(战斗方案生成): 添加max_card_num字段, 在启动自动带卡后, 将更优雅地支持限卡数任务.
  function/core/FAA.py
  function/core/FAA_BattlePreparation.py
  function/core/Todo.py
Labels: Git-Feat

#512 refactor(自动禁卡): 完全重构, 支持根据类型名称禁卡，性能提高1000倍+, 和自动带卡兼容性更佳
  function/core/FAA.py
  function/core/FAA_BattlePreparation.py
Labels: Git-Perf

#514 style(任务事项): 允许额外带卡/禁卡/最大卡片的参数置空, 将自动处理. 并优化文本输出.
  function/core/FAA.py
  function/core/Todo.py
  function/scattered/match_ocr_text/text_to_battle_info.py
Labels: Module-UI

#515 perf(战斗方案编辑器): 多波次编辑时, 如果该波次没有方案, 默认继承上一波有效变阵, 而不是0波方案.
  function/core/FAA.py
  function/core/FAA_BattlePreparation.py
  function/core/QMW_EditorOfBattlePlan.py
  function/core/Todo.py
  function/scattered/match_ocr_text/text_to_battle_info.py
Labels: Git-Perf

#516 fix(自动大赛OCR): 恢复因stage_info.json重构, 而失效的功能.
  function/scattered/extract_names_and_ids_from_json.py
Labels: Git-Fix, Module-OCR

#519 fix(自动禁卡): 修复没有禁卡时, 战斗报错的问题.
  function/core/FAA.py
Labels: Git-Fix
