Repository StareAbyss/FoodsVsMiceAutoAssistant, pull requests merged in 2024-09, with the labels that each got.

#279 v1.5.0-beta.3 公会日志(周贡扫描)功能. 初步完成UI和配置按钮, 并纳入Todo中.
  config/settings_template.json
  function/core/QMW_0_load_ui_file.py
  function/core/QMW_1_load_settings.py
  function/core/QMW_3_service.py
  function/core/Todo.py
  function/scattered/guild_manager.py
  function/tools/guild_manager.py
  function/widget/__init__.py
  logs/item_ranking_dag_graph.json
  resource/picture/ocr/关卡名称/字.png
  resource/picture/ocr/关卡名称/尔.png
  resource/picture/ocr/关卡名称/库.png
  resource/ui/FAA_3.0.ui
Labels: 🔼enhancement

#284 v1.5.0-beta.3 得意黑绝赞回归! 应用等宽数字. 公会日志(周贡扫描)功能. 增加路径初始化.
  function/core/QMW_0_load_ui_file.py
  function/core/QMW_3_service.py
  function/core/QMW_EditorOfTaskSequence.py
  function/globals/get_paths.py
  logs/item_ranking_dag_graph.json
  resource/font/SmileySans-Oblique.ttf
  resource/ui/FAA_3.0.ui
Labels: 🪲Bug, 🔼enhancement

#277 v1.5.0 beta3 优化`text_to_battle_info.py`中的卡片匹配逻辑
  function/scattered/match_ocr_text/text_to_battle_info.py
  resource/picture/ocr/美食大赛/乐.png
  resource/picture/ocr/美食大赛/及.png
  resource/picture/ocr/美食大赛/唱.png
  resource/picture/ocr/美食大赛/巨.png
  resource/picture/ocr/美食大赛/戚.png
  resource/picture/ocr/美食大赛/探.png
  resource/picture/ocr/美食大赛/时.png
  resource/picture/ocr/美食大赛/油.png
  resource/picture/ocr/美食大赛/灯.png
  resource/picture/ocr/美食大赛/炸.png
  resource/picture/ocr/美食大赛/纸.png
  resource/picture/ocr/美食大赛/胎.png
  resource/picture/ocr/美食大赛/能.png
  resource/picture/ocr/美食大赛/营.png
  resource/picture/ocr/美食大赛/葵.png
  resource/picture/ocr/美食大赛/虾.png
  resource/picture/ocr/美食大赛/行.png
  resource/picture/ocr/美食大赛/轰.png
  resource/picture/ocr/美食大赛/险.png
  resource/picture/ocr/美食大赛/隆.png
  resource/picture/ocr/美食大赛/骑.png
  resource/picture/ocr/美食大赛/鲨.png
  resource/picture/ocr/美食大赛/龙.png
Labels: 🔼enhancement

#292 v1.5.0-beta.3 Tab-Bar. 大幅美化默认样式.
  function/core/QMW_0_load_ui_file.py
Labels: 🔼enhancement

#293 v1.5.0-beta.3 从文件系统直接加载图片资源到ui.
  function/core/QMW_0_load_ui_file.py
Labels: 🔼enhancement

#294 v1.5.0-beta.3 文档更新. 从shields.io获取下载数, Q群图片.
  README.md
Labels: 📘doc

#297 v1.5.0-beta.3 公会管理器(贡献点扫描器). 完全重构数据结构, 完成视图并绑定交互. 初步完工.
  function/core/QMW_3_service.py
  function/core/Todo.py
  function/scattered/guild_manager.py
  resource/ui/FAA_3.0.ui
  test/test.py
Labels: 🔼enhancement

#295 v1.5.0-beta.3 更新大赛界面点击坐标，降低匹配阈值，更新大赛字库
  function/scattered/match_ocr_text/get_food_quest_by_ocr.py
  resource/picture/ocr/美食大赛/笛.png
  resource/picture/ocr/美食大赛/蛤.png
  resource/picture/ocr/美食大赛/蜊.png
Labels: 🪲Bug, 📦Resource

#296 v1.5.0-beta.3 ui外观bug修复 gpu加速高级战斗设置 幻坤高级战斗未正确启用bug修复
  config/settings_template.json
  function/core/FAA_extra_readimage.py
  function/core/QMW_0_load_ui_file.py
  function/core/QMW_1_load_settings.py
  function/core/Todo.py
  function/qrc/modern_rc.py
  function/qrc/qdarkgraystyle_rc.py
  function/yolo/onnxdetect.py
  resource/picture/card/特殊对策卡/其他不是炸弹的特殊卡/学者幻幻鸡_9_275.png
  resource/picture/card/特殊对策卡/其他不是炸弹的特殊卡/导师幻幻鸡_9_275.png
  resource/picture/card/特殊对策卡/其他不是炸弹的特殊卡/幻幻鸡_9_325.png
  resource/ui/FAA_3.0.ui
Labels: 🪲Bug, 🔼enhancement

#298 v1.5.0-beta.3 更新大赛字库
  resource/picture/ocr/美食大赛/保.png
  resource/picture/ocr/美食大赛/卖.png
  resource/picture/ocr/美食大赛/吧.png
  resource/picture/ocr/美食大赛/啤.png
  resource/picture/ocr/美食大赛/爪.png
  resource/picture/ocr/美食大赛/特.png
  resource/picture/ocr/美食大赛/电.png
  resource/picture/ocr/美食大赛/皮.png
  resource/picture/ocr/美食大赛/粉.png
  resource/picture/ocr/美食大赛/红.png
  resource/picture/ocr/美食大赛/罗.png
  resource/picture/ocr/美食大赛/蒙.png
  resource/picture/ocr/美食大赛/贩.png
  resource/picture/ocr/美食大赛/酒.png
  resource/picture/ocr/美食大赛/饮.png
  resource/picture/ocr/美食大赛/鳗.png
Labels: 📦Resource

#300 v1.5.0-beta.3 公会管理器. 新增对周贡献点的直接扫描, 视图中不再通过计算展示周贡, 而是从游戏中直接扫描.
  function/core/QMW_3_service.py
  function/scattered/guild_manager.py
Labels: 🔼enhancement

#301 v1.5.0-beta.3 领取任务奖励. 修复背包爆满时, 无限尝试领取奖励卡死流程的问题.
  function/core/FAA.py
  function/core/FAA_ActionQuestReceiveRewards.py
  function/core/Todo.py
Labels: 🪲Bug

#302 v1.5.0-beta.3 新增米苏物流上传路径系统. 用户可在ui中编辑路径, 可自动进行路径可用性检查并恢复默认, 点击可查看详细说明.
  .gitignore
  config/settings_template.json
  function/core/QMW_1_load_settings.py
  function/core/QMW_1_log.py
  function/core/QMW_2_load_settings.py
  function/core/QMW_2_log.py
  function/core/QMW_3_service.py
  function/core/QMW_TipMisuLogistics.py
  function/core/Todo.py
  function/globals/g_extra.py
  function/scattered/loots_and_chest_data_save_and_post.py
  function/scattered/test_route_connectivity.py
  logs/item_ranking_dag_graph.json
  resource/ui/FAA_3.0.ui
  test/test.py
Labels: 🔼enhancement

#303 v1.5.0-beta.3 更新软件开屏输出, 更新赞助渠道.
  function/core/QMW_1_log.py
  resource/logo/赞赏码.png
Labels: 📘doc

#304 v1.5.0-beta.3 更新致谢名单.
  致谢名单.md
  致谢名单.png
Labels: 📘doc

#305 v1.5.0-beta.3 将二级密码功能相关说明, 收纳到独立页面, 按钮点开即可查看.
  function/core/QMW_3_service.py
  function/core/QMW_TipLevel2.py
Labels: 🔼enhancement

#306 v1.5.0-beta.3 微调大赛文字匹配逻辑
  function/scattered/match_ocr_text/text_to_battle_info.py
Labels: 🔼enhancement

#308 v1.5.0-beta.3 一种基于psutil的性能监控实现
  function/core/QMW_3_service.py
  function/core/performance_analysis.py
  resource/ui/FAA_3.0.ui
Labels: 🔼enhancement

#309 v1.5.0-beta.3 将任意通用包裹-悬赏酬劳和通用宝箱的资源图片, 从git, 自动打包器中移除. 情侣任务, 遗漏补充/错误更改（致谢: LTPTR.）
  .gitignore
  config/cus_images/背包_装备_需使用的/任意通用包裹.png
  logs/item_ranking_dag_graph.json
  resource/picture/quest_spouse/2/NO-2-2.png
  resource/picture/quest_spouse/2/NO-2-9.png
  resource/picture/quest_spouse/2/NO-3-1.png
  resource/picture/quest_spouse/3/NO-3-3.png
  打包_资源文件.py
Labels: 🪲Bug, 🔼enhancement

#310 v1.5.0-beta.3 魔塔单人. 2P最高上限层数155->165.
  resource/ui/FAA_3.0.ui
Labels: 🔼enhancement

#311 v1.5.0-beta.3 二级功能. 改用卸除装备激活输入框.而非送花.
  function/core/FAA.py
  function/core/Todo.py
Labels: 🔼enhancement

#312 v1.5.0-beta.3 每日签到. 新增领取月卡.
  function/core/FAA.py
  function/core/FAA_ActionInterfaceJump.py
  resource/picture/common/顶部菜单/月卡福利.png
Labels: 🔼enhancement

#313 v1.5.0-beta.3 大赛字库补充
  function/scattered/match_ocr_text/get_food_quest_by_ocr.py
  resource/picture/ocr/美食大赛/(.png
  resource/picture/ocr/美食大赛/).png
  resource/picture/ocr/美食大赛/值.png
  resource/picture/ocr/美食大赛/充.png
  resource/picture/ocr/美食大赛/券.png
  resource/picture/ocr/美食大赛/加.png
  resource/picture/ocr/美食大赛/参.png
  resource/picture/ocr/美食大赛/台.png
  resource/picture/ocr/美食大赛/后.png
  resource/picture/ocr/美食大赛/周.png
  resource/picture/ocr/美食大赛/坚.png
  resource/picture/ocr/美食大赛/大.png
  resource/picture/ocr/美食大赛/本.png
  resource/picture/ocr/美食大赛/术.png
  resource/picture/ocr/美食大赛/毯.png
  resource/picture/ocr/美食大赛/点.png
  resource/picture/ocr/美食大赛/累.png
  resource/picture/ocr/美食大赛/级.png
  resource/picture/ocr/美食大赛/警.png
  resource/picture/ocr/美食大赛/计.png
  resource/picture/ocr/美食大赛/赛.png
  resource/picture/ocr/美食大赛/预.png
  resource/picture/ocr/美食大赛/食.png
  resource/picture/ocr/美食大赛/高.png
Labels: 🔼enhancement

#316 v1.5.0-beta.4 重写和调整大量元素, 缩小UI.
  function/core/QMW_0_load_ui_file.py
  function/core/QMW_2_load_settings.py
  function/core/QMW_3_service.py
  function/core/QMW_TipBattleSenior.py
  function/core/performance_analysis.py
  logs/item_ranking_dag_graph.json
  resource/ui/FAA_3.0.ui
  resource/ui/draglabel.py
Labels: 🔼enhancement

#317 v1.5.0-beta.4 将战斗中卡片位置的坐标基点, 从随意取定, 改为卡片左上角.
  function/core/FAA.py
  function/core_battle/Card.py
  function/core_battle/get_position_in_battle.py
  test/test_screen_in_battle_all_card.py
Labels: 🔼enhancement

#318 v1.5.0-beta.4 重新编排入门文档. 以适应当前版本的变化. 特别是游戏和角色填写相关.
  [入门]FAA从入门到神殿.docx
  [入门]FAA从入门到神殿.pdf
Labels: 📘doc

#319 v1.5.0-beta.4 stage_info_extra.json.json 2024-09-26 内容更新. 致谢: TY丶雨
  config/stage_info_extra.json
Labels: 📦Resource
