Repository StareAbyss/FoodsVsMiceAutoAssistant, pull requests merged in 2024-07, with the labels that each got.

#44 v1.3.1 重大更新, 完成定时启动任务事项的功能.
  function/scattered/TodoTimerManager.py
  function/script/QMW_1_load_settings.py
  function/script/QMW_2_log.py
  function/script/QMW_3_service.py
  function/script/ThreadTodo.py
  resource/ui/FAA_3.0.ui
Labels: enhancement

#45 v1.3.1 尝试性完成多线程单人作战功能
  function/script/QMW_3_service.py
  function/script/ThreadTodo.py
Labels: enhancement

#46 v1.3.1 完成关卡配置-魔塔蛋糕-单人 21-30层 136-165层 的填写, 补完了萌宠神殿20-25层的铲卡参数
  config/opt_stage_info.json
Labels: enhancement

#47 v1.3.1 战利品识别. 添加如下图片资源 中心徽章A/中心钥匙/冰镇西瓜/城堡钥匙/深渊钥匙/飞船徽章B
  resource/picture/item/战斗/中心徽章A.png
  resource/picture/item/战斗/中心钥匙.png
  resource/picture/item/战斗/冰镇西瓜.png
  resource/picture/item/战斗/城堡钥匙.png
  resource/picture/item/战斗/深渊钥匙.png
  resource/picture/item/战斗/飞船徽章B.png
Labels: enhancement

#48 v1.3.1 为部分内置战斗方案, 提供幻幻鸡支持 (kun参数)
  battle_plan/1卡组-默认-1P.json
  battle_plan/1卡组-默认-2P.json
  battle_plan/1卡组-默认-激进-1P.json
  battle_plan/1卡组-默认-激进-2P.json
  battle_plan/2卡组-速刷-生煎-1P.json
  battle_plan/2卡组-速刷-生煎-2P.json
  battle_plan/2卡组-速刷-生煎电棍-1P.json
  battle_plan/2卡组-速刷-生煎电棍-2P.json
Labels: enhancement

#51 v1.3.1 完善log图片和文件的自动创建, 从git中移除对应模板文件.
  function/core/FAA.py
  logs/chests_picture/CU-0-0_1P_2024-03-31_01-10-21.png
  logs/chests_picture/CU-0-0_2P_2024-03-31_01-10-21.png
  logs/chests_picture/本文件用于在pull代码后可以不缺失目录结构.txt
  logs/loots_picture/CU-0-0_1P_2024-03-31_01-09-56.png
  logs/loots_picture/CU-0-0_2P_2024-03-31_01-09-56.png
  logs/loots_picture/本文件用于在pull代码后可以不缺失目录结构.txt
  logs/result_json/1P掉落明细.json
  logs/result_json/1P掉落汇总.json
  logs/result_json/2P掉落明细.json
  logs/result_json/2P掉落汇总.json
  logs/result_json/本文件用于在pull代码后可以不缺失目录结构.txt
  logs/running_log.log
Labels: enhancement

#52 v1.3.1 战利品日志记录中, 每个关卡的记录下,将区分本场战斗是否使用钥匙.
  function/battle/CardManager.py
  function/core/FAABattle.py
  function/core/Todo.py
Labels: enhancement

#53 v1.3.1 新增 自动移除超过三天的日志图片功能
  function/core/Todo.py
Labels: enhancement

#55 v1.3.1 log日志. 添加了报错内容的写入
  function/globals/log.py
Labels: enhancement

#56 v1.3.1 战斗方案执行器 - 放卡时, 通过偏移对应点击位置, 以规避点到领取奖励按钮, 老方案危险区域先识图检测再点击, 已移除
  function/battle/Card.py
Labels: enhancement

#58 v1.3.1 更新requirements.txt 并规范代码, 增加可读性和可维护性.
  function/battle/Card.py
  function/battle/get_position_in_battle.py
  function/common/bg_img_match.py
  function/common/bg_img_screenshot.py
  function/common/bg_p_screenshot.py
  function/core/FAA.py
  function/core/FAAActionInterfaceJump.py
  function/core/FAAActionQuestReceiveRewards.py
  function/core/FAABattle.py
  function/core/QMW_2_log.py
  function/core/Todo.py
  function/scattered/get_house_id.py
  requirements.txt
  resource/ui/FAA_3.0.ui
Labels: documentation

#59 v1.3.1 实现双倍掉落卡(双暴)使用功能
  config/settings.json
  function/core/FAA.py
  function/core/QMW_1_load_settings.py
  function/core/Todo.py
Labels: enhancement

#60 v1.3.1 对自定义todo的配置文件和转换器进行了更新, 以符合最新版本的战斗配置格式.
  customize_todo/be_transformed.xlsx
  customize_todo/todo_example.json
  customize_todo/transform_excel_to_json.py
  customize_todo/transformer_of_todo_json_from_excel.py
  customize_todo/大赛240201-240229.json
  customize_todo/大赛240201-240229单人.json
  customize_todo/大赛240201-240229双人.json
  customize_todo/测试用.json
Labels: bug

#61 v1.3.1 图像识别功能新特性: 自动无视template的透明像素进行匹配.
  function/common/bg_img_match.py
Labels: enhancement

#62 v1.3.1 使用背包中消耗品功能, 提高了识图物品的阈值(0.9->0.95), 以规避某些相似图形误判的问题.
  resource/picture/item/背包/金币-小金币袋.png
Labels: bug

#64 v1.3.1 项目目录结构调整, 杂项.
  function/core/FAA.py
  function/core/QMW_1_load_settings.py
  function/core/QMW_EditorOfBattlePlan.py
  function/core/Todo.py
  function/core_battle/Card.py
  function/core_battle/CardManager.py
  function/core_battle/CardQueue.py
  function/core_battle/__init__.py
  function/core_battle/get_position_in_battle.py
Labels: documentation

#65 v1.3.1 从 stage_info.json 中分离常更换的部分到 stage_info_extra.json.
  config/stage_info.json
  config/stage_info_extra.json
  function/scattered/read_json_to_stage_info.py
Labels: enhancement

#66 v1.3.1 更新了开屏输出文本.
  function/common/thread_with_exception.py
  function/core/QMW_2_log.py
  function/core/analyzer_of_loot_logs.py
Labels: documentation

#67 v1.3.1 使用双倍掉落卡功能, 新增特性: 在北京时间周末, 跳过.
  function/core/FAA.py
Labels: enhancement

#68 v1.3.1 Update README.md
  README.md
Labels: documentation

#69 v1.3.1 自动战斗模块 - 识别使用幻鸡 - 新增对金卡创世神的支持 (三转和四转)
  function/core/FAA.py
  resource/picture/card/战斗/幻幻鸡-10.png
  resource/picture/card/战斗/幻幻鸡-11.png
  resource/picture/card/战斗/幻幻鸡-7.png
  resource/picture/card/战斗/幻幻鸡-8.png
Labels: enhancement

#70 v1.3.1 新增花火龙变种卡组. 新增魔塔高层方案占位符. 新增 battle_plan_old 目录存放用不上的方案.
  battle_plan/3卡组-魔塔-单人-136 to 139-海星.json
  battle_plan/3卡组-魔塔-单人-146 to 150-海星.json
  battle_plan/3卡组-魔塔-单人-151 to 155-海星.json
  battle_plan/3卡组-魔塔-单人-156 to 160-未完成.json
  battle_plan/3卡组-魔塔-单人-161 to 165-未完成.json
  battle_plan/4卡组-默认-1P+2P.json
  battle_plan/S-1卡组-默认-花火龙-1P.json
  battle_plan/S-1卡组-默认-花火龙-2P.json
  battle_plan/S-2卡组-速刷-生煎电棍花火龙-1P.json
  battle_plan/S-2卡组-速刷-生煎电棍花火龙-2P.json
  battle_plan_old/2卡组-速刷-生煎-1P.json
  battle_plan_old/2卡组-速刷-生煎-2P.json
  battle_plan_old/EX-2卡组-街区钟楼-1P.json
  battle_plan_old/EX-2卡组-街区钟楼-2P.json
  battle_plan_old/EX-2卡组-阴乐劫夜-1P.json
  battle_plan_old/EX-2卡组-阴乐劫夜-2P.json
  battle_plan_old/EX-2卡组-阴乐劫日-1P.json
  battle_plan_old/EX-2卡组-阴乐劫日-2P.json
  battle_plan_old/EX-特殊卡组-冰跨-1P.json
  battle_plan_old/EX-特殊卡组-冰跨-2P.json
  battle_plan_old/EX-特殊卡组-雪山-1P.json
  battle_plan_old/EX-特殊卡组-雪山-2P.json
  battle_plan_old/本文件夹用于储存部分暂时无用的战斗方案, 不会被faa读取.txt
Labels: enhancement

#72 v1.3.1 对Todo类中的各项子功能的开始和结束输出文本进行了规范化. 应用统一的输出函数.
  function/core/Todo.py
Labels: enhancement

#73 v1.3.1 重新整理多方案下, 定时启动和编辑方案的逻辑. 启动后将锁定配置, 不应用实时更新.
  function/core/FAA.py
  function/core/QMW_1_load_settings.py
  function/core/QMW_3_service.py
  function/core/Todo.py
  function/scattered/TodoTimerManager.py
Labels: enhancement

#74 v1.3.1 运行 定时启动 线程时, 将锁定用户的对应设置ui. 结束后解锁.
  function/core/QMW_3_service.py
Labels: enhancement

#75 v1.3.1 更新注释文本, 提高项目可维护性.
  function/core/FAA.py
  function/core/QMW_2_log.py
Labels: documentation

#76 v1.3.1 图像资源补充, 包括: 战利品 / 被使用的消耗品 / 删除的道具 / 携带和ban卡的战斗卡
  logs/img.png
  resource/picture/card/房间/冰淇淋-2.png
  resource/picture/card/房间/幻幻鸡-0.png
  resource/picture/card/房间/油灯-0.png
  resource/picture/card/房间/麦芽糖-2.png
  resource/picture/item/mask.png
  resource/picture/item/战斗/激光宝石.png
  resource/picture/item/战斗/阿诺的弹药包.png
  resource/picture/item/背包/礼券.png
  resource/picture/item/背包/金币-小金币袋.png
  resource/picture/item/背包_道具_需删除的/S-冰煮蛋器投手-初级技能书.png
  resource/picture/item/背包_道具_需删除的/S-大火炉-初级技能书.png
  resource/picture/item/背包_道具_需删除的/S-巧克力大炮-初级技能书.png
  resource/picture/item/背包_道具_需删除的/S-机枪冰冻小笼包-初级技能书.png
  resource/picture/item/背包_道具_需删除的/S-机枪小笼包-初级技能书.png
  resource/picture/item/背包_道具_需删除的/S-章鱼烧-初级技能书.png
  resource/picture/item/背包_道具_需删除的/S-钢鱼刺-初级技能书.png
  resource/picture/item/背包_道具_需删除的/猫猫箱-初级技能书.png
  resource/picture/item/背包_道具_需删除的/猫猫箱-高级技能书.png
  resource/picture/item/背包_道具_需删除的/肥牛火锅-高级技能书.png
  resource/picture/item/背包_道具_需删除的/雷电长棍面包-初级技能书.png
  resource/picture/item/背包_道具_需删除的/雷电长棍面包-高级技能书.png
  resource/picture/item/背包_道具_需删除的/麻辣香锅-高级技能书.png
Labels: enhancement

#77 v1.3.1 小工具 1. 计算多个关卡中哪些格子组合一定少于多少障碍; 2. 计算肝帝宝箱最优路径;
  battle_plan/1卡组-通用-1P.json
  battle_plan/1卡组-通用-2P.json
  battle_plan/1卡组-通用-激进-1P.json
  battle_plan/1卡组-通用-激进-2P.json
  battle_plan/1卡组-通用-花瓶.json
  battle_plan/4卡组-通用-1P+2P.json
  battle_plan/S-1卡组-通用-花火龙-1P.json
  battle_plan/S-1卡组-通用-花火龙-2P.json
  config/settings.json
  function/tools/calculation_best_cell_without_obstacle.py
  function/tools/calculation_grind_chest.py
Labels: enhancement

#78 v1.3.1 关卡配置. 修正了 海葵洋流-夜 和 魔塔151-155 的 承载卡的错误.
  config/stage_info.json
Labels: bug

#79 v1.3.1 更新致谢名单! 感谢你们!
  致谢名单.md
Labels: documentation

#80 v1.3.1 增加了魔塔蛋糕双人70层及以下的承载卡和障碍物配置, 感谢QQ群友 Ray 的录入!
  config/stage_info.json
Labels: enhancement

#81 v1.3.1 修正了魔塔蛋糕单人61-70层的承载卡和障碍物配置的错误; 感谢QQ群友 Ray 的修正!
  config/stage_info.json
Labels: bug

#82 v1.3.1 修正了 自动战斗-自动放卡 中, 优先级队列在低火苗能量情况下失效的bug.
  function/core_battle/Card.py
Labels: bug

#83 v1.3.1 重大优化, 图像截取时, 若窗口最小化, 将自动提升至已激活窗口的最低一级.
  function/common/bg_img_match.py
  function/common/bg_img_screenshot.py
  function/core/FAA.py
  function/core/FAABattle.py
  function/core/FAA_ActionInterfaceJump.py
  function/core/FAA_ActionQuestReceiveRewards.py
  function/core/FAA_BattleARoundPreparation.py
  function/core/Todo.py
  function/core/analyzer_of_loot_logs.py
  function/core_battle/Card.py
  function/core_battle/get_position_in_battle.py
  function/scattered/get_house_id.py
Labels: enhancement

#84 v1.3.1 将自动战斗中各项动作间隔设置为动态调整的比例关系, 而非固定值.
  function/core/Todo.py
  function/core_battle/CardManager.py
Labels: enhancement

#85 v1.3.1 修复了在多线程单人模式时, 其中一个号卡死会导致正常运行的另一号同时reload, 导致报错卡死的bug.
  function/core/Todo.py
Labels: bug

#86 v1.3.1 当没有成功完成至少一次战斗时, 将不再输出战利品文本
  function/core/Todo.py
Labels: bug

#87 v1.3.1 自动战斗模块 - 识别使用幻鸡 - 新增对金卡创世神的支持 (不转)
  function/core_battle/Card.py
  resource/picture/card/战斗/幻幻鸡-6.png
  resource/picture/card/战斗/幻幻鸡-9.png
Labels: enhancement

#88 v1.3.1 文档更新, 包括 入门文档 / 欢乐互娱Bug收集 / 致谢名单
  [入门]FAA从入门到神殿.docx
  [入门]FAA从入门到神殿.pdf
  a_tips.md
  a_欢乐互娱bug.md
  battle_plan/4卡组-魔塔-双100-2P.json
  function/common/bg_img_match.py
  function/core/FAA.py
  function/core/Todo.py
  function/scattered/restore_window_if_minimized.py
  function/tools/calculation_min_dif_from_imgs.py
  test/match_png/__init__.py
  test/match_png/a+b.py
  test/match_png/mask-2.bmp
  test/match_png/mask.bmp
  test/match_png/match_image.py
  test/match_png/match_images.py
  test/match_png/source.png
  test/match_png/template.png
  test/match_png/template_lock.png
  test/match_png/test.py
  test/match_png/角标-卡片40x50.png
  test/match_png/角标-物品44x44.png
  test/test.png
  test/test.py
  test/test_compare_picture.py
  test/test_compare_pictures.py
  test/test_screen_in_battle_all_card.py
  test/test_screenshot.py
  致谢名单.md
Labels: documentation

#89 v1.3.1 修复背包爆满时无法通过兑换暗晶输入二级密码的问题.
  function/core/FAA.py
  function/core/Todo.py
  resource/picture/common/二级密码.png
Labels: bug

#90 v1.3.1 Update README.md 并补充少量图片资源.
  README.md
  a_欢乐互娱bug.md
  resource/picture/item/战斗/对战雾宝石.png
  resource/picture/item/战斗/法老王的黄金棺材.png
  resource/picture/quest_spouse/3/NO-4-8.png
Labels: documentation

#91 v1.3.1 从git去除settings.json, 此后将通过settings_template.json作为模板, 在启动时校验并复制模板完成该项工作.
  config/settings_template.json
  function/core/QMW_1_load_settings.py
Labels: enhancement

#92 v1.3.1 优化截图最小化检测的性能, 从判定窗口状态改为检查截图图像是否纯黑.
  battle_plan/3卡组-魔塔-单人-136 to 140-海星.json
  config/settings.json
  function/common/bg_img_screenshot.py
  function/scattered/restore_window_if_minimized.py
  test/test_screenshot.py
Labels: enhancement

#93 v1.3.1 修正关卡信息中, 云洞图. 不再尝试在魔塔单人131-140一定时间内不可能出现云洞的地块放置承载.
  config/stage_info.json
  function/globals/log.py
Labels: bug

#94 v1.3.1 加快了全局动作处理线程类的出口处理频率(interval 0.015 -> 0.01)
  function/globals/thread_action_queue.py
Labels: enhancement

#95 v1.3.1 修复了战前准备中, 移除卡片功能失效的bug.
  function/core/FAA_BattleARoundPreparation.py
Labels: bug

#96 v1.3.1 添加了调查部分电脑机型上, 动作队列生产者速度>消费者速度问题的测试单元.
  function/core/FAABattle.py
  function/core_battle/CardManager.py
  function/globals/thread_action_queue.py
  test/profile_load.py
  test/test_action_queue_timer.py
  test/test_queue_click.py
Labels: bug

#99 v1.3.1 初步设计了ui中日志文本以颜色分级不同层的内容的函数.
  config/settings_template.json
  function/core/QMW_2_log.py
  function/core/QMW_3_service.py
  function/core/Todo.py
  resource/picture/quest_food/NO-1-10_2_0_None_None.png
  resource/picture/quest_food/NO-1-10_2_1_None_None.png
  resource/picture/quest_food/NO-1-5_2_1_None_None.png
  resource/picture/quest_food/NO-1-7_1_1_None_None.png
  resource/picture/quest_food/NO-1-7_2_0_None_None.png
  resource/picture/quest_food/NO-1-7_2_1_None_None.png
  resource/picture/quest_food/NO-1-9_2_1_None_None.png
  resource/picture/quest_food/NO-2-11_2_1_None_None.png
  resource/picture/quest_food/NO-2-12_2_1_None_None.png
  resource/picture/quest_food/NO-2-12_2_1_None_棉花糖.png
  resource/picture/quest_food/NO-2-13_2_1_None_None.png
  resource/picture/quest_food/NO-2-13_2_1_酒杯灯_None.png
  resource/picture/quest_food/NO-2-14_2_1_None_None.png
  resource/picture/quest_food/NO-2-15_2_1_None_None.png
  resource/picture/quest_food/NO-2-1_1_1_None_None.png
  resource/picture/quest_food/NO-2-1_2_1_None_None.png
  resource/picture/quest_food/NO-2-6_2_1_None_None.png
  resource/picture/quest_food/NO-2-7_2_1_None_木盘子.png
  resource/picture/quest_food/NO-2-8_2_1_None_None.png
  resource/picture/quest_food/NO-4-2_2_1_None_None.png
  resource/picture/quest_food/NO-4-3_2_1_None_None.png
  resource/picture/quest_food/NO-4-5_1_0_None_None.png
  resource/picture/quest_food/NO-4-5_2_1_None_None(2).png
  resource/picture/quest_food/NO-4-5_2_1_None_None.png
  resource/picture/quest_food/NO-4-6_1_0_None_None.png
  resource/picture/quest_food/NO-4-7_1_0_None_None.png
  resource/picture/quest_food/NO-4-7_2_1_None_None.png
  resource/picture/quest_food/NO-4-8_1_0_None_None.png
  text_color_plan.md
Labels: enhancement

#100 v1.3.1 修复了需要 ban卡 的情况下, 承载卡和冰沙幻鸡在关卡中的卡片位置会被ban卡影响而顺位加减的问题.
  function/core/FAA.py
  function/core/FAA_BattleARoundPreparation.py
Labels: bug

#101 v1.3.1 动作队列在部分cpu较差的机型上, 生产者速度>消费者速度问题, 尝试解决.
  function/core/FAA_Battle.py
  function/core_battle/Card.py
Labels: bug

#102 v1.3.1 进一步细化了ui中日志文本颜色, 采用了更适合白色背景且更多层级的配色方案.
  function/core/FAA.py
  function/core/Todo.py
  function/globals/thread_action_queue.py
  test/test_action_queue_timer.py
  text_color_plan.md
Labels: enhancement

#104 v1.3.1 大幅重构图像识别基本方法. 应用自动生成掩模和手动淹没, 实现了难以置信的 高性能 稳定性 准确度.
  function/common/bg_img_match.py
  function/common/overlay_images.py
  function/core/FAA.py
  resource/picture/item/item_mask_locked.png
  resource/picture/item/item_mask_tradable.png
  resource/picture/item/mask.png
  resource/picture/item/绑定角标-不透明部分.png
  resource/picture/item/背包/公会卡牌包.png
  resource/picture/item/背包/公会宝箱_1.png
  resource/picture/item/背包/公会宝箱_2.png
  resource/picture/item/背包/公会宝箱_3.png
  resource/picture/item/背包/助人为乐宝箱.png
  resource/picture/item/背包/四叶草箱.png
  resource/picture/item/背包/四叶草篮.png
  resource/picture/item/背包/威望币.png
  resource/picture/item/背包/水果篮子.png
  resource/picture/item/背包/礼券-遗迹古券.png
  resource/picture/item/背包/礼券.png
  resource/picture/item/背包/礼卷-遗迹古券.png
  resource/picture/item/背包/金币-大金币袋.png
  resource/picture/item/背包/金币-小金币袋.png
  resource/picture/item/背包/金币.png
  resource/picture/item/背包/香料随机礼包.png
  test/match_png/match_image.py
  test/match_png/test_match_image.py
  test/match_png/test_match_images.py
Labels: enhancement

#106 v1.3.1 添加了缘分树功能, 以达成二级密码的输入, 防止背包爆满时暗晶兑换无法激活输入框.
  .idea/workspace.sync-conflict-20231118-010307-HQ2EI7Z.xml
  battle_plan/4卡组-通用-1P+2P.json
  config/stage_info_extra.json
  function/core/FAA_ActionInterfaceJump.py
  function/core/Todo.py
  function/globals/thread_action_queue.py
  resource/picture/common/底部菜单/跳转_缘分树.png
  resource/ui/FAA_3.0.ui
Labels: bug, enhancement

#107 v1.3.1 动作队列日志, 在每次战斗前和战斗后 输出距离上一次进行该操作期间, 鼠标队列的进出次数.
  function/core_battle/CardManager.py
Labels: bug

#108 v1.3.1 自动战斗. 放卡后 检测状态前 的延时增加, 以提高识别到卡片放满的成功率. 防止一直尝试放置放满的卡片.
  function/core_battle/Card.py
Labels: bug

#109 v1.3.1 修正了没注意到动作队列生产者线程有两个, 消费者线程只有一个导致堆积, 产生动作执行延后的严重BUG .
  function/globals/thread_action_queue.py
Labels: bug

#110 v1.3.1 双线程单人. 增加了配套的 UI输出 和 调试输出, 并精简代码.
  function/core/Todo.py
Labels: enhancement

#112 v1.3.1 战斗结束时, 手动清空动作序列, 以保证不会有图标乱晃干扰图像, 并确保可以正常结束.
  function/core/FAA_Battle.py
  function/core/FAA_BattleARoundPreparation.py
Labels: bug

#114 v1.4.0 修正UI打开时, 不在主页而在高级配置页的问题.
  resource/ui/FAA_3.0.ui
Labels: bug

#115 v1.4.0-beta.1 修正暗晶商店点击过快, 无法完成兑换的问题.
  function/core/FAA.py
  function/core/FAA_BattleARoundPreparation.py
Labels: bug

#116 v1.4.0-beta.1 更新致谢名单! 感谢你们的支持!
  致谢名单.md
  致谢名单.png
Labels: documentation

#117 v1.4.0-beta.1 为萌宠神殿功能添加了运行时输出文本.
  function/core/Todo.py
Labels: enhancement

#118 v1.4.0 修改了兑换暗晶和删除物品功能的顺序, 会先删除物品, 防止包满兑换失败.
  function/core/Todo.py
Labels: bug

#119 v1.4.0-beta.1 多线程单人. 修正了2P先完成战斗的情况下的线程异常,
  function/core/QMW_2_log.py
  function/core/Todo.py
  test/test.py
Labels: bug

#120 v1.4.0-beta.1 战利品数据到服务器的功能, 增加服务器离线超时处理.
  function/core/FAA_BattleARoundPreparation.py
Labels: bug

#121 v1.4.0-beta.1 新增功能, 将配对的游戏窗口 挪动到所有窗口的Z轴底层 or 切换到顶层 的按钮.
  function/common/bg_img_screenshot.py
  function/core/FAA.py
  function/core/FAA_ActionQuestReceiveRewards.py
  function/core/FAA_BattleARoundPreparation.py
  function/core/QMW_3_service.py
  function/core_battle/CardManager.py
  resource/ui/FAA_3.0.ui
Labels: enhancement

#122 v1.4.0-beta.2 在对背包中的物品进行操作前, 增加了10s等待时间, 以确保图标均加载完成.
  function/core/FAA.py
Labels: bug

#123 v1.4.0-beta.2 \n位置: 图像识别 - 战利品识别 - 基于有向无环图的战利品识别路径规划. 问题: 以错误的方式进行有向无环图储存. 在储存和读取多次后, 导致有向无环图成环, 导致graph更新失败. 方案: 节点路径计算和有向无环图的保存和构筑分离.
  function/core/analyzer_of_loot_logs.py
Labels: bug, enhancement

#124 v1.4.0-beta.2 位置: 图像识别 - 战利品识别 - 基于有向无环图的战利品识别路径规划. 问题: 将有向无环图以错误的方式计算, 以寻求同优先级的节点. 方案: 以寻找graph中的最长链作为新的方案.
  function/core/analyzer_of_loot_logs.py
Labels: bug, enhancement

#125 v1.4.0-beta.2 图像识别 - 战利品识别 优化代码可读性增加注释, 修复多线程读写时的卡死问题.
  function/core/Todo.py
  function/core/analyzer_of_loot_logs.py
Labels: bug, enhancement

#127 v1.4.0-beta.2 领取温馨礼包. 如果欢乐互娱炸服了, 会超时步过, 不再卡死.
  function/core/Todo.py
Labels: bug

#128 v1.4.0-beta.2 Update requirement.txt
  requirements.txt
Labels: documentation

#129 v1.4.0-beta.2 自动战斗 - 添加任务卡, 如果选择了空战斗方案进行战斗, 导致卡死的问题已修复.
  function/core/FAA.py
Labels: bug

#130 v1.4.0-beta.2 公会任务 - 识别任务, 限定了识别范围, 略微提高了识别性能.
  function/core/FAA.py
Labels: enhancement

#132 v1.4.0-beta.3 浇水施肥摘果 - 界面跳转. 从 公会界面->任务和花园界面 时, 限制50次, 若持续失败, reload游戏, 最多reload两次跳过.
  function/core/FAA.py
Labels: enhancement

#133 v1.4.0-beta.3 浇水施肥摘果 - 界面跳转. 花园界面->公会界面增加图像检测, 防止游戏UI卡死后无限施肥.
  function/core/FAA.py
Labels: bug

#134 v1.4.0-beta.3 浇水施肥摘果. 主页面->公会界面. 增加图像检测, 防止游戏UI卡死后无限施肥.
  function/core/FAA.py
Labels: bug

#135 v1.4.0-beta.3 浇水施肥摘果. 对几乎所有的识图框定范围, 去除了多余的点击, 准确度↑ 速度↑
  function/core/FAA.py
Labels: enhancement

#136 v1.4.0-beta.3 浇水施肥摘果. 当步骤总计100次未能完成任务后, 跳过该步骤.
  function/core/FAA.py
Labels: bug

#137 v1.4.0-beta.3 战利品识别 - bug修复. 修复识别结果为None值是非dict格式导致更新有向无环图时的错误.
  function/core/FAA_BattleARoundPreparation.py
  function/core/Todo.py
Labels: bug

#138 v1.4.0-beta.3 图像识别 - 战利品识别. 根据战利品数据是否可以被构筑为有向无环图, 判断战利品数据是否有效.
  function/core/FAA_BattleARoundPreparation.py
  function/core/Todo.py
  function/core/analyzer_of_loot_logs.py
  function/scattered/loots_and_chest_data_save_and_post.py
Labels: enhancement

#139 v1.3.1 图像识别. 将用于绑定/不绑物品掩模的数字遮罩部分, 增加两像素高度, 以确保在战利品识别中的数字部分能被移除. 注: 战利品的数字14像素高, 背包物品的数字12像素高.
  function/core/FAA.py
  function/core/Todo.py
  resource/picture/item/item_mask_locked.png
  resource/picture/item/item_mask_tradable.png
  resource/picture/quest_guild/ui_guild.png
Labels: bug

#142 v1.4.0-beta.4 项目结构调整, 增加维护性. 大赛图像资源例行更新.
  function/common/one_time_match.py
  function/core/FAA.py
  function/core/QMW_3_service.py
  resource/picture/item/战利品/冰冻宝石.png
  resource/picture/item/战利品/冰煮蛋器投手配方.png
  resource/picture/item/战利品/冰鸡蛋.png
  resource/picture/item/战利品/极寒冰沙配方.png
  resource/picture/item/战利品/绿宝石.png
  resource/picture/item/战利品/雪山.png
  resource/picture/item/战利品/龙虾配方.png
  resource/picture/item/物品-双暴卡.png
  resource/picture/item/物品-掩模-不绑定.png
  resource/picture/item/物品-掩模-绑定.png
  resource/picture/item/物品-绑定角标.png
  resource/picture/item/物品-背包-使用-被选中.png
  resource/picture/item/物品-背包-使用.png
  resource/picture/quest_food/NO-1-10_2_1_None_None__.png
  resource/picture/quest_food/NO-1-12_2_1_None_None_.png
  resource/picture/quest_food/NO-1-6_2_1_None_None_.png
  resource/picture/quest_food/NO-1-7_1_1_None_None__.png
  resource/picture/quest_food/NO-2-10_2_1_None_None_.png
  resource/picture/quest_food/NO-2-10_2_1_None_木盘子.png
  resource/picture/quest_food/NO-2-12_2_1_None_棉花糖_.png
  resource/picture/quest_food/NO-2-15_2_1_None_None___.png
  resource/picture/quest_food/NO-2-15_2_1_None_None____.png
  resource/picture/quest_food/NO-2-5_2_1_None_None__.png
  resource/picture/quest_food/NO-2-7_2_0_None_None__.png
  resource/picture/quest_food/NO-2-7_2_1_None_None__.png
  resource/picture/quest_food/NO-2-7_2_1_None_木盘子_.png
  resource/picture/quest_food/NO-2-8_2_1_None_None___.png
  resource/picture/quest_food/NO-2-9_2_1_None_None__.png
  resource/picture/quest_food/NO-4-2_1_1_None_None_.png
  resource/picture/quest_food/NO-4-3_1_1_None_None___.png
  resource/picture/quest_food/NO-5-1_2_1_None_None__.png
  resource/picture/quest_food/NO-5-2_1_1_None_None_.png
  resource/picture/quest_food/NO-5-2_2_1_None_None__.png
  test/match_png/test_match_image.py
  test/test.py
Labels: enhancement

#143 v1.4.0-beta.4 任务列表. 增加了一个按钮, 点击显示关于FAA战斗逻辑的若干提示文本.
  function/core/QMW_3_service.py
  function/core/QMW_TipBattle.py
  function/core/QMW_TipWarmGift.py
Labels: enhancement

#144 v1.4.0-beta.4 尝试实现自动适配高DPI缩放.
  function/core/QMW_3_service.py
  resource/ui/FAA_3.0.ui
Labels: enhancement

#145 v1.4.0-beta.4 日志输出. 增加图像输出功能.
  function/core/QMW_2_log.py
Labels: enhancement

#146 v1.4.0-beta.4 天知完全修复了战斗方案执行器V3
  function/core/FAA_Battle.py
  function/core_battle/Card.py
  function/core_battle/CardManager.py
  function/core_battle/CardQueue.py
  function/globals/thread_action_queue.py
Labels: bug

#147 v1.4.0-beta.4 自动战斗 - 自动承载/任务卡. 其插入位置不再是首位, 而是第二位, 解决部分无风化玩家的开局产火问题.
  function/core/FAA.py
Labels: enhancement

#148 v1.4.0-beta.4 深渊完全修复了战斗方案执行器V3 bug
  a_tips.md
  config/stage_info_extra.json
  function/core/FAA_Battle.py
  function/core_battle/Card.py
  function/core_battle/CardManager.py
  function/globals/thread_action_queue.py
Labels: bug

#149 v1.4.0-beta.4 致谢名单更新! 感谢你们的支持!
  致谢名单.png
Labels: documentation

#150 v1.4.0-beta.4 图像识别 - 战利品识别. 将绑定物的名称中的空格移除. 不再设置潜在绑定名单以识别, 而是全部识别.
  function/core/analyzer_of_loot_logs.py
Labels: enhancement

#151 v1.4.0-beta.4 暗晶兑换. 再次上调兑换点击间隔, 1.33->2s, 以确保可以完成兑换.
  function/core/FAA.py
  function/core_battle/CardManager.py
  function/core_battle/CardQueue.py
Labels: bug

#153 v1.4.0-beta.4 系统稳定性. 为所有的json读写添加全局自旋锁, 以防止双线程作战时因读写冲突出现bug.
  customize_todo/transformer_of_todo_json_from_excel.py
  function/core/FAA.py
  function/core/QMW_1_load_settings.py
  function/core/QMW_2_log.py
  function/core/QMW_EditorOfBattlePlan.py
  function/core/QMW_Other.py
  function/core/Todo.py
  function/core/analyzer_of_loot_logs.py
  function/globals/extra.py
  function/scattered/loots_and_chest_data_save_and_post.py
  function/scattered/read_json_to_stage_info.py
Labels: bug

#154 v1.4.0-beta.4 将是否需要使用钥匙 从 is_use_key 的字段和变量全部统一为 need_key.
  function/core/FAA.py
  function/core/Todo.py
  function/core_battle/Card.py
  test/test.py
Labels: bug

#155 v1.4.0-beta.4 自定义作战序列. 重新维护自定义作战序列包括: 更新了 自动转换excel为json的.py文件 和 excel模板; 更新了 todo_example.json 模板文件; 重写简易文档.
  customize_todo/be_transformed.xlsx
  customize_todo/todo_example.json
  customize_todo/transformer_of_todo_json_from_excel 暂时停摆, 如有需要请根据todo_example手动书写.txt
  customize_todo/transformer_of_todo_json_from_excel.py
  customize_todo/自定义作战序列 - 用前必读!.txt
Labels: documentation, enhancement

#156 v1.4.0-beta.4 战斗执行器 - 使用钥匙. 完成了该被遗漏的功能.
  function/core/FAA.py
  function/core/FAA_Battle.py
  function/core/Todo.py
  function/core_battle/CardManager.py
Labels: enhancement

#157 v1.4.0-beta.4 战斗执行器 - 图像识别 - 卡片状态. 不再同时识别卡片最上排和最下排像素, 而是仅识别最上排像素. 该改动旨在修复以下bug: 1. 由于当卡片数在15+时, 会出现竖向排布的卡片, 这些卡片的最下一排像素被下一张卡片的最上一排遮挡, 导致目前的函数无法正确识别状态. 2. 火苗的收集动画常遮挡部分卡片下排像素, 导致误判.
  function/core_battle/Card.py
Labels: bug, enhancement

#158 全自动大赛 - 运行逻辑. 当钥匙不足, 任务需要使用钥匙时, 出现无限刷关循环的问题已修复.
  README.md
  a_tips.md
  function/core/FAA.py
  function/core/FAA_Battle.py
  function/core/FAA_BattleARoundPreparation.py
  function/core/QMW_EditorOfBattlePlan.py
  function/core/Todo.py
  function/core_battle/CardManager.py
  function/core_battle/CardQueue.py
  function/globals/extra.py
Labels: bug

#159 v1.4.0-beta.4 自动战斗 - 方案生成. 当 ban_card_list == ["None"]时, 仍然会识图ban冰淇淋和幻幻鸡浪费时间, 现已修复该问题.
  function/core/FAA.py
Labels: bug

#160 v1.4.0-beta.4 全自动大赛 - 图像资源. 例行更新. 感谢LTPTR提供.
  customize_todo/from_transformer.json
  logs/item_ranking_dag_graph.json
  resource/logo/圆角-FetTuo-192x.png
  resource/logo/圆角-FetTuo-512x.png
  resource/picture/item/关于掩模.txt
  resource/picture/quest_food/NO-1-6_2_1_None_None_.png
  resource/picture/quest_food/NO-1-7_1_1_None_None__.png
  resource/picture/quest_food/NO-1-7_2_1_None_None_.png
  resource/picture/quest_food/NO-1-8_1_1_None_None .png
  resource/picture/quest_food/NO-2-10_1_1_None_None.png
  resource/picture/quest_food/NO-2-15_2_1_None_None___.png
  resource/picture/quest_food/NO-2-15_2_1_None_None____.png
  resource/picture/quest_food/NO-2-7_2_1_None_木盘子_.png
  resource/picture/quest_food/NO-2-8_2_1_None_None___.png
  resource/picture/quest_food/NO-4-1_2_1_None_None__.png
  resource/picture/quest_food/NO-5-1_1_0_None_狮子座精灵,油灯,咖啡粉,糖葫芦炮弹,瓜皮护罩,木盘子,麦芽糖,樱桃反弹布丁.png
  resource/picture/quest_food/NO-5-2_2_1_None_None__.png
  resource/picture/quest_food/NO-5-3_2_0_None_None.png
  resource/picture/quest_food/NO-5-4_2_0_None_None.png
  resource/picture/quest_food/NO-5-4_2_1_None_None_.png
Labels: enhancement

#161 v1.4.0-beta.4 战斗方案解析器 - 修正了如果战斗方案为空(花瓶), 插入倒index1会报错的问题.
  function/core/FAA.py
Labels: bug

#162 v1.4.0-beta.8 重新修订beta版本号规则. 不再以fix后缀标识, 而是直接累加. 之前累加的四个fix版本号, 被包含于beta版本号中.
  battle_plan/EX-梦境通用卡组-1-6通解-1P.json
  battle_plan/EX-梦境通用卡组-1-6通解-2P.json
  function/core/FAA.py
  function/core/QMW_2_log.py
  function/core/QMW_3_service.py
  function/core/Todo.py
  function/resource_preload.py
  function/tools/get_all_obstacle.py
  logs/item_ranking_dag_graph.json
  resource/picture/quest_food/EX-5-1_1_1_None_None_.png
  resource/picture/quest_food/NO-1-11_2_1_None_None.png
  resource/picture/quest_food/NO-1-11_2_1_None_糖葫芦炮弹,瓜皮护罩,狮子座精灵,樱桃反弹布丁,油灯,麦芽糖.png
  resource/picture/quest_food/NO-1-12_1_1_None_None.png
  resource/picture/quest_food/NO-1-5_2_1_None_None__.png
  resource/picture/quest_food/NO-1-7_1_1_None_None___.png
  resource/picture/quest_food/NO-1-7_1_1_None_None_____.png
  resource/picture/quest_food/NO-1-7_1_1_None_None______.png
  resource/picture/quest_food/NO-1-7_2_1_None_None____.png
  resource/picture/quest_food/NO-1-9_1_1_None_糖葫芦,瓜皮护罩,狮子座精灵,油灯,樱桃反弹布丁.png
  resource/picture/quest_food/NO-1-9_2_1_None_None__.png
  resource/picture/quest_food/NO-2-10_2_1_None_None___.png
  resource/picture/quest_food/NO-2-11_2_1_None_None___.png
  resource/picture/quest_food/NO-2-12_2_1_None_None__.png
  resource/picture/quest_food/NO-2-13_2_1_None_None__.png
  resource/picture/quest_food/NO-2-15_2_1_None_None_____.png
  resource/picture/quest_food/NO-2-1_1_1_None_None_.png
  resource/picture/quest_food/NO-2-1_2_1_None_None__.png
  resource/picture/quest_food/NO-2-3_1_1_None_None.png
  resource/picture/quest_food/NO-2-5_1_1_None_None__.png
  resource/picture/quest_food/NO-2-6_1_1_None_None.png
  resource/picture/quest_food/NO-2-7_1_1_None_None_.png
  resource/picture/quest_food/NO-2-7_2_1_None_木盘子__.png
  resource/picture/quest_food/NO-4-2_2_1_None_None_.png
  resource/picture/quest_food/NO-4-2_2_1_None_None__.png
  resource/picture/quest_food/NO-4-3_2_1_None_None_.png
  resource/picture/quest_food/NO-4-4_2_1_None_狮子座精灵,油灯,樱桃反弹布丁.png
  resource/picture/quest_food/NO-4-5_1_1_None_None__.png
  resource/picture/quest_food/NO-4-5_2_1_None_None__.png
  resource/picture/quest_food/NO-4-5_2_1_None_None___.png
  resource/picture/quest_food/NO-4-7_2_0_None_瓜皮护罩,樱桃反弹布丁,木盘子,麦芽糖.png
  resource/picture/quest_food/NO-5-2_2_1_None_None___.png
  resource/picture/quest_food/NO-5-4_2_1_None_None__.png
  resource/picture/quest_food/NO-5-5_2_1_None_None_.png
  resource/picture/quest_food/NO-5-5_2_1_None_None__.png
  resource/ui/FAA_3.0.ui
Labels: documentation

#163 v1.4.0-beta.9 维护更新番外副本-沙漠的图像资源文件和关卡信息. 以支持对应副本的自动导航.
  config/stage_info.json
  resource/picture/stage/EX-2-1.png
  resource/picture/stage/EX-2-2.png
  resource/picture/stage/EX-2-3.png
  resource/picture/stage/EX-2-4.png
  resource/picture/stage/EX-2-5.png
  resource/picture/stage/EX-2-6.png
  resource/picture/stage/EX-2-7.png
  resource/picture/stage/EX-2-8.png
  resource/picture/stage/EX-2-9.png
  resource/picture/stage/EX-2.png
Labels: enhancement

#164 v1.4.0-beta.9 关卡信息 - 额外关卡信息 - 悬赏关卡. 添加等级限制参数.
  config/stage_info_extra.json
Labels: bug

#165 v1.4.0-beta.9 自动战斗 - 战前准备 - 选任务卡. 解决部分背包格子较多的用户无法正常选择任务卡的问题.
  function/core/FAA_BattleARoundPreparation.py
Labels: bug

#166 v1.4.0-beta.9 战斗方案 - 默认方案. 重新整理 默认方案们命名 和 默认配置模板. 更新来自作者的有向无环图.
  battle_plan/3卡组-难关-1P+2P.json
  battle_plan/3卡组-难关-魔塔双人-100-1P.json
  battle_plan/3卡组-难关-魔塔双人-100-2P.json
  battle_plan/EX-梦境通用卡组-玫瑰花园夜-1P.json
  battle_plan/EX-梦境通用卡组-玫瑰花园夜-2P.json
  battle_plan_not_active/冰跨-1P.json
  battle_plan_not_active/冰跨-2P.json
  battle_plan_not_active/本文件夹用于储存部分暂时无用的战斗方案, 不会被faa读取.txt
  battle_plan_not_active/番外-梦境-1-7通解-1P.json
  battle_plan_not_active/番外-梦境-1-7通解-2P.json
  battle_plan_not_active/番外-梦境-悬浮梦境-1+2P.json
  battle_plan_not_active/番外-梦境-玫瑰日-1+2P.json
  battle_plan_not_active/番外-雪山-通解-1P.json
  battle_plan_not_active/番外-雪山-通解-2P.json
  battle_plan_not_active/番外-雷城-街区钟楼-1P.json
  battle_plan_not_active/番外-雷城-街区钟楼-2P.json
  battle_plan_not_active/番外-雷城-阴乐劫夜-1P.json
  battle_plan_not_active/番外-雷城-阴乐劫夜-2P.json
  battle_plan_not_active/番外-雷城-阴乐劫日-1P.json
  battle_plan_not_active/番外-雷城-阴乐劫日-2P.json
  battle_plan_not_active/魔塔-单人-136 to 139-海星.json
  battle_plan_not_active/魔塔-单人-136 to 140-海星.json
  battle_plan_not_active/魔塔-单人-146 to 150-海星.json
  battle_plan_not_active/魔塔-单人-151 to 155-海星.json
  battle_plan_not_active/魔塔-单人-156 to 160-未完成.json
  battle_plan_not_active/魔塔-单人-161 to 165-未完成.json
  battle_plan_not_active/魔塔-单人-低层方案-未完成.json
  battle_plan_old/2卡组-速刷-生煎-1P.json
  battle_plan_old/2卡组-速刷-生煎-2P.json
  config/settings_template.json
  logs/item_ranking_dag_graph.json
Labels: enhancement

#167 v1.4.0-beta.9 互换了 萌宠神殿功能 和 双人魔塔功能 的 位置.
  config/settings_template.json
  logs/item_ranking_dag_graph.json
  resource/picture/stage/EX-2.png
  resource/ui/FAA_3.0.ui
Labels: enhancement

#168 v1.4.0-beta.9 每日签到. 为其中各项功能的增加sleep并延长识别失败判定时间. 以支持在差网络 / 低配置 电脑上的正确运行.
  config/stage_info_extra.json
  function/core/FAA.py
  function/core/QMW_1_load_settings.py
  function/core/Todo.py
  logs/item_ranking_dag_graph.json
Labels: bug

#169 v1.4.0-beta.9 更新了致谢名单, 感谢你们!
  致谢名单.md
  致谢名单.png
Labels: documentation

#171 v1.4.0-beta.9 关卡进出 - 地图切换. 跟随游戏中地图UI上的字体更换, 更新图片资源.
  resource/picture/map/0.png
  resource/picture/map/1.png
  resource/picture/map/2.png
  resource/picture/map/3.png
  resource/picture/map/4.png
  resource/picture/map/5.png
Labels: enhancement

#172 v1.4.0-beta.9 日志输出 - 战利品和宝箱. 场均->合计. 改用图片拼接, 优化视觉体验.
  function/core/QMW_2_log.py
  function/core/Todo.py
  function/scattered/create_drops_image.py
Labels: enhancement

#173 v1.4.0-beta.9 自动战斗 - 半自动拾取. 拾取范围 半屏->全图.
  function/core/FAA_Battle.py
Labels: enhancement

#174 v1.4.0-beta.9 关卡代号一览. 适配星际穿越地图.
  function/core/QMW_TipStageID.py
Labels: enhancement

#175 v1.4.0-beta.9 图像识别 - 战利品识别. 添加番外副本特殊掉落代币的图片资源.
  a_tips.md
  logs/item_ranking_dag_graph.json
  resource/picture/item/战利品/仙人球.png
  resource/picture/item/战利品/冰水晶.png
  resource/picture/item/战利品/奇境蘑菇.png
  resource/picture/item/战利品/雷城金币.png
  resource/picture/stage/NO-2-10.png
  resource/picture/stage/NO-2-14.png
  resource/picture/stage/NO-2-15.png
  resource/picture/stage/NO-3-1.png
  resource/picture/stage/NO-3-2.png
  resource/picture/stage/NO-3-3.png
  resource/picture/stage/NO-3-4.png
  resource/picture/stage/NO-3-5.png
  resource/picture/stage/NO-3-6.png
Labels: enhancement

#176 v1.4.0-beta.9 入门文档更新.
  [入门]FAA从入门到神殿.docx
  [入门]FAA从入门到神殿.pdf
Labels: documentation

#177 v1.4.0-beta.10 修复双人魔塔和萌宠神殿交换顺序后, 萌宠神殿完成后不退出, 需触发防卡死才能正常继续的问题.
  function/core/Todo.py
Labels: bug

#178 v1.4.0-beta.10 日志输出 - 战利品和宝箱. 无掉落时, 增加None字样. 识别失败时, 为?添加文本黑边框, 提高视觉体验.
  function/scattered/create_drops_image.py
Labels: enhancement

#179 v1.4.0-beta.10 图像识别 - 战利品识别. 添加了星际穿越地图前四关掉落物的图像资源.
  resource/picture/item/战利品/堡王徽章A.png
  resource/picture/item/战利品/堡王徽章B.png
  resource/picture/item/战利品/外星鸟蛋.png
  resource/picture/item/战利品/太空服.png
  resource/picture/item/战利品/巨螯蟹.png
  resource/picture/item/战利品/年糕条.png
  resource/picture/item/战利品/微波炉.png
  resource/picture/item/战利品/微波炉爆弹配方.png
  resource/picture/item/战利品/户外电源.png
  resource/picture/item/战利品/星际钥匙.png
  resource/picture/item/战利品/火锅底料.png
  resource/picture/item/战利品/香辣年糕蟹初级技能书.png
  resource/picture/item/战利品/香辣年糕蟹终极技能书.png
  resource/picture/item/战利品/香辣年糕蟹配方.png
  resource/picture/item/战利品/香辣年糕蟹高级技能书.png
Labels: enhancement

#180 v1.4.0-beta.10 关卡进出 - 地图切换. 修复了浮空岛地图无法正常识别进入的问题.
  resource/picture/map/4.png
Labels: bug

#181 v1.4.0 经过长期迭代和测试, 该版本趋于稳定, 提升为正式版.
  logs/match_failed/_此文件夹用于存放识图失败的例图.txt
  test/test.py
Labels: documentation

#184 v1.4.1-beta.1 界面跳转 - 关卡进入 - 工会副本. 添加2s动作完成后等待, 以防止部分配置网络较差的电脑进入失败.
  function/core/FAA_ActionInterfaceJump.py
Labels: bug

#185 v1.4.1-beta.1 读取关卡信息. 会优先使用stage_info_extra.json, 而非 stage_info.json.
  function/core/QMW_3_service.py
  function/scattered/read_json_to_stage_info.py
  logs/item_ranking_dag_graph.json
Labels: enhancement

#186 v1.4.1-beta.1 自动战斗 - 定时使用武器技能&自动拾取. 考虑到火苗消失时间是7s, 故修改原本的10s间隔为7s间隔.
  function/core_battle/CardManager.py
Labels: enhancement

#187 v1.4.1-beta.1 关卡进出. 更新 星际穿越地图 苏打水星(夜) 的 进入图片. 该更新作为 1.4.0 - r1 内容发布.
  resource/picture/map/6.png
  resource/picture/stage/NO-6-4.png
Labels: enhancement

#188 v1.4.1-beta.1 关卡进出. 更新 星际穿越和浮空岛 的 进入图片. 该更新作为 1.4.0 - r1 内容发布.
  battle_plan/星际穿越卡组-苏打水星夜-无投手-1+2P.json
  config/stage_info.json
  logs/item_ranking_dag_graph.json
  resource/picture/map/4.png
  resource/picture/map/6.png
  resource/picture/stage/NO-6-1.png
  resource/picture/stage/NO-6-2.png
  resource/picture/stage/NO-6-3.png
  resource/picture/stage/NO-6-4.png
Labels: enhancement

#189 v1.4.1-beta.1 文本配色方的应用采用采用color_level参数, 取代原有的颜色rgb值, 简洁清晰.
  function/core/QMW_2_log.py
  function/core/QMW_3_service.py
  function/core/Todo.py
Labels: enhancement

#190 v1.4.1-beta.1 settings.json校验. 将以模板文件为基础, 订正settings中的键和值类型. 以支持跨版本迁移配置.
  function/core/QMW_1_load_settings.py
Labels: enhancement

#191 v1.4.1-beta.1 识图点击功能. 支持点击和识图使用不同的句柄.
  function/common/bg_img_match.py
Labels: enhancement

#192 v1.4.1-beta.1 日氪一元. 完成了该功能的全部部分. 包括UI/配置/操作的实现.
  function/core/FAA.py
  function/core/QMW_1_load_settings.py
  function/core/Todo.py
  resource/picture/common/顶部菜单/每日充值.png
  resource/picture/top_up_money/充值界面_游币兑换.png
  resource/picture/top_up_money/充值界面_游币兑换√.png
  resource/picture/top_up_money/充值界面_立即充值.png
  resource/picture/top_up_money/充值界面_请输入.png
  resource/picture/top_up_money/充值界面_请输入√.png
  resource/picture/top_up_money/充值界面_退出.png
  resource/picture/top_up_money/每日必充_充值.png
  resource/picture/top_up_money/每日必充_判定点.png
  resource/picture/top_up_money/每日必充_领取.png
  resource/ui/FAA_3.0.ui
Labels: enhancement

#193 v1.4.1-beta.1 送花输入二级. 修正了罕见情况下无法正常点击到二级输入框的问题.
  function/core/FAA.py
  function/core/Todo.py
  function/scattered/gat_handle.py
  logs/item_ranking_dag_graph.json
  test/match_png/test_match_image.py
  test/test.py
  test/test_screenshot.py
  text_color_plan.md
Labels: bug

#194 v1.4.1-beta.1 更新settings.json配置模板.
  config/settings_template.json
Labels: enhancement

#195 v1.4.1-beta.1 等级不足时不再尝试营地领钥匙.
  function/core/FAA.py
  logs/item_ranking_dag_graph.json
Labels: bug

#197 v1.4.1-beta.1 尝试修复了点击中止按钮在大部分情况下会卡死主线程的bug.
  function/core/QMW_3_service.py
  function/core/Todo.py
Labels: bug

#198 v1.4.1-beta.1 Remove __pycache__ from Git tracking
  function/__pycache__/__init__.cpython-311.pyc
  function/battle/__pycache__/Card.cpython-311.pyc
  function/battle/__pycache__/CardManager.cpython-311.pyc
  function/battle/__pycache__/CardQueue.cpython-311.pyc
  function/battle/__pycache__/FAABattle.cpython-311.pyc
  function/battle/__pycache__/__init__.cpython-311.pyc
  function/battle/__pycache__/get_position_in_battle.cpython-311.pyc
  function/common/__pycache__/__init__.cpython-311.pyc
  function/common/__pycache__/bg_p_match.cpython-311.pyc
  function/common/__pycache__/bg_p_screenshot.cpython-311.pyc
  function/common/__pycache__/get_system_dpi.cpython-311.pyc
  function/common/__pycache__/match.cpython-311.pyc
  function/common/__pycache__/thread_with_exception.cpython-311.pyc
  function/globals/__pycache__/__init__.cpython-311.pyc
  function/globals/__pycache__/get_paths.cpython-311.pyc
  function/globals/__pycache__/init_resources.cpython-311.pyc
  function/globals/__pycache__/thread_action_queue.cpython-311.pyc
  function/scattered/__pycache__/__init__.cpython-311.pyc
  function/scattered/__pycache__/gat_handle.cpython-311.pyc
  function/scattered/__pycache__/get_channel_name.cpython-311.pyc
  function/scattered/__pycache__/get_customize_todo_list.cpython-311.pyc
  function/scattered/__pycache__/get_list_battle_plan.cpython-311.pyc
  function/scattered/__pycache__/read_json_to_stage_info.cpython-311.pyc
  function/script/__pycache__/FAA.cpython-311.pyc
  function/script/__pycache__/__init__.cpython-311.pyc
  function/script/__pycache__/analyzer_of_loot_logs.cpython-311.pyc
  function/script/__pycache__/ui_0_load_ui_file.cpython-311.pyc
  function/script/__pycache__/ui_1_load_opt.cpython-311.pyc
  function/script/__pycache__/ui_2_battle_with_ui.cpython-311.pyc
  function/script/__pycache__/ui_3_advanced_settings_ui.cpython-311.pyc
Labels: bug

#200 v1.4.1-beta.1 将.gitignore上传到git, 以防止pycache 日志 用户配置文件 被上传到git.
  .gitignore
  function/core/Todo.py
  logs/item_ranking_dag_graph.json
Labels: enhancement

#202 v1.4.1-beta.1 将README.md的图片放在git中而非github图床.
  README.md
  md_img/关卡一览.png
  md_img/战斗方案编辑器.png
  md_img/流程配置.png
  md_img/窗口名和游戏名称.png
  md_img/运行主页.png
  md_img/队列遍历.png
  md_img/高级选项.png
Labels: documentation

#204 v1.4.1-beta.1
  function/core/FAA.py
Labels: bug

#205 v1.4.1-beta.1 杂项.
  .gitignore
  config/cus_images/一些常用的图标/任意通用包裹.png
  config/cus_images/背包_装备_需使用的/任意通用包裹.png
  resource/picture/quest_food/EX-2-7_2_1_None_None.png
  resource/picture/quest_food/NO-2-11_2_1_None_None_.png
  resource/picture/quest_food/NO-2-14_2_1_None_None___.png
  resource/picture/quest_food/NO-4-8_1_1_None_None_.png
  resource/picture/quest_food/NO-5-4_1_1_None_None.png
Labels: enhancement

#206 v1.4.1-beta.1 将部分错误上传到git的 settings.json / running_log.log 移除.
  .gitignore
  config/settings.json
  logs/running_log.log
Labels: bug

#207 v1.4.1-beta.1 Update README.md 更新关于默认卡组部分的介绍.
  README.md
Labels: documentation

#208 Stare abyss Update README.md 更新爱发电暂时暴毙后的赞助渠道
  README.md
  battle_plan/番外-沙漠通用卡组-通用-1P+2P.json
  battle_plan/番外-沙漠通用卡组-鱼骨夜-1P+2P.json
  logs/item_ranking_dag_graph.json
  md_img/FAA-赞赏码.jpg
Labels: documentation

#210 v1.4.1-beta.1 将欢乐假期关卡纳入FAA自动建房支持中, 代号H-0-0.
  config/stage_info_extra.json
  function/core/FAA_ActionInterfaceJump.py
  function/core/Todo.py
Labels: enhancement

#211 v1.4.1-beta.1 战利品识别. 修正了因游戏中战利品和背包物品使用绑定角标图像不同, 导致战利品的绑定无法被正确识别出的问题.
  function/common/one_time_match.py
  function/core/FAA.py
  function/core/analyzer_of_loot_logs.py
  function/scattered/create_drops_image.py
  resource/picture/item/物品-绑定角标-战利品.png
  resource/picture/item/物品-绑定角标-背包.png
  test/match_png/test_match_what this block is.py
Labels: bug

#212 v1.4.1-beta.1 UI美化. 美化了 [通过鼠标拖动到窗口获取句柄按钮] 的UI呈现.
  resource/ui/FAA_3.0.ui
  resource/ui/draglabel.py
Labels: enhancement

#213 v1.4.1-beta.1 尝试修正了点击中止运行按钮后, 主线程卡死的问题. (第三次)
  function/core/Todo.py
Labels: bug

#214 v1.4.1-beta
  function/core/QMW_0_load_ui_file.py
  function/core/QMW_TipStageID.py
  logs/item_ranking_dag_graph.json
Labels: documentation

#215 v1.4.1-beta.1 修复多人协同中, 被异常回调的修正.
  function/common/bg_img_match.py
  resource/ui/FAA_3.0.ui
Labels: bug

#217 v1.4.1-beta.1 提高识别使用任务卡时, 截图的粒度. 以支持背包格子过多的玩家, 或游戏本身卡顿带来的功能异常.
  function/core/FAA.py
  function/core/FAA_Battle.py
  function/core/FAA_BattleARoundPreparation.py
  function/core_battle/Card.py
  function/deprecated/old_battle_loop.py
Labels: bug

#216 v1.4.1-beta.1 检查创建OCR目录中, 存放字块的子目录的存在
  function/scattered/match_ocr_text/match_text.py
Labels: bug
