Repository StareAbyss/FoodsVsMiceAutoAssistant, pull requests merged in 2024-12, with the labels that each got.

#520 fix(战斗方案编辑器): 修复第一次加载方案时, 初始不加载第0波的问题.
  function/core/QMW_EditorOfBattlePlan.py
Labels: Git-Fix

#521 fix(公会管理器): 修复视图中, 游戏中有人退会后, 名称列和数据列错位的问题.
  function/core/QMW_3_service.py
Labels: Git-Fix, Module-UI

#522 style: 优化日志输出内容和格式, 更新赞助致谢名单!
  function/core/QMW_1_log.py
  function/scattered/get_stage_info_online.py
  致谢名单.png
Labels: 🕹️Module-UI, Git-Perf

#523 build(自动带卡): 支持更多卡片(+49)
  resource/image/card/准备房间/主神-1.png
  resource/image/card/准备房间/冥神-3.png
  resource/image/card/准备房间/双鱼座精灵-1.png
  resource/image/card/准备房间/双鱼座精灵-2.png
  resource/image/card/准备房间/壮壮牛-0.png
  resource/image/card/准备房间/壮壮牛-1.png
  resource/image/card/准备房间/壮壮牛-2.png
  resource/image/card/准备房间/天神-3.png
  resource/image/card/准备房间/巨神-3.png
  resource/image/card/准备房间/弹弹鸡-0.png
  resource/image/card/准备房间/弹弹鸡-1.png
  resource/image/card/准备房间/弹弹鸡-2.png
  resource/image/card/准备房间/扑克牌护罩-3.png
  resource/image/card/准备房间/投弹猪-0.png
  resource/image/card/准备房间/投弹猪-1.png
  resource/image/card/准备房间/投弹猪-2.png
  resource/image/card/准备房间/投篮虎-0.png
  resource/image/card/准备房间/投篮虎-1.png
  resource/image/card/准备房间/投篮虎-2.png
  resource/image/card/准备房间/曙光女神-0.png
  resource/image/card/准备房间/曙光女神-1.png
  resource/image/card/准备房间/机械汪-0.png
  resource/image/card/准备房间/机械汪-1.png
  resource/image/card/准备房间/机械汪-2.png
  resource/image/card/准备房间/泡泡龙-0.png
  resource/image/card/准备房间/泡泡龙-1.png
  resource/image/card/准备房间/泡泡龙-2.png
  resource/image/card/准备房间/烤蜥蜴投手-0.png
  resource/image/card/准备房间/烤蜥蜴投手-1.png
  resource/image/card/准备房间/烤蜥蜴投手-2.png
  resource/image/card/准备房间/煮蛋器投手-0.png
  resource/image/card/准备房间/煮蛋器投手-1.png
  resource/image/card/准备房间/煮蛋器投手-2.png
  resource/image/card/准备房间/猪猪加强器-2.png
  resource/image/card/准备房间/糖渍刺梨-0.png
  resource/image/card/准备房间/糖渍刺梨-1.png
  resource/image/card/准备房间/糖渍刺梨-2.png
  resource/image/card/准备房间/钵钵鸡-0.png
  resource/image/card/准备房间/钵钵鸡-1.png
  resource/image/card/准备房间/雪糕投手-0.png
  resource/image/card/准备房间/雪糕投手-1.png
  resource/image/card/准备房间/雪糕投手-2.png
  resource/image/card/准备房间/飞鱼喵-0.png
  resource/image/card/准备房间/飞鱼喵-1.png
  resource/image/card/准备房间/飞鱼喵-2.png
Labels: Git-Build, 🧐Module-Drop

#525 build(公会任务): 修复穿越苏打水星(日)资源命名错误.
  resource/image/quest_guild/4/NO-6-3_带#香辣年糕蟹.png
Labels: Git-Build

#526 build(关卡信息): 更新online部分.
  config/stage_info_online.json
Labels: Git-Build

#527 build(道具识别图优化): 资源更新
  logs/item_ranking_dag_graph.json
Labels: Git-Build

#529 fix:修复番外多次跳转后图会变大导致异常
  function/core/FAA_ActionInterfaceJump.py
  resource/image/stage/EX-2_1.png
  resource/image/stage/EX-3_1.png
  resource/image/stage/EX-4_1.png
Labels: Git-Fix

#530 fix(公会任务): 修复限制卡片数量任务(坚果高台-夜) + 自动带卡 激活时会报错卡死的问题
  function/core/FAA.py
Labels: Git-Fix

#531 fix(云端获取StageInfoOnline): 修复直接比较字符串的愚蠢问题.
  function/scattered/get_stage_info_online.py
Labels: Git-Fix

#532 perf(浇水施肥摘果): 游戏可以无限施肥, 故优化逻辑, 最大尝试次数仅5次, 且会自动点击确定满施肥提示.
  function/core/FAA.py
  function/core/Todo.py
Labels: Git-Perf

#534 fix(自动带卡): 名称包含数字的卡片, 无法被正确解析名称, 导致带卡失败的问题已进行修复.
  function/core/FAA_BattlePreparation.py
Labels: Git-Fix, 🗡️Module-Battle

#535 fix(自动带卡): 修复过于相似的卡片无法被区分开(祥龙环初始和一转)的问题.
  function/core/FAA_BattlePreparation.py
Labels: Git-Fix, 🗡️Module-Battle

#536 fix(自动带卡): 自动带卡检索卡片时, 未对波次按int进行排序, 这可能导致的潜在问题. 故进行修复.
  function/core/FAA_BattlePreparation.py
Labels: Git-Fix

#537 perf(刷新游戏): 调整流程 使得4399微端也可以完成刷新后回到桌面的操作.
  function/core/FAA.py
  function/core/Todo.py
Labels: Git-Perf

#538 perf(输出文本): 优化开屏输出和主要流程步骤输出.
  config/stage_plan.json
  function/core/QMW_1_log.py
  function/core/QMW_3_service.py
  function/core/Todo.py
  logs/item_ranking_dag_graph.json
  resource/image/common/登录/0_刷新_被点击.png
  resource/image/common/登录/0_刷新_被选中.png
  resource/ui/FAA_3.0.ui
Labels: 🕹️Module-UI, Git-Perf

#539 fix(战斗流程): 修复一个问题. 该问题导致, 魔塔类事项在开启自动带卡后, 偶数场次的战斗将因无法自动带卡而失败.
  function/core/Todo.py
Labels: Git-Fix

#540 build(自动战斗): 添加喷壶卡的支持.
  resource/image/card/准备房间/可乐汪-0.png
  resource/image/card/准备房间/可乐汪-1.png
  resource/image/card/准备房间/可乐汪-2.png
  resource/image/card/准备房间/海神-0.png
  resource/image/card/准备房间/海神-1.png
  resource/image/card/准备房间/海神-2.png
  resource/image/card/准备房间/海神-3.png
  resource/image/card/准备房间/狮子座精灵-0.png
  resource/image/card/准备房间/狮子座精灵-1.png
  resource/image/card/准备房间/狮子座精灵-2.png
  resource/image/card/准备房间/转转鸡-0.png
  resource/image/card/准备房间/转转鸡-1.png
  resource/image/card/准备房间/转转鸡-2.png
Labels: 🗡️Module-Battle, Git-Build

#542 build(战斗方案): 优化坚果高台夜5卡方案. 更稳定.
  battle_plan/EX-1-6-1P 坚果-夜 5卡.json
  battle_plan/EX-1-6-2P 坚果-夜 5卡.json
Labels: 🗡️Module-Battle, Git-Build

#543 perf(战斗方案编辑器): 添加波次方案自动排序功能.
  battle_plan/EX-2-9-1P 金字塔 SSS.json
  battle_plan/EX-2-9-2P 金字塔 SSS.json
  battle_plan/EX-4-6-1P 音乐节-夜 SSS.json
  battle_plan/EX-4-6-2P 音乐节-夜 SSS.json
  battle_plan/NO-6-10-1P 多拿滋.json
  battle_plan/NO-6-10-2P 多拿滋.json
  battle_plan/NO-6-7-1P 巴旦木-夜 10损 SSS.json
  battle_plan/NO-6-7-2P 巴旦木-夜 10损 SSS.json
  battle_plan/NO-6-8to9 冷萃星环.json
  battle_plan/教程示例-一卡多重优先级.json
  function/core/QMW_EditorOfBattlePlan.py
Labels: Git-Perf

#546 build: 遗漏资源补充
  resource/image/common/登录/0_回退.png
  resource/image/common/登录/0_回退_被点击.png
  resource/image/common/登录/0_回退_被选中.png
  resource/image/common/登录/1_我最近玩过的服务器_4399微端.png
Labels: Git-Build

#548 perf(战斗执行器): 优化自动冰沙, 使其在大量卡片被冻结后也能正常使用.
  function/core/FAA.py
  function/core_battle/Card.py
Labels: 🗡️Module-Battle, Git-Perf

#549 perf(UI): 关卡代号查看, 为列染色, 增加可读性.
  function/core/QMW_TipStageID.py
Labels: 🕹️Module-UI, Git-Perf

#550 perf(奖励领取): 在北京时间周四0-12点之间领取公会任务奖励, 将跳过该步骤.
  battle_plan/3通用-花火追踪-1P.json
  battle_plan/3通用-花火追踪-2P.json
  function/core/FAA_ActionQuestReceiveRewards.py
  logs/item_ranking_dag_graph.json
  resource/image/ocr/关卡名称/国.png
  resource/image/ocr/关卡名称/母.png
  resource/image/ocr/关卡名称/电.png
  resource/image/ocr/关卡名称/绿.png
Labels: Git-Perf

#551 build(战斗方案): 新增公会副本3-死亡之棘 内置方案.
  battle_plan/GD-0-3-1P 花火追踪.json
  battle_plan/GD-0-3-2P 花火追踪.json
  config/stage_plan.json
Labels: 🗡️Module-Battle, Git-Build

#552 build(战斗方案): 更新CS-6-5冰跨12方案. 可以正常通关, 但需要双二转海盐粉.
  battle_plan/CS-6-5-1P.json
  battle_plan/CS-6-5-2P.json
Labels: 🗡️Module-Battle, Git-Build

#553 feat(版本号更新): v2.0.0, 由于该版本添加了大量重要功能, 进行了大量开发, 且趋于稳定, 故更新版本号.
  function/globals/EXTRA.py
Labels: Git-Feat, Relese

#554 build: 例行资源补充
  task_sequence/多拿滋循环.json
Labels: Git-Build

#556 feat(性能分析):完成了仪表盘功能（虽然有点丑）
  function/core/performance_analysis.py
  function/widget/GaugePanel.py
  resource/ui/FAA_3.0.ui
Labels: Git-Feat, 🕹️Module-UI

#557 feat(贡献扫描器): 额外添加功勋扫描器和相关可视化. 移除贡献视图中天月年部分.
  function/core/QMW_3_service.py
  function/scattered/guild_manager.py
Labels: Git-Feat, 🕹️Module-UI

#558 feat(配置迁移器): 新增可选迁移项, 配置文件 - 关卡全局方案
  function/core/QMW_SettingsMigrator.py
Labels: Git-Feat, 🕹️Module-UI

#559 perf(自动带卡): 扫描后选卡时, 降低操作速度, 防止卡顿造成失败.
  function/core/FAA_BattlePreparation.py
Labels: 🗡️Module-Battle, Git-Perf

#560 biuld: 修正多拿滋星云障碍物, 修正勇士本23关承载. 在线关卡信息例行补充.
  config/stage_info.json
  config/stage_info_online.json
  logs/item_ranking_dag_graph.json
Labels: Git-Build

#562 build(自动删除道具): 添加仙人掌刺身/灸烤灯笼鱼/金箔甜筒/雪糕投手技能书的自动删除.
  config/cus_images/背包_道具_需删除的/仙人掌刺身-初级技能书.png
  config/cus_images/背包_道具_需删除的/仙人掌刺身-终极技能书.png
  config/cus_images/背包_道具_需删除的/仙人掌刺身-高级技能书.png
  config/cus_images/背包_道具_需删除的/炙烤灯笼鱼-初级技能书.png
  config/cus_images/背包_道具_需删除的/炙烤灯笼鱼-终极技能书.png
  config/cus_images/背包_道具_需删除的/炙烤灯笼鱼-高级技能书.png
  config/cus_images/背包_道具_需删除的/金箔甜筒-初级技能书.png
  config/cus_images/背包_道具_需删除的/金箔甜筒-终极技能书.png
  config/cus_images/背包_道具_需删除的/金箔甜筒-高级技能书.png
  config/cus_images/背包_道具_需删除的/雪糕投手-初级技能书.png
  config/cus_images/背包_道具_需删除的/雪糕投手-究极技能书.png
  config/cus_images/背包_道具_需删除的/雪糕投手-终极技能书.png
  config/cus_images/背包_道具_需删除的/雪糕投手-高级技能书.png
Labels: Git-Build

#563 refactor(战斗方案编辑器): 完全重构功能实现. 重新抽象化模块化, 规范变量名. 优化界面文本并添加大量提示信息. 缩小整体布局使其在1K屏125%缩放下也能完整显示. 修复意外出现'未选择卡片'报错的Bug.
  function/core/QMW_EditorOfBattlePlan.py
Labels: Git-Fix, Git-Feat, 🕹️Module-UI, Git-Perf, ✏️Module-Editor

#564 feat(战斗方案编辑器): 新增波次编辑器. 以一行按钮标识波次，点击即可切换到对应波次, 被切换的波次数字以>>X<<标识.
  function/core/QMW_EditorOfBattlePlan.py
Labels: Git-Feat, ✏️Module-Editor

#565 feat(战斗方案编辑器): 波次编辑器, 新增复制粘贴波次/ 应用当前波次方案到全部波次.
  function/core/QMW_EditorOfBattlePlan.py
Labels: Git-Feat, ✏️Module-Editor

#566 feat(战斗方案编辑器): 为波次编辑器的波次按钮染色, 从前到后, 每当波次方案发生变化颜色也将变化.
  function/core/QMW_EditorOfBattlePlan.py
Labels: Git-Feat, ✏️Module-Editor

#567 feat(战斗方案编辑器): 重做波次高亮. 关卡障碍高亮(原红色)和正在编辑的卡片放置动作位置高亮(原黄色)不再互斥清除彼此. 先已兼容可同时展示. 采用红(障碍)/紫(障碍上放卡)/蓝(放卡)配色.
  function/core/QMW_EditorOfBattlePlan.py
Labels: Git-Feat, ✏️Module-Editor

#568 perf(战斗方案编辑器): 通过调整棋盘中放卡动作名称显示规则和调整布局规则. 优化其过长时, 棋盘中文本显示超出格子, 并导致布局畸形的缺陷.
  function/core/QMW_EditorOfBattlePlan.py
Labels: Git-Perf, ✏️Module-Editor
