Repository StareAbyss/FoodsVsMiceAutoAssistant, pull requests merged in 2024-10, with the labels that each got.

#321 v1.5.0-beta.4 战斗方案编辑器. 读取A方案, 覆盖保存到B方案时, 修改使用的UUID将为B的, 不再是A的.
  battle_plan/真萌新-煮蛋器忍坤狮子座.json
  function/core/QMW_EditorOfBattlePlan.py
  function/scattered/create_drops_image.py
Labels: 🔼enhancement

#322 v1.5.0-beta.4 优化UI中的Tooltips. 调整高级自定义作战的位置到单本连战之前.
  function/core/QMW_0_load_ui_file.py
  function/core/QMW_1_log.py
  function/core/Todo.py
  resource/ui/FAA_3.0.ui
Labels: 🔼enhancement

#323 v1.5.0-beta.4 修复欢乐假期无法正常进入的问题.
  function/core/FAA_ActionInterfaceJump.py
Labels: 🪲Bug

#325 v1.5.0-beta.4 重大更新! 战斗执行器 - 卡片状态识别 - 自学习模块. 开发完成. 重新整理战斗逻辑, 极大减少重复截图次数, 极大减轻识图负担. 对部分特殊卡背和未来可能的改卡背的卡片, 进行完美适配. 高级战斗模块相应部分可能需要更新以支持. 部分参数目前较为保守, 可能需要进一步调优.
  function/core/Todo.py
  function/core_battle/Card.py
  function/core_battle/CardManager.py
  function/core_battle/CardQueue.py
  resource/picture/card/状态判定/0/不可用.png
  resource/picture/card/状态判定/0/冷却.png
  resource/picture/card/状态判定/0/可用.png
  resource/picture/card/状态判定/1/不可用.png
  resource/picture/card/状态判定/1/冷却.png
  resource/picture/card/状态判定/1/可用.png
  resource/picture/card/状态判定/2/不可用.png
  resource/picture/card/状态判定/2/冷却.png
  resource/picture/card/状态判定/2/可用.png
  resource/picture/card/状态判定/3/不可用.png
  resource/picture/card/状态判定/3/冷却.png
  resource/picture/card/状态判定/3/可用.png
  resource/picture/card/状态判定/4/不可用.png
  resource/picture/card/状态判定/4/冷却.png
  resource/picture/card/状态判定/4/可用.png
  resource/picture/card/状态判定/5/不可用.png
  resource/picture/card/状态判定/5/冷却.png
  resource/picture/card/状态判定/5/可用.png
  resource/picture/card/状态判定/冷却状态_0.png
  resource/picture/card/状态判定/冷却状态_1.png
  resource/picture/card/状态判定/冷却状态_2.png
  resource/picture/card/状态判定/冷却状态_3.png
  resource/picture/card/状态判定/可用状态_0.png
  resource/picture/card/状态判定/可用状态_1.png
  resource/picture/card/状态判定/可用状态_2.png
  resource/picture/card/状态判定/可用状态_3.png
  resource/picture/card/状态判定/可用状态_4.png
  test/capture_card_state_image/__init__.py
  test/capture_card_state_image/main.py
  test/test.py
Labels: 🔼enhancement

#326 v1.5.0-beta.4 去除 任务事项耗时通报 的时间小数点.
  function/core/Todo.py
Labels: 🪲Bug

#329 v1.5.4 自定义任务事项. 添加双暴卡功能. 并添加部分待实现功能代码.
  function/core/QMW_EditorOfTaskSequence.py
Labels: 🔼enhancement

#330 v1.5.4 调整所有战斗的卡组选择UI, 从数值输入框改为下拉选择框.
  function/core/FAA.py
  function/core/FAA_ActionInterfaceJump.py
  function/core/QMW_2_load_settings.py
  function/core/Todo.py
  function/core_battle/CardManager.py
  function/core_battle/FAA_Battle.py
  function/globals/g_extra.py
  logs/item_ranking_dag_graph.json
  resource/ui/FAA_3.0.ui
  test/test.py
  打包 & 部署.md
  打包 - 资源文件.py
Labels: 🔼enhancement

#331 v1.5.4 修复自动爬塔功能. 该bug原因是: OCR识别关卡游戏内名称 - 应用关卡信息时, 修改了关卡的id.
  function/core/FAA_ActionInterfaceJump.py
  function/core/FAA_BattleARoundPreparation.py
  function/scattered/read_json_to_stage_info.py
Labels: 🪲Bug

#332 v1.5.4 将使用武器技能和自动拾取的点击操作, 加入FAA-Battle Lock, 以解决其干扰正常放卡流程的问题. 并调优放卡流程的时延参数.
  function/core_battle/Card.py
  function/core_battle/CardQueue.py
  function/core_battle/FAA_Battle.py
  logs/item_ranking_dag_graph.json
Labels: 🪲Bug, 🔼enhancement

#333 v1.5.4 为所有打开背包的操作增加10s延时. 不仅是删除物品. 以防止加载较慢的情况下关键操作卡死.
  function/core/FAA.py
Labels: 🪲Bug

#336 补充汉堡王星进入方式.
  resource/picture/stage/NO-6-5.png
Labels: 📦Resource

#337 战斗方案编辑器. 添加按钮和独立的教学界面. 取代原有的简单描述.
  function/core/QMW_3_service.py
  function/core/QMW_EditorOfBattlePlan.py
  function/core/QMW_TipEditorOfBattlePlan.py
Labels: 🔼enhancement

#340 战斗方案编辑器. 在未选择卡片时, 卡片id 名称 队列 遍历 坤参数 删除卡片的UI, 设定它们为不可用.
  function/core/QMW_EditorOfBattlePlan.py
Labels: 🔼enhancement

#341 战斗方案编辑器. 调整卡片列表的对齐逻辑, 不再使用制表符, 而是使用中西文字数统计和添加全半宽空格. 视觉表现更好.
  function/core/QMW_EditorOfBattlePlan.py
Labels: 🔼enhancement

#342 OCR关卡名修改关卡信息. 修正该功能的一项错误, 导致爬塔功能总是开启的Bug.
  function/core/FAA_BattleARoundPreparation.py
Labels: 🪲Bug

#345 战斗执行器 - 状态识别. 重新使用容差匹配, 而非完全相等来匹配状态, 提高抗干扰能力, 增加健壮性.
  function/core_battle/Card.py
Labels: 🔼enhancement

#346 fix(战斗执行器-状态识别): 修复点击队列混乱的问题
  function/core_battle/Card.py
Labels: Issue-Bug🪲

#348 fix: 战斗执行器. 修复坤卡不放置的问题.
  function/core_battle/Card.py
Labels: Issue-Bug🪲, Module-Battle

#349 perf: 战斗执行器. 使用更激进参数, 提高放卡速度.
  function/core_battle/Card.py
  function/core_battle/FAA_Battle.py
  function/globals/thread_action_queue.py
Labels: Module-Battle

#355 fix: ui和opt数据交互. 修复改名方案, 不退出faa而直接点击保存, 会导致当前选中的Todo方案的战斗方案错位的问题.
  function/core/QMW_2_load_settings.py
Labels: Issue-Bug🪲

#357 fix: OCR. 修复识别失败图像保存时, 越来越卡顿的问题.
  function/scattered/match_ocr_text/match_text.py
Labels: Issue-Bug🪲

#359 feat: 新增配置迁移器.
  function/core/QMW_3_service.py
  function/core/QMW_SettingsMigrator.py
  resource/ui/FAA_3.0.ui
Labels: Issue-Enhancement🔼

#362 feat: 允许用户在UI中自定义软件点击频率. 此外调整了高级设置中, 多项配置项的分类.
  config/settings_template.json
  function/core/QMW_2_load_settings.py
  function/core_battle/FAA_Battle.py
  function/globals/g_extra.py
  function/globals/thread_action_queue.py
  resource/ui/FAA_3.0.ui
Labels: Issue-Enhancement🔼

#364 fix: 修复米苏物流使用默认url时上传失败的问题.
  function/scattered/loots_and_chest_data_save_and_post.py
Labels: Issue-Bug🪲

#365 perf: 关卡信息. 沙漠飞碟鼠关卡, 新增防火承载.
  config/stage_info.json
Labels: Issue-Enhancement🔼

#366 build: 支持星级穿越二期地图的关卡跳转和关卡信息.
  config/stage_info.json
  resource/picture/stage/NO-6-10.png
  resource/picture/stage/NO-6-5.png
  resource/picture/stage/NO-6-6.png
  resource/picture/stage/NO-6-7.png
  resource/picture/stage/NO-6-8.png
  resource/picture/stage/NO-6-9.png
Labels: Resource📦

#367 feat: 日氪. 适配新版日氪UI.
  function/core/FAA.py
  resource/picture/top_up_money/充值界面_退出.png
  resource/picture/top_up_money/每日必充_判定点.png
Labels: Issue-Enhancement🔼

#368 refactor: 战斗执行器 - 高级战斗. 大幅重构, 重整逻辑, 修复可用性, 重整代码逻辑, 优化可读性.
  function/core/QMW_3_service.py
  function/core/Todo.py
  function/core_battle/Card.py
  function/core_battle/CardManager.py
  function/core_battle/CardQueue.py
  function/core_battle/FAA_Battle.py
  function/scattered/get_list_battle_plan.py
  resource/picture/card/特殊对策卡/其他不是炸弹的特殊卡/冰激凌_15.png
  resource/picture/card/特殊对策卡/其他不是炸弹的特殊卡/咖啡粉_17.png
  resource/picture/card/特殊对策卡/其他不是炸弹的特殊卡/极寒冰沙_15.png
  resource/picture/card/特殊对策卡/其他不是炸弹的特殊卡/果蔬冰淇淋_15.png
Labels: Issue-Bug🪲, Issue-Enhancement🔼, Module-Battle

#369 feat: 战利品识别. 新增支持: 星际穿越二期 - 钥匙徽章配方材料 / 食神谱 / 礼卷 / 漫游奇境 - 遗漏的部分配方和材料
  resource/picture/item/战利品/冰块冷萃机-初级技能书.png
  resource/picture/item/战利品/冰块冷萃机-终极技能书.png
  resource/picture/item/战利品/冰块冷萃机-高级技能书.png
  resource/picture/item/战利品/冰块冷萃机配方.png
  resource/picture/item/战利品/冰镇西瓜.png
  resource/picture/item/战利品/冷萃装置.png
  resource/picture/item/战利品/南翔小笼包.png
  resource/picture/item/战利品/外星water.png
  resource/picture/item/战利品/多拿滋.png
  resource/picture/item/战利品/小喷嘴.png
  resource/picture/item/战利品/彩色糖霜.png
  resource/picture/item/战利品/怪味鱿鱼配方.png
  resource/picture/item/战利品/扑克护罩配方.png
  resource/picture/item/战利品/扑克蛋糕杯.png
  resource/picture/item/战利品/星云徽章A.png
  resource/picture/item/战利品/星云徽章B.png
  resource/picture/item/战利品/梦幻多拿滋-初级技能书.png
  resource/picture/item/战利品/梦幻多拿滋-终极技能书.png
  resource/picture/item/战利品/梦幻多拿滋-高级技能书.png
  resource/picture/item/战利品/梦幻多拿滋配方.png
  resource/picture/item/战利品/甜点包装盒.png
  resource/picture/item/战利品/礼卷.png
  resource/picture/item/战利品/蓝山咖啡豆.png
  resource/picture/item/战利品/蚝油.png
  resource/picture/item/战利品/鱿鱼仔.png
  resource/picture/item/战利品/麻辣烫.png
Labels: Resource📦

#370 build: 战利品识别. 支持大量终极技能书, 以应对未来可能的战利品增加.
  resource/picture/item/战利品/三向冰冻小笼包-终极技能书.png
  resource/picture/item/战利品/三向国王小笼包-终极技能书.png
  resource/picture/item/战利品/三向小笼包-终极技能书.png
  resource/picture/item/战利品/三线酒架-终极技能书.png
  resource/picture/item/战利品/关东煮喷锅-终极技能书.png
  resource/picture/item/战利品/冰冻小笼包-终极技能书.png
  resource/picture/item/战利品/冰煮蛋器投手-终极技能书.png
  resource/picture/item/战利品/双向水管-终极技能书.png
  resource/picture/item/战利品/双层冰冻小笼包-终极技能书.png
  resource/picture/item/战利品/双层小笼包-终极技能书.png
  resource/picture/item/战利品/咖啡壶-终极技能书.png
  resource/picture/item/战利品/咖啡杯-终极技能书.png
  resource/picture/item/战利品/国王小笼包-终极技能书.png
  resource/picture/item/战利品/土司面包-终极技能书.png
  resource/picture/item/战利品/大火炉-终极技能书.png
  resource/picture/item/战利品/小火炉-终极技能书.png
  resource/picture/item/战利品/小笼包-终极技能书.png
  resource/picture/item/战利品/巧克力投手-终极技能书.png
  resource/picture/item/战利品/巧克力面包-终极技能书.png
  resource/picture/item/战利品/旋转咖啡喷壶-终极技能书.png
  resource/picture/item/战利品/木盘子-终极技能书.png
  resource/picture/item/战利品/机枪冰冻小笼包-终极技能书.png
  resource/picture/item/战利品/机枪小笼包-终极技能书.png
  resource/picture/item/战利品/棉花糖-终极技能书.png
  resource/picture/item/战利品/水上茶杯-终极技能书.png
  resource/picture/item/战利品/热狗大炮-终极技能书.png
  resource/picture/item/战利品/煮蛋器投手-终极技能书.png
  resource/picture/item/战利品/章鱼烧-终极技能书.png
  resource/picture/item/战利品/糖葫芦炮弹-终极技能书.png
  resource/picture/item/战利品/臭豆腐投手-终极技能书.png
  resource/picture/item/战利品/色拉投手-终极技能书.png
  resource/picture/item/战利品/菠萝爆炸面包-终极技能书.png
  resource/picture/item/战利品/酒杯灯-终极技能书.png
  resource/picture/item/战利品/钢鱼刺-终极技能书.png
  resource/picture/item/战利品/钢鱼刺-高级技能书.png
  resource/picture/item/战利品/雷电长棍面包-终极技能书.png
  resource/picture/item/战利品/香肠-终极技能书.png
  resource/picture/item/战利品/鱼刺-终极技能书.png
Labels: Resource📦

#371 build: 战利品识别. 修复 番茄色拉投手 -> 色拉投手. 修复 旋转咖啡壶 -> 旋转咖啡喷壶. 移除 饭团.
  resource/picture/item/战利品/旋转咖啡壶-高级技能书.png
  resource/picture/item/战利品/色拉投手-初级技能书.png
  resource/picture/item/战利品/色拉投手-高级技能书.png
  resource/picture/item/战利品/色拉投手配方.png
  resource/picture/item/战利品/饭团.png
Labels: Issue-Bug🪲, Resource📦

#372 build: 关卡名称OCR. 34项资源补充.
  resource/picture/ocr/关卡名称/冰.png
  resource/picture/ocr/关卡名称/冷.png
  resource/picture/ocr/关卡名称/口.png
  resource/picture/ocr/关卡名称/台.png
  resource/picture/ocr/关卡名称/号.png
  resource/picture/ocr/关卡名称/啤.png
  resource/picture/ocr/关卡名称/回.png
  resource/picture/ocr/关卡名称/坚.png
  resource/picture/ocr/关卡名称/城.png
  resource/picture/ocr/关卡名称/壁.png
  resource/picture/ocr/关卡名称/士.png
  resource/picture/ocr/关卡名称/大.png
  resource/picture/ocr/关卡名称/巴.png
  resource/picture/ocr/关卡名称/廊.png
  resource/picture/ocr/关卡名称/戈.png
  resource/picture/ocr/关卡名称/拆.png
  resource/picture/ocr/关卡名称/旦.png
  resource/picture/ocr/关卡名称/星.png
  resource/picture/ocr/关卡名称/木.png
  resource/picture/ocr/关卡名称/沙.png
  resource/picture/ocr/关卡名称/港.png
  resource/picture/ocr/关卡名称/漠.png
  resource/picture/ocr/关卡名称/环.png
  resource/picture/ocr/关卡名称/芝.png
  resource/picture/ocr/关卡名称/萃.png
  resource/picture/ocr/关卡名称/营.png
  resource/picture/ocr/关卡名称/蜥.png
  resource/picture/ocr/关卡名称/蜴.png
  resource/picture/ocr/关卡名称/迁.png
  resource/picture/ocr/关卡名称/队.png
  resource/picture/ocr/关卡名称/风.png
  resource/picture/ocr/关卡名称/骨.png
  resource/picture/ocr/关卡名称/高.png
  resource/picture/ocr/关卡名称/鱼.png
Labels: Resource📦

#373 fix: 战利品识别 - 图优化配置. 修复部分物品名称.
  logs/item_ranking_dag_graph.json
Labels: Issue-Bug🪲, Resource📦

#375 feat: 新增用户设置项 - 游戏最低帧数. 并更新相关鼠标提示信息.
  config/settings_template.json
  function/core/QMW_2_load_settings.py
  function/core_battle/Card.py
  function/core_battle/CardManager.py
  function/core_battle/CardQueue.py
  function/globals/g_extra.py
  resource/ui/FAA_3.0.ui
Labels: Issue-Enhancement🔼

#376 feat: 战斗方案. 翻新雷城雪山方案. 更新巴旦木多拿滋方案. 沙漠方案下移.
  battle_plan/!!!  本文件夹用于储存战斗方案, 会被faa读取, 下方的not_active里面还有更多方案, 有需要请拖到此处, 再在FAA点击保存配置或重启FAA以读取方案  !!!
  battle_plan/1卡组-NO-4-5.json
  battle_plan/1卡组-通用-花火-1P-测试版.json
  battle_plan/1卡组-通用-花火-2P.json
  battle_plan/雪山卡组-EX-3-N(通解)-1P.json
  battle_plan/雪山卡组-EX-3-N(通解)-2P.json
  battle_plan/雷城卡组-EX-4-1至4-1P.json
  battle_plan/雷城卡组-EX-4-1至4-2P.json
  battle_plan/雷城卡组-EX-4-5-1P.json
  battle_plan/雷城卡组-EX-4-5-2P.json
  battle_plan/雷城卡组-EX-4-6-1P.json
  battle_plan/雷城卡组-EX-4-6-2P.json
  battle_plan/非标卡组-EX-1-6.json
  battle_plan/非标卡组-NO-6-4.json
  battle_plan/非标卡组-NO-6-6至7.json
  battle_plan_not_active/!!!  本文件夹用于储存部分暂时无用的战斗方案, 不会被FAA读取, 有需要请拖到battle_plan中, 再在FAA点击保存配置或重启FAA以读取方案  !!!
  battle_plan_not_active/_本文件夹用于储存部分暂时无用的战斗方案, 不会被faa读取, 有需要请拖到battle_plan中, 再点击保存配置以重新读取方案.txt
  battle_plan_not_active/沙漠卡组-EX-2-6-1P.json
  battle_plan_not_active/沙漠卡组-EX-2-6-2P.json
  battle_plan_not_active/沙漠卡组-EX-2-7-2P.json
  battle_plan_not_active/沙漠卡组-EX-2-8-2P.json
  battle_plan_not_active/沙漠卡组-EX-2-9-1P.json
  battle_plan_not_active/沙漠卡组-EX-2-9-2P.json
Labels: Resource📦, Module-Battle

#377 perf: 综合优化. 优化日氪功能输出文本以便除错. 优化多项鼠标提示信息.
  README - 高级放卡.md
  function/core/FAA.py
  logs/item_ranking_dag_graph.json
  resource/ui/FAA_3.0.ui
  打包 - 资源文件.py
Labels: Issue-Enhancement🔼

#378 docs: 更新致谢名单! 感谢你们!
  致谢名单.png
Labels: Documentation

#381 biuld: Create release.yml
  .github/release.yml
Labels: Git-Biuld

#380 fix(cardmanager): 修复了高级战斗炸弹只能用一次的bug。
  function/core_battle/CardManager.py
Labels: Git-Fix

#387 perf: 战斗执行器. 仅承载卡包含木盘子时, 其放卡策略为遍历, 其他情况为不再遍历.
  function/core/FAA.py
Labels: Git-Perf

#388 perf: 战斗执行器. 自动冰沙卡片放置格不再固定为"1-1", 而是根据关卡信息自动选取非障碍位置.
  function/core/FAA.py
Labels: Module-Battle, Git-Perf

#389 feat: 战利品识别. 新增校验规则, 如果某个物品的出现位置不连续, 视为识别错误, 不参与无环图校验&记录&米苏物流提交. 并输出有多少次识别为正确.
  function/core/FAA_BattleARoundPreparation.py
  function/core/Todo.py
  function/core/analyzer_of_loot_logs.py
Labels: Git-Feat, Module-Battle

#390 feat: FAA版本号保存为全局变量, 并上传给米苏物流.
  function/core/QMW_0_load_ui_file.py
  function/globals/g_extra.py
  function/scattered/loots_and_chest_data_save_and_post.py
Labels: Git-Feat

#392 feat: 领取任务奖励, 添加领取营地任务奖励功能模块.
  function/core/FAA.py
  function/core/FAA_ActionQuestReceiveRewards.py
Labels: Git-Feat

#393 perf: 战斗方案编辑器. 另存为方案后, 正在编辑的文件, 变更为保存后的文件.
  function/core/QMW_EditorOfBattlePlan.py
Labels: Git-Perf

#395 feat: 自定义任务序列. 支持自定义领取任务奖励功能.
  function/core/QMW_EditorOfTaskSequence.py
  function/core/Todo.py
  resource/ui/FAA_3.0.ui
Labels: Git-Feat

#396 perf: 战斗执行器. 优化战斗方案读取, 提高可读性和健壮性.
  function/core/FAA.py
  function/core_battle/Card.py
  function/core_battle/CardManager.py
Labels: Git-Perf

#397 feat: 战斗执行器. 支持多种复制类卡片(幻坤)的自动化使用.
  function/core/FAA.py
  function/core_battle/Card.py
  function/core_battle/CardManager.py
Labels: Git-Feat

#398 perf: 战斗执行器. 卡片缩短放满自ban时间10->7s. 每次放卡后无论状态, 卡片自Ban2s.
  function/core_battle/Card.py
  function/core_battle/CardManager.py
  function/tools/calculation_best_cell_without_obstacle.py
  function/tools/get_all_obstacle.py
Labels: Git-Perf

#399 build: 卡牌图片资源例行更新, 以支持战斗执行器-多种复制卡.
  resource/picture/card/战斗/创造神-0.png
  resource/picture/card/战斗/创造神-1.png
  resource/picture/card/战斗/创造神-2.png
  resource/picture/card/战斗/创造神-3.png
  resource/picture/card/战斗/创造神-4.png
  resource/picture/card/战斗/创造神-5.png
Labels: Module-Battle, Git-Build

#400 fix: 战利品识别. 修复图片版日志生成, 因数据源格式错误造成的卡死.
  function/core/Todo.py
Labels: Git-Fix, Module-Drop

#401 fix: 任务列表. 修复仅启动自定义任务序列时. 额外事项和自建房事项的日志输出和游戏刷新仍激活的Bug.
  function/core/Todo.py
Labels: Git-Fix

#402 build: 内置战斗方案进行修缮.
  battle_plan/2卡组-速刷-生煎电棍花火-1P.json
  battle_plan/2卡组-速刷-生煎电棍花火-2P.json
  battle_plan/非标卡组-NO-6-8至9.json
  battle_plan/非标卡组-萌新-冷萃莓果.json
  battle_plan/非标卡组-萌新-煮蛋忍坤.json
  battle_plan/非标卡组-通用-追踪电棍花火.json
Labels: Module-Battle, Git-Build

#403 build: OCR资源更新. 战利品识别DAG优化资源更新. 关卡信息维护. 增加内置自定义任务序列.
  config/stage_info.json
  logs/item_ranking_dag_graph.json
  resource/picture/ocr/关卡名称/乐.png
  resource/picture/ocr/关卡名称/会.png
  resource/picture/ocr/关卡名称/前.png
  resource/picture/ocr/关卡名称/动.png
  resource/picture/ocr/关卡名称/区.png
  resource/picture/ocr/关卡名称/叶.png
  resource/picture/ocr/关卡名称/孜.png
  resource/picture/ocr/关卡名称/宝.png
  resource/picture/ocr/关卡名称/巨.png
  resource/picture/ocr/关卡名称/庄.png
  resource/picture/ocr/关卡名称/感.png
  resource/picture/ocr/关卡名称/戚.png
  resource/picture/ocr/关卡名称/抹.png
  resource/picture/ocr/关卡名称/断.png
  resource/picture/ocr/关卡名称/枪.png
  resource/picture/ocr/关卡名称/桥.png
  resource/picture/ocr/关卡名称/棒.png
  resource/picture/ocr/关卡名称/椒.png
  resource/picture/ocr/关卡名称/楼.png
  resource/picture/ocr/关卡名称/浓.png
  resource/picture/ocr/关卡名称/浮.png
  resource/picture/ocr/关卡名称/然.png
  resource/picture/ocr/关卡名称/爱.png
  resource/picture/ocr/关卡名称/经.png
  resource/picture/ocr/关卡名称/节.png
  resource/picture/ocr/关卡名称/芭.png
  resource/picture/ocr/关卡名称/茶.png
  resource/picture/ocr/关卡名称/莎.png
  resource/picture/ocr/关卡名称/莓.png
  resource/picture/ocr/关卡名称/藏.png
  resource/picture/ocr/关卡名称/街.png
  resource/picture/ocr/关卡名称/钟.png
  resource/picture/ocr/关卡名称/阁.png
  resource/picture/ocr/关卡名称/集.png
  resource/picture/ocr/关卡名称/雾.png
  resource/picture/ocr/关卡名称/音.png
  resource/picture/ocr/美食大赛/威.png
  resource/picture/ocr/美食大赛/望.png
  task_sequence/测试.json
  task_sequence/营地通刷.json
Labels: Git-Build

#406 perf: 日氪. 修复 充值界面-复核-已选中氪金值输入框 步骤 错误的问题.
  function/core/FAA.py
Labels: Git-Fix

#407 build: 自动大赛. 增加可适配的替换卡列表.
  function/core/QMW_TipBattle.py
  function/core/Todo.py
  function/core_battle/Card.py
  resource/image/card/准备房间/樱桃反弹布丁-10.png
  resource/image/card/准备房间/樱桃反弹布丁-11.png
  resource/image/card/准备房间/樱桃反弹布丁-9.png
  resource/image/card/准备房间/狮子座精灵-10.png
  resource/image/card/准备房间/狮子座精灵-11.png
  resource/image/card/准备房间/狮子座精灵-12.png
  resource/image/card/准备房间/狮子座精灵-13.png
  resource/image/card/准备房间/狮子座精灵-14.png
  resource/image/card/准备房间/狮子座精灵-15.png
  resource/image/card/准备房间/狮子座精灵-16.png
  resource/image/card/准备房间/狮子座精灵-17.png
  resource/image/card/准备房间/狮子座精灵-18.png
  resource/image/card/准备房间/狮子座精灵-9.png
  resource/image/card/准备房间/糖葫芦炮弹-12.png
Labels: Git-Build

#408 build: 战利品识别, 图优化图表更新.
  logs/item_ranking_dag_graph.json
Labels: Git-Build, Module-Drop

#410 fix: 关卡信息. 珊瑚洋流-夜铲卡错误修正.
  config/stage_info.json
Labels: Git-Fix, Module-Battle

#411 biuld: 关卡信息-额外. 2024/10/24例行更新. 感谢: TY丶雨
  config/stage_info_extra.json
Labels: Module-Battle, Git-Build

#415 fix: 界面跳转. 进入悬赏关卡时切区延时增加. 解决服务器较卡时进不去游戏的问题.
  function/core/FAA_ActionInterfaceJump.py
Labels: Git-Fix

#416 fix: 日氪. 修复在部分电脑上无法正常完成流程的Bug.
  function/core/FAA.py
  function/core/Todo.py
Labels: Git-Fix

#418 fix: 任务序列编辑器. 修复删除按钮绑定的上级元素错位问题.
  function/core/QMW_EditorOfTaskSequence.py
Labels: Git-Fix

#419 fix: 自定义任务序列. 修复领取奖励执行问题.
  function/core/Todo.py
Labels: Git-Fix

#421 refactor: 优化每日必充功能的匹配参数和流程
  function/common/bg_img_match.py
  function/core/FAA.py
  resource/image/top_up_money/充值界面_游币兑换_已选中.png
  resource/image/top_up_money/充值界面_请输入_已输入.png
  resource/image/top_up_money/充值界面_请输入_已选中.png
Labels: Git-Perf
