Repository StareAbyss/FoodsVsMiceAutoAssistant, pull requests merged in 2024-08, with the labels that each got.

#218 v1.4.1-beta.1 萌宠神殿. 修复了双人多线程情况下完成后不退出的问题.
  function/core/FAA.py
  function/core/Todo.py
  logs/item_ranking_dag_graph.json
Labels: bug

#219 v1.4.1-beta.1 修复了全局变量引用为拷贝, 导致战斗方案不启动软件无法应用更新, 增加战斗日志中识别失败的图像资源的全局引用.
  function/common/bg_img_match.py
  function/core/FAA.py
  function/core_battle/CardManager.py
  function/core_battle/CardQueue.py
  function/deprecated/old_battle_loop.py
  function/globals/init_resources.py
Labels: bug

#220 v1.4.1-beta.1 全局路径. 重写, 增加部分潜在空路径的检查创建.
  function/globals/get_paths.py
Labels: enhancement

#221 v1.4.1-beta.1 战利品识别失败后, 不再以随机id进行堆放, 而是改到logs文件夹的match/failed, 命名为 unknown_id_count. 以统计某些图片未被识别的频次. 并将美食大赛识别失败的资源统计中相同的模块归并.
  function/common/bg_img_match.py
  function/common/same_size_match.py
  function/core/FAA.py
  function/core/FAA_BattleARoundPreparation.py
  function/core/QMW_1_load_settings.py
  function/core/analyzer_of_loot_logs.py
  function/scattered/match_ocr_text/match_text.py
  logs/item_ranking_dag_graph.json
  logs/loots_picture/本文件用于在pull代码后可以不缺失目录结构.txt
  logs/match_failed/_此文件夹用于存放识图失败的例图.txt
  logs/result_json/本文件用于在pull代码后可以不缺失目录结构.txt
  resource/picture/ocr/texts_unmatched/1-占位避免报错.png
Labels: enhancement

#222 v1.4.1-beta.1 战利品识别. 优化识别逻辑, 规范化代码, 补充相关备注, 提供额外的识别精准度输出, 增加相关全局测试输出调控.
  function/common/same_size_match.py
  function/core/analyzer_of_loot_logs.py
  function/globals/extra.py
  test/match_loots/__init__.py
  test/match_loots/match_items_in_blocks.py
  test/match_png/test_match_what this block is.py
Labels: enhancement

#223 v1.4.1-beta.1 修正有时无法正常退出关闭日氪界面的的问题, 并限定仅有假期票的日氪会自动进行.
  function/core/FAA.py
  resource/picture/top_up_money/每日必充_判定点.png
Labels: bug, enhancement

#226 v1.4.1-beta.1 修复自动识别大赛中, 保存识别失败图片功能的bug.
  function/common/same_size_match.py
  function/globals/get_paths.py
  function/scattered/match_ocr_text/match_text.py
Labels: bug

#230 v1.4.1-beta.1 自动大赛ocr - 保存识别失败图片. 将不再保存内容相同的图片.
  function/globals/init_resources.py
  function/scattered/match_ocr_text/match_text.py
  resource/picture/ocr/texts_matched/剿.png
  resource/picture/ocr/texts_matched/变.png
  resource/picture/ocr/texts_matched/异.png
  resource/picture/ocr/texts_matched/征.png
  resource/picture/ocr/texts_matched/服.png
  resource/picture/ocr/texts_matched/炼.png
  resource/picture/ocr/texts_matched/相.png
  resource/picture/ocr/texts_matched/色.png
  resource/picture/ocr/texts_matched/觉.png
  resource/picture/ocr/texts_matched/跨.png
  resource/picture/ocr/texts_matched/远.png
  resource/picture/ocr/texts_matched/遇.png
Labels: 🔼enhancement, 📦Resource

#231 删除不规范的git内容 ( .idea文件 )
  .idea/.gitignore
  .idea/FAA_FoodsVsMouses_AutoAssistant.iml
  .idea/FoodsVsMouses_AutoAssistant.iml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.sync-conflict-20231204-070617-HI67XVI.xml
  .idea/workspace.sync-conflict-20231204-071441-HQ2EI7Z.xml
Labels: 🪲Bug

#235 v1.5.0-beta.1 兼容自动炸弹时, 无location_to的卡片不被移除, 导致战斗线程崩溃的bug完成修复
  function/core_battle/Card.py
Labels: 🪲Bug

#238 v1.5.0-beta.1 修订了高级放卡文本，并添加了高级放卡相关前端功能
  config/settings_template.json
  function/core/QMW_1_load_settings.py
  function/core/Todo.py
  function/core_battle/CardManager.py
  resource/ui/FAA_3.0.ui
  高级放卡.md
Labels: 📘doc, 🔼enhancement

#243 v1.5.0-beta.1 重新排版ui, 修正git工作流问题导致的部分文件错乱.
  customize_todo/todo_example.json
  function/core/QMW_0_load_ui_file.py
  resource/ui/FAA_3.0.ui
  task_sequence/be_transformed.xlsx
  task_sequence/todo_example.json
Labels: 🪲Bug, 🔼enhancement

#244 v1.5.0-beta.1 暂时修复并锁定日氪功能
  function/common/bg_img_match.py
  function/core/FAA.py
  logs/item_ranking_dag_graph.json
  test/match_png/source.png
  test/match_png/target.png
  test/match_png/target_2.png
  test/match_png/test_match_image.py
Labels: 🪲Bug

#245 v1.5.0-beta.1 重要更新! 基础解释器升级: Python 3.7.9 -> 3.12.5. PyQt 升级: PyQt 5 -> 6. 完成了相应的函数适配更新.
  README.md
  function/core/FAA_extra_readimage.py
  function/core/QMW_0_load_ui_file.py
  function/core/QMW_1_load_settings.py
  function/core/QMW_2_log.py
  function/core/QMW_3_service.py
  function/core/QMW_EditorOfBattlePlan.py
  function/core/QMW_EditorOfTaskSequence.py
  function/core/QMW_Other.py
  function/core/QMW_TipBattle.py
  function/core/QMW_TipStageID.py
  function/core/QMW_TipWarmGift.py
  function/core/Todo.py
  function/core_battle/CardManager.py
  function/globals/thread_action_queue.py
  function/performance_testing.prof
  logs/item_ranking_dag_graph.json
  requirements.txt
  resource/ui/draglabel.py
  test/test_QListWidgetDraggable.py
  test/test_action_queue_timer.py
  test/test_game_windows.py
Labels: 🔼enhancement

#246 v1.5.0-beta.1 适配暗色主题UI. 包含多级文本上色 & 部分特殊控件样式. 去除冗余版本号控件.
  function/core/QMW_0_load_ui_file.py
  function/core/QMW_2_log.py
  resource/ui/FAA_3.0.ui
Labels: 🔼enhancement

#247 v1.5.0-beta.1 在PyQt6的新默认样式下, 部分控件拥挤/显示不全的问题已修复.
  function/core/QMW_1_load_settings.py
  function/core/QMW_EditorOfBattlePlan.py
  function/core/QMW_EditorOfTaskSequence.py
Labels: 🪲Bug

#248 v1.5.0-beta.1 战斗方案编辑器. 修复card_id可以为0或超过21的问题.
  function/core/QMW_EditorOfBattlePlan.py
Labels: 🪲Bug

#249 v1.5.0-beta.1 Logger. 新增错误日志处理器, 将出现Error级的错误额外保存到一份log文件中.
  function/globals/log.py
  resource/ui/FAA_3.0.ui
Labels: 🔼enhancement

#250 v1.5.0-beta.1 批量二级高级功能, 批量刷新游戏功能. 添加player参数并严谨实现逻辑.
  function/core/Todo.py
  logs/item_ranking_dag_graph.json
  task_sequence/example.json
  task_sequence/from_transformer.json
  task_sequence/自定义作战序列 - 用前必读!.txt
Labels: 🔼enhancement

#251 v1.5.0-beta.1 完成事项序列功能在新协议下的实现(原高级自定义). 调整 自定义事项序列 自建房作战在ui的位置到最底部, 并略微调整Todo.run整体逻辑更模块化.
  function/core/Todo.py
  resource/ui/FAA_3.0.ui
Labels: 🔼enhancement

#252 更新自动资源打包小工具.
  a_tips.md
  function/core/Todo.py
  资源文件打包.py
Labels: 🔼enhancement

#254 v1.5.0-beta.2 文件读写改用线程锁而非自旋锁, 以处理潜在多线程问题.
  README.md
  function/common/bg_img_match.py
  function/common/same_size_match.py
  function/core/FAA.py
  function/core/FAA_ActionInterfaceJump.py
  function/core/FAA_ActionQuestReceiveRewards.py
  function/core/FAA_Battle.py
  function/core/FAA_BattleARoundPreparation.py
  function/core/QMW_1_load_settings.py
  function/core/QMW_EditorOfBattlePlan.py
  function/core/QMW_EditorOfTaskSequence.py
  function/core/QMW_Other.py
  function/core/Todo.py
  function/core/analyzer_of_loot_logs.py
  function/core_battle/Card.py
  function/core_battle/CardManager.py
  function/core_battle/CardQueue.py
  function/core_battle/get_position_in_battle.py
  function/globals/g_extra.py
  function/globals/g_resources.py
  function/scattered/check_uuid_in_battle_plan.py
  function/scattered/create_drops_image.py
  function/scattered/loots_and_chest_data_save_and_post.py
  function/scattered/match_ocr_text/loop_match_ocr.py
  function/scattered/match_ocr_text/match_text.py
  function/scattered/read_json_to_stage_info.py
  logs/item_ranking_dag_graph.json
  task_sequence/transformer_of_todo_json_from_excel.py
  test/match_png/test_match_image.py
  打包_资源文件.py
  打包_部署.md
Labels: 🪲Bug, 🔼enhancement

#255 v1.5.0-beta.2 文字识别&战利品识别. 识别失败, 保留图片时, 应用最小未使用id, 而不再使用非文件数做id, 以处理撞文件名导致的闪退问题.
  function/core/analyzer_of_loot_logs.py
  function/scattered/match_ocr_text/match_text.py
Labels: 🪲Bug

#253 修复了若干bug
  function/core/FAA_extra_readimage.py
  function/core_battle/Card.py
  function/core_battle/CardManager.py
  function/yolo/onnxdetect.py
  resource/ui/FAA_3.0.ui
Labels: 🪲Bug

#256 v1.5.0-beta.2 用户自截图增. 增加模板文件. 原图从git移除并注册.gitignore.
  .gitignore
  config/cus_images/用户自截/空间服登录界面_1P_template.png
  config/cus_images/用户自截/空间服登录界面_2P_template.png
  config/cus_images/用户自截/跨服远征_1p_template.png
  function/core/QMW_1_load_settings.py
Labels: 🔼enhancement

#257 v1.5.0-beta.2 修复RESOURCE中用户自定义部分以静态导入的问题.
  config/cus_images/一些常用的图标/浮空岛酬劳.png
  config/cus_images/一些常用的图标/火山岛酬劳.png
  config/cus_images/一些常用的图标/美味岛酬劳.png
  config/cus_images/背包_装备_需使用的/浮空岛酬劳.png
  config/cus_images/背包_装备_需使用的/火山岛酬劳.png
  config/cus_images/背包_装备_需使用的/美味岛酬劳.png
  function/core/FAA.py
  function/core/FAA_ActionInterfaceJump.py
  function/core/QMW_1_load_settings.py
  logs/item_ranking_dag_graph.json
  resource/picture/ocr/texts_matched/号.png
  resource/picture/ocr/texts_matched/手.png
  resource/picture/ocr/texts_matched/械.png
  resource/picture/ocr/texts_matched/船.png
  resource/picture/ocr/texts_matched/镜.png
  resource/picture/ocr/texts_matched/魔.png
Labels: 🪲Bug

#259 1.5.0 beta2 修复了一个抽象问题
  function/core_battle/Card.py
Labels: 🪲Bug

#260 v1.5.0-beta.2 回滚抽象问题的错误解决, 通过更改识别逻辑(任意像素容差内->80%像素容差内)解决放卡迟钝错乱问题.
  function/common/bg_img_match.py
  function/common/bg_img_screenshot.py
  function/core/FAA.py
  function/core/FAA_ActionInterfaceJump.py
  function/core/FAA_Battle.py
  function/core/FAA_BattleARoundPreparation.py
  function/core/FAA_extra_readimage.py
  function/core/analyzer_of_loot_logs.py
  function/core_battle/Card.py
  function/core_battle/CardManager.py
  function/core_battle/CardQueue.py
  function/globals/g_extra.py
  logs/item_ranking_dag_graph.json
  test/test_screenshot.py
  打包_资源文件.py
  打包_部署.md
Labels: 🪲Bug

#266 v1.5.0-beta.3 自动大赛 - 解析文本为关卡代号. 需要ban卡以限制带卡数时, 对应承载卡优先级没能正确降低被ban优先级的问题已修正.
  function/scattered/match_ocr_text/text_to_battle_info.py
Labels: 🪲Bug

#267 v1.5.0-beta.3 自动大赛 - 解析文本为关卡代号. 需要ban卡以限制带卡数时, 对应承载卡优先级没能正确降低被ban优先级的问题已修正.
  function/scattered/get_house_id.py
  打包_资源文件.py
Labels: 🪲Bug, 🔼enhancement
