Repository StareAbyss/FoodsVsMiceAutoAssistant, pull requests merged in 2025-04, with the labels that each got.

#711 fix(战斗方案编辑器): 修复花瓶方案无法正确打开的问题.
  function/core/qmw_editor_of_battle_plan.py
Labels: Git-Fix, ✏️Module-Editor

#713 feat: 完成了FAA执行插件脚本功能的开发
  function/core/qmw_2_load_settings.py
  function/core/qmw_3_service.py
  function/core/tempCodeRunnerFile.py
  function/core/todo.py
  function/extension/function_faa.py
  function/extension/saltedfish.ico
  function/extension/saltedfish.qrc
  function/extension/saltedfish_rc.py
  function/extension/ui.py
  resource/ui/FAA_3.0.ui
  resource/ui/FAA_3.0_ui.py
  打包 & 部署.md
Labels: Git-Feat

#715 fix(关卡进入): 修复蛇来运转无法进入的问题, 错误原因, 将时间限制为了7:00-7:30, 而非 19:00-19:30
  function/core/faa/faa_core.py
  function/core/todo.py
Labels: Git-Fix

#716 fix(自建房对战): 修复该功能总是显示"关卡名称错误"的问题. 原因: 自建房内部id CU-0-0 不存在于用于校验的关卡id列表.
  function/core/faa/faa_action_receive_quest_rewards.py
  function/core/faa/faa_core.py
  function/core/todo.py
  function/scattered/loots_and_chest_data_save_and_post.py
  function/scattered/match_ocr_text/text_to_battle_info.py
  logs/item_ranking_dag_graph.json
Labels: Git-Fix

#717 feat(全自动大赛): 支持并强制使用全局方案+关卡方案完成大赛任务, 以应对番外的复杂关卡.
  config/settings_template.json
  function/core/qmw_2_load_settings.py
  function/core/todo.py
  function/scattered/match_ocr_text/text_to_battle_info.py
Labels: Git-Feat

#718 feat(全自动大赛): 正式支持同一任务完成三次后跳过, 防止无限循环. 优化执行任务的顺序, 并清晰输出展示该顺序的逻辑. (先双线程单人完成单人任务, 再从前往后一关一关/且从难到易地执行双人任务),
  function/core/faa/faa_core.py
  function/core/todo.py
  function/scattered/match_ocr_text/get_food_quest_by_ocr.py
  function/scattered/match_ocr_text/text_to_battle_info.py
Labels: Git-Feat

#719 fix(全自动大赛): 增加扫描密度, 以修复在扫描任务和领取奖励时, 偶尔遗漏的问题.
  function/core/faa/faa_action_receive_quest_rewards.py
  function/core/faa/faa_core.py
  function/scattered/match_ocr_text/get_food_quest_by_ocr.py
Labels: Git-Fix

#720 build(战斗方案): 更新沙漠全部方案, 音乐节日方案, 雪山通解方案, 使用机莓替代防空对地, 降低产火压力. 更新奇境通解方案, 确保能放下照明. 以适配自动大赛-番外副本.
  battle_plan/EX-2-1to6-1P 蜥蜴戈壁及以前.json
  battle_plan/EX-2-1to6-2P 蜥蜴戈壁及以前.json
  battle_plan/EX-2-7-1P 鱼骨-日.json
  battle_plan/EX-2-7-2P 鱼骨-日.json
  battle_plan/EX-2-8-1P 鱼骨-夜.json
  battle_plan/EX-2-8-2P 鱼骨-夜.json
  battle_plan/EX-2-9-1P 金字塔 SSS.json
  battle_plan/EX-2-9-2P 金字塔 SSS.json
  battle_plan/EX-3-N-1P 雪山通解.json
  battle_plan/EX-3-N-2P 雪山通解.json
  battle_plan/EX-4-5-1P 音乐节-日 低配.json
  battle_plan/EX-4-5-2P 音乐节-日 低配.json
  battle_plan/EX-5-1to5-1P 奇境通解.json
  battle_plan/EX-5-1to5-2P 奇境通解.json
Labels: 🗡️Module-Battle, Git-Build

#721 build(关卡信息): 修正音乐节日夜关卡的障碍物信息颠倒的错误. 更新在线关卡信息.
  config/stage_info.json
  config/stage_info_online.json
  config/stage_plan.json
Labels: Git-Build

#723 fix(战前准备): 双线程单人作战时, P战斗方案现在将采用1P方案而非2P方案. 以确保其拥有完整的战斗力.
  function/core/todo.py
Labels: Git-Fix, 🗡️Module-Battle

#724 fix(自动大赛): 修复多线程单人情况下, 可能出现卡死的问题.
  function/core/todo.py
Labels: Git-Fix

#725 perf(自动大赛): 支持根据任务要求, 判断是否需要使用钥匙或徽章; 支持"不放置任何"和"同时存在不超过"类型任务; 跳过"美食等级"类型任务.
  function/core/faa/faa_action_receive_quest_rewards.py
  function/core/qmw_1_log.py
  function/core/todo.py
  function/scattered/match_ocr_text/text_to_battle_info.py
Labels: Git-Perf

#728 fix(配置迁移工具): 修复无法迁移 版本为v3的战斗方案 的问题.
  function/core/qmw_settings_migrator.py
  function/scattered/check_battle_plan.py
Labels: Git-Fix
