Repository StareAbyss/FoodsVsMiceAutoAssistant, pull requests merged in 2025-05, with the labels that each got.

#731 perf(加速): 在战斗开始前，复核加速已经关闭.
  function/core/faa/faa_battle_preparation.py
Labels: Git-Perf

#729 feat:适配世界boss，修复前铲过快bug，修复子窗口关闭导致主窗口一并关闭bug
  config/stage_info.json
  function/core/faa/faa_action_interface_jump.py
  function/core/qmw_3_service.py
  function/core/qmw_tip_stage_id.py
  function/core_battle/card_manager.py
  function/globals/EXTRA.py
  logs/item_ranking_dag_graph.json
  resource/image/common/顶部菜单/巅峰对决.png
Labels: Git-Feat

#732 perf(关卡进出): 补充巅峰对决关卡, 在代号一览的视图, 以及在非开放时间的自动跳过功能.
  function/core/faa/faa_action_interface_jump.py
  function/core/faa/faa_core.py
  function/core/qmw_tip_stage_id.py
  function/globals/EXTRA.py
  resource/image/common/顶部菜单/巅峰对决.png
Labels: Git-Perf

#734 perf(用户界面): 美化任务列表界面.
  resource/ui/FAA_3.0.ui
Labels: Git-Perf

#736 fix(浇水施肥摘果): 清晰化运行时输出文本, 将最大运行次数调整回20次. 因为游戏又不再允许对已解散公会施肥(来回改折腾人呢).
  function/core/faa/faa_core.py
Labels: Git-Fix

#737 build: 自动删除物品默认名单添加, 仙人掌刺身卡套、怪味鱿鱼卡套+技能、海盐粉卡套、炸炸菇初级技能、耗油双菇卡套、辣椒粉初高级技能、金箔甜筒卡套、防风草沙拉卡套、雪糕投手卡套. 自动带卡内置转龙壶资源.
  config/cus_images/背包_道具_需删除的/仙人掌刺身-仙人掌.png
  config/cus_images/背包_道具_需删除的/仙人掌刺身-芥末.png
  config/cus_images/背包_道具_需删除的/仙人掌刺身-酱油.png
  config/cus_images/背包_道具_需删除的/仙人掌刺身配方.png
  config/cus_images/背包_道具_需删除的/咖喱龙虾炮-咖喱粉.png
  config/cus_images/背包_道具_需删除的/咖喱龙虾炮-椰奶.png
  config/cus_images/背包_道具_需删除的/咖喱龙虾炮-澳洲龙虾.png
  config/cus_images/背包_道具_需删除的/国王小笼包-小型压缩机.png
  config/cus_images/背包_道具_需删除的/废弃材料-活龙虾.png
  config/cus_images/背包_道具_需删除的/废弃材料-红辣椒.png
  config/cus_images/背包_道具_需删除的/怪味鱿鱼-初级技能书.png
  config/cus_images/背包_道具_需删除的/怪味鱿鱼-小米辣.png
  config/cus_images/背包_道具_需删除的/怪味鱿鱼-怪味豆.png
  config/cus_images/背包_道具_需删除的/怪味鱿鱼-章鱼仔.png
  config/cus_images/背包_道具_需删除的/怪味鱿鱼-配方.png
  config/cus_images/背包_道具_需删除的/怪味鱿鱼-高级技能书.png
  config/cus_images/背包_道具_需删除的/新疆拉面-拉面.png
  config/cus_images/背包_道具_需删除的/新疆拉面-洋葱.png
  config/cus_images/背包_道具_需删除的/新疆拉面-羊肉.png
  config/cus_images/背包_道具_需删除的/新疆拉面-配方.png
  config/cus_images/背包_道具_需删除的/海盐粉-大粒海盐.png
  config/cus_images/背包_道具_需删除的/海盐粉-玉米淀粉.png
  config/cus_images/背包_道具_需删除的/海盐粉-研磨瓶.png
  config/cus_images/背包_道具_需删除的/海盐粉-配方.png
  config/cus_images/背包_道具_需删除的/炸炸菇-初级技能书.png
  config/cus_images/背包_道具_需删除的/炸炸菇-炸药.png
  config/cus_images/背包_道具_需删除的/炸炸菇-爆炸菇.png
  config/cus_images/背包_道具_需删除的/炸炸菇-花椒叶.png
  config/cus_images/背包_道具_需删除的/炸炸菇-配方.png
  config/cus_images/背包_道具_需删除的/老虎蟹面包-螃蟹壳.png
  config/cus_images/背包_道具_需删除的/老虎蟹面包-配方.png
  config/cus_images/背包_道具_需删除的/耗油双菇-小喷嘴.png
  config/cus_images/背包_道具_需删除的/耗油双菇-茶树菇.png
  config/cus_images/背包_道具_需删除的/耗油双菇-蚝油.png
  config/cus_images/背包_道具_需删除的/耗油双菇-配方.png
  config/cus_images/背包_道具_需删除的/苏打气泡-吸管.png
  config/cus_images/背包_道具_需删除的/苏打气泡-小苏打.png
  config/cus_images/背包_道具_需删除的/苏打气泡-配方.png
  config/cus_images/背包_道具_需删除的/辣椒粉-初级技能书.png
  config/cus_images/背包_道具_需删除的/辣椒粉-高级技能书.png
  config/cus_images/背包_道具_需删除的/金箔甜筒-沙冰.png
  config/cus_images/背包_道具_需删除的/金箔甜筒-蛋卷.png
  config/cus_images/背包_道具_需删除的/金箔甜筒-配方.png
  config/cus_images/背包_道具_需删除的/金箔甜筒-金箔.png
  config/cus_images/背包_道具_需删除的/防风草沙拉-树枝.png
  config/cus_images/背包_道具_需删除的/防风草沙拉-线团.png
  config/cus_images/背包_道具_需删除的/防风草沙拉-配方.png
  config/cus_images/背包_道具_需删除的/防风草沙拉-防风草.png
  config/cus_images/背包_道具_需删除的/雪糕投手-炼乳.png
  config/cus_images/背包_道具_需删除的/雪糕投手-牛奶.png
  config/cus_images/背包_道具_需删除的/雪糕投手-绵白糖.png
  config/cus_images/背包_道具_需删除的/雪糕投手-配方.png
  config/cus_images/背包_道具_需删除的/食神谱-冰镇西瓜.png
  config/cus_images/背包_道具_需删除的/食神谱-南翔小笼包.png
  config/cus_images/背包_道具_需删除的/食神谱-美食豪华套餐.png
  config/cus_images/背包_道具_需删除的/食神谱-麻辣烫.png
  resource/image/card/准备房间/转龙壶-0.png
  resource/image/card/准备房间/转龙壶-1.png
  resource/image/card/准备房间/转龙壶-2.png
Labels: Git-Build

#738 fix: 修复了定时放卡居然不能设置浮点数的bug
  function/core/qmw_editor_of_battle_plan.py
  function/scattered/class_battle_plan_v3d0.py
Labels: Git-Fix, 🗡️Module-Battle

#740 fix(关卡进入): 修复公会副本关卡代号不在白名单中, 导致总是被跳过的问题.
  config/FAA配置文件简介(可用记事本打开).md
  config/card_type.json
  config/stage_info_online.json
  function/core/qmw_tip_stage_id.py
  function/globals/EXTRA.py
Labels: Git-Fix

#741 docs(README): 更新图片和新增内容.
  README.md
  md_img/任务列表.png
  md_img/运行主页.png
  md_img/高级功能.png
Labels: Git-Docs

#744 perf(自动大赛): 由于游戏的屎山代码, 部分任务即使没有注明要求, 实际也需要使用钥匙或徽章才能完成任务. 经群友投票, 将无脑使用钥匙徽章.
  function/core/faa/faa_core.py
  function/scattered/match_ocr_text/text_to_battle_info.py
Labels: Git-Perf

#747 fix(自动战斗): 在战斗条件-限制携带卡片数量应用时, 将额外禁用咖啡粉. 以确保卡片总数不超过限制要求.
  battle_plan/别西卜-花火海星散点.json
  function/core/faa/faa_battle_preparation.py
  function/scattered/match_ocr_text/text_to_battle_info.py
  logs/item_ranking_dag_graph.json
  resource/image/common/暗晶商店_ui.png
  task_sequence/生肖限时+巅峰对决.json
  打包 - 资源文件.py
  打包.bat
  新手入门 看我!!! 看我!!! 看我!!!.txt
Labels: Git-Fix, 🗡️Module-Battle
