Repository StareAbyss/FoodsVsMiceAutoAssistant, pull requests merged in 2025-02, with the labels that each got.

#653 feat(战斗方案协议): 完全重构战斗方案协议, 大规模重构战斗方案编辑器, 重写定时放卡编辑UI, 使用二级窗口编辑卡片属性, 同步同ID卡片的Name字段修改.
  function/core/QMW_EditorOfBattlePlan.py
  function/scattered/ClassBattlePlanV2d0.py
  function/scattered/ClassBattlePlanV3d0.py
Labels: Git-Feat, ✏️Module-Editor

#655 feat(战斗方案协议): 完全重构战斗方案协议, 重写FAA战斗内核对新协议的解析.
  function/core/FAA.py
  function/core/FAA_BattlePreparation.py
  function/core_battle/Card.py
  function/core_battle/CardManager.py
  function/core_battle/FAA_Battle.py
  function/deprecated/old_battle_loop.py
Labels: Git-Feat

#656 build: 删除战利品识别中, 错误的'怪味章鱼配方.png'
  resource/image/item/战利品/怪味章鱼配方.png
Labels: Git-Build

#657 perf(图像识别内核): 在未能正确识别到目标, 并通过根窗口拉起目标窗口后, 不再立刻重新截图, 而是休息一秒后重试.
  function/common/bg_img_screenshot.py
Labels: 👀Module-MatchImg, Git-Perf

#658 build: 修正战利品识别中少量物品名称错误 (香辣年糕蟹X级技能书 -> 香辣年糕蟹-X级技能书)
  logs/item_ranking_dag_graph.json
  resource/image/item/战利品/香辣年糕蟹-初级技能书.png
  resource/image/item/战利品/香辣年糕蟹-终极技能书.png
  resource/image/item/战利品/香辣年糕蟹-高级技能书.png
Labels: Git-Build

#659 build(删除物品): 背包-道具-默认删除物品新增15项物品.
  config/cus_images/背包_道具_需删除的/吸管.png
  config/cus_images/背包_道具_需删除的/咖喱粉.png
  config/cus_images/背包_道具_需删除的/咖喱龙虾炮配方.png
  config/cus_images/背包_道具_需删除的/小苏打.png
  config/cus_images/背包_道具_需删除的/拉面.png
  config/cus_images/背包_道具_需删除的/新疆炒面配方.png
  config/cus_images/背包_道具_需删除的/椰奶.png
  config/cus_images/背包_道具_需删除的/洋葱.png
  config/cus_images/背包_道具_需删除的/活龙虾.png
  config/cus_images/背包_道具_需删除的/澳洲龙虾.png
  config/cus_images/背包_道具_需删除的/红辣椒.png
  config/cus_images/背包_道具_需删除的/羊肉.png
  config/cus_images/背包_道具_需删除的/老虎蟹面包配方.png
  config/cus_images/背包_道具_需删除的/苏打气泡配方.png
  config/cus_images/背包_道具_需删除的/螃蟹壳.png
Labels: Git-Build

#651 fix(大量炒饭修复):高级战斗，皮肤
  function/core/FAA_extra_readimage.py
  function/core/QMW_0_load_ui_file.py
  function/core/QMW_EditorOfBattlePlan.py
  function/core/Todo.py
  function/globals/log.py
  resource/ui/firefly.png
Labels: Git-Fix

#660 fix(关卡信息): 魔塔单人, 86-90 和 91-95 承载卡对调以修正错误. 161-165 飞车落点不再视为障碍物.
  config/stage_info.json
Labels: Git-Fix, 🗡️Module-Battle

#661 refactor(自动大赛): 优化美食大赛任务选择逻辑
  function/core/FAA.py
  function/core/Todo.py
  function/scattered/match_ocr_text/text_to_battle_info.py
  resource/image/ocr/美食大赛/先.png
  resource/image/ocr/美食大赛/兔.png
  resource/image/ocr/美食大赛/午.png
  resource/image/ocr/美食大赛/境.png
  resource/image/ocr/美食大赛/夫.png
  resource/image/ocr/美食大赛/庭.png
  resource/image/ocr/美食大赛/径.png
  resource/image/ocr/美食大赛/悬.png
  resource/image/ocr/美食大赛/扑.png
  resource/image/ocr/美食大赛/护.png
  resource/image/ocr/美食大赛/梦.png
  resource/image/ocr/美食大赛/洞.png
  resource/image/ocr/美食大赛/游.png
  resource/image/ocr/美食大赛/漫.png
  resource/image/ocr/美食大赛/牌.png
  resource/image/ocr/美食大赛/玫.png
  resource/image/ocr/美食大赛/瑰.png
  resource/image/ocr/美食大赛/生.png
  resource/image/ocr/美食大赛/白.png
  resource/image/ocr/美食大赛/罩.png
  resource/image/ocr/美食大赛/菇.png
  resource/image/ocr/美食大赛/蘑.png
  resource/image/ocr/美食大赛/院.png
Labels: Git-Perf

#662 build(OCR): 新增78个额外文本支持.
  function/core/QMW_TipStageID.py
  resource/image/ocr/关卡名称/E.png
  resource/image/ocr/关卡名称/c.png
  resource/image/ocr/关卡名称/t.png
  resource/image/ocr/关卡名称/了.png
  resource/image/ocr/关卡名称/儿.png
  resource/image/ocr/关卡名称/兔.png
  resource/image/ocr/关卡名称/刷.png
  resource/image/ocr/关卡名称/午.png
  resource/image/ocr/关卡名称/叮.png
  resource/image/ocr/关卡名称/响.png
  resource/image/ocr/关卡名称/场.png
  resource/image/ocr/关卡名称/好.png
  resource/image/ocr/关卡名称/工.png
  resource/image/ocr/关卡名称/帮.png
  resource/image/ocr/关卡名称/庭.png
  resource/image/ocr/关卡名称/开.png
  resource/image/ocr/关卡名称/当.png
  resource/image/ocr/关卡名称/径.png
  resource/image/ocr/关卡名称/悬.png
  resource/image/ocr/关卡名称/手.png
  resource/image/ocr/关卡名称/扫.png
  resource/image/ocr/关卡名称/施.png
  resource/image/ocr/关卡名称/杂.png
  resource/image/ocr/关卡名称/来.png
  resource/image/ocr/关卡名称/树.png
  resource/image/ocr/关卡名称/梦.png
  resource/image/ocr/关卡名称/民.png
  resource/image/ocr/关卡名称/汤.png
  resource/image/ocr/关卡名称/洗.png
  resource/image/ocr/关卡名称/洞.png
  resource/image/ocr/关卡名称/清.png
  resource/image/ocr/关卡名称/物.png
  resource/image/ocr/关卡名称/玫.png
  resource/image/ocr/关卡名称/现.png
  resource/image/ocr/关卡名称/瑰.png
  resource/image/ocr/关卡名称/百.png
  resource/image/ocr/关卡名称/的.png
  resource/image/ocr/关卡名称/菇.png
  resource/image/ocr/关卡名称/葵.png
  resource/image/ocr/关卡名称/蘑.png
  resource/image/ocr/关卡名称/行.png
  resource/image/ocr/关卡名称/谷.png
  resource/image/ocr/关卡名称/豆.png
  resource/image/ocr/关卡名称/车.png
  resource/image/ocr/关卡名称/辣.png
  resource/image/ocr/关卡名称/逆.png
  resource/image/ocr/关卡名称/铃.png
  resource/image/ocr/关卡名称/铜.png
  resource/image/ocr/关卡名称/银.png
  resource/image/ocr/关卡名称/锅.png
  resource/image/ocr/关卡名称/院.png
  resource/image/ocr/关卡名称/除.png
  resource/image/ocr/关卡名称/静.png
  resource/image/ocr/关卡名称/鬼.png
  resource/image/ocr/关卡名称/鸯.png
  resource/image/ocr/关卡名称/鸳.png
  resource/image/ocr/关卡名称/麻.png
Labels: 👀Module-MatchImg, Git-Build

#663 feat: 新增连携启动天知强卡器!
  function/common/TCEPipeCommunicationThread.py
  function/core/QMW_2_load_settings.py
  function/core/QMW_3_service.py
  resource/ui/FAA_3.0.ui
Labels: Git-Feat, 🗡️Module-Battle

#664 fix(联动天知强卡器): 完成内部事项处理.
  function/core/Todo.py
Labels: Git-Fix

#666 perf(联动天知强卡器): 修改运行位置, 修改配置方式.
  config/settings_template.json
  function/core/QMW_2_load_settings.py
  function/core/QMW_3_service.py
  function/core/Todo.py
  resource/ui/FAA_3.0.ui
Labels: Git-Perf

#667 perf(开屏输出): 使用超链接替代链接.
  function/core/QMW_1_log.py
Labels: 🕹️Module-UI, Git-Perf

#668 perf(用户界面): 完全重做进阶设置界面, 使用可下滑区域放置控件 + 列表索引导航.
  function/core/QMW_0_load_ui_file.py
Labels: 🕹️Module-UI, Git-Perf

#672 perf(自动选卡): 极大优化了选卡速度 - 采用动态等待时间 + 缩减视图范围 + 减少重复截图
  function/core/FAA_BattlePreparation.py
Labels: 🗡️Module-Battle, Git-Perf

#673 perf(战斗线程初始化): 通过优化战斗刚开始时的对卡组的图像识别逻辑, 极大优化启动时间(3.8s -> 1.4s)
  function/common/bg_img_match.py
  function/core/FAA.py
  function/core/Todo.py
  function/core_battle/FAA_Battle.py
Labels: Git-Perf

#670 style(皮肤): 优化了深色类皮肤字体看不清的问题
  function/core/QMW_1_log.py
  resource/theme/GTRONICK/ElegantDark.qss
Labels: 🕹️Module-UI, Git-Perf

#674 build(关卡信息): 珊瑚洋流补充1-3铲卡位置; 巫毒回廊补充障碍位置; 五级冰雹承载位置错误修复; Online信息更新;
  config/stage_info.json
  config/stage_info_online.json
  logs/item_ranking_dag_graph.json
Labels: 🗡️Module-Battle, Git-Build

#675 build(战斗方案): 定时放卡CS-6-5方案重置, 配置够高可SSS; 修正萌新冷萃莓果方案不支持自动带卡的问题; 新增最新星际悬赏方案.
  battle_plan/CS-6-5-1P.json
  battle_plan/CS-6-5-2P.json
  battle_plan/EX-5-1to5-1P 奇境通解.json
  battle_plan/NO-6-10-1P 多拿滋 加速SSS.json
  battle_plan/NO-6-10-2P 多拿滋 加速SSS.json
  battle_plan/悬赏4-1P.json
  battle_plan/悬赏4-2P.json
  battle_plan/萌新专用-冷萃莓果.json
  config/stage_plan.json
  task_sequence/默认.json
Labels: 🗡️Module-Battle, Git-Build

#676 build: 版本号更新 v2.2.0
  function/core/FAA.py
  function/globals/EXTRA.py
Labels: Relese, Git-Build

#677 build(战利品识别): 移除以下物品资源: 小喷菇/横向冰冻小笼包配方/珍珠/蜜枣/酥油/面团; 修复雪山钥匙名称(原雪山)
  resource/image/item/战利品/小喷菇.png
  resource/image/item/战利品/横向冰冻小笼包配方.png
  resource/image/item/战利品/珍珠.png
  resource/image/item/战利品/蜜枣.png
  resource/image/item/战利品/酥油.png
  resource/image/item/战利品/雪山钥匙.png
  resource/image/item/战利品/面团.png
Labels: Git-Build, 🧐Module-Drop

#678 perf(内部教程): 增加日氪模块/加速模块.
  function/core/QMW_3_service.py
  function/core/QMW_TipAccelerateSettings.py
Labels: 🕹️Module-UI, Git-Perf

#679 refactor(战斗执行器): 完全重构定时放卡模块. 使其在manager stop后能销毁未完成执行的任务定时器. 并减少代码冗余.
  function/core/FAA.py
  function/core_battle/CardManager.py
  function/core_battle/FAA_Battle.py
Labels: 🗡️Module-Battle, Git-Perf

#680 fix(按波次变阵): 修复按波次变阵期间, 因多线程同步问题, 导致偶尔变阵铲卡会出现遗漏的问题.
  function/core/FAA.py
  function/core/QMW_3_service.py
  function/core/QMW_UsefulToolsWidget.py
  function/core/Todo.py
  function/core_battle/Card.py
  function/core_battle/CardManager.py
  function/core_battle/FAA_Battle.py
  function/globals/thread_action_queue.py
  resource/ui/FAA_3.0.ui
Labels: Git-Fix, 🗡️Module-Battle

#681 perf(战前准备): 优化点击开始按钮 -> 查找到火苗开始战斗 中, 大量识图的性能. 以减少耗时, 提高定时放卡精准度.
  battle_plan/NO-6-7-1P 巴旦木-夜 10损 SSS.json
  battle_plan/NO-6-7-2P 巴旦木-夜 10损 SSS.json
  function/core/FAA_BattlePreparation.py
Labels: Git-Perf

#682 fix(战利品识别): 修复一个问题, 该问题导致战利品识别确定为错误图像后, 仍会运行一次必定失败的有向无环图更新, 造成浪费.
  function/core/Todo.py
Labels: Git-Fix

#683 fix(战斗执行器): 在需要继续战斗时, 强制清空点击队列. 使部分参数设置不合理的用户也能正常完成相关流程. 并在点击队列出现堆积时弹…
  function/core_battle/FAA_Battle.py
Labels: Git-Fix, 🗡️Module-Battle

#684 build(打包部署): 使用UPX打包, 软件大小直接减半!
  打包 & 部署.md
  打包.bat
Labels: Relese, Git-Build

#686 perf(战斗执行器): 重新规范大量检测操作和放卡操作的时间间隔. 并修正默认卡片放满自锁时间只有设定值一半的bug.
  function/core_battle/card_manager.py
  function/core_battle/card_queue.py
Labels: Git-Perf

#687 fix(战斗执行器): 全局冰沙锁现在仅在组队战斗的情况下激活. 不再影响单人战斗.
  function/core_battle/card.py
  function/core_battle/card_manager.py
Labels: Git-Fix, 🗡️Module-Battle

#688 fix(战斗执行器): 修复宝石使用间隔 / 模拟收集间隔 / 冰沙锁时间 短于预期的问题.
  function/core_battle/card_manager.py
  function/globals/EXTRA.py
Labels: Git-Fix

#689 feat(删除物品): 支持翻页删除, 完整遍历整个背包.
  function/core/faa/faa_base.py
Labels: Git-Feat

#691 build: 修复无法打包的文件结构.
  function/common/bg_img_match.py
  function/core/faa/__init__.py
  function/core/faa/faa_action_interface_jump.py
  function/core/faa/faa_action_receive_quest_rewards.py
  function/core/faa/faa_battle.py
  function/core/faa/faa_battle_preparation.py
  function/core/faa/faa_core.py
  function/core/faa/faa_mix.py
  function/core/faa_extra_readimage.py
  function/core/qmw_3_service.py
  function/core/todo.py
  function/core_battle/card.py
  function/core_battle/card_manager.py
  function/scattered/loots_and_chest_data_save_and_post.py
  function/scattered/time_line_editor.py
  function/scattered/todo_timer_manager.py
Labels: Git-Build

#692 fear: 完成了QQ密码登录和额外休眠功能的开发
  function/core/faa/faa_core.py
  function/core/my_crypto.py
  function/core/qmw_2_load_settings.py
  function/core/qmw_3_service.py
  function/core/qmw_tip_qqlogin.py
  function/core/qmw_tip_sleep.py
  resource/image/common/登录/叉号.png
  resource/image/common/登录/密码登录.png
  resource/image/common/登录/密码输入框.png
  resource/image/common/登录/登录.png
  resource/image/common/登录/账号输入框.png
  resource/ui/FAA_3.0.ui
  resource/ui/FAA_3.0_ui.py
Labels: Git-Feat

#693 perf: 优化自动抽许愿池功能
  function/tools/useful_tools.py
  resource/image/common/许愿十次.png
Labels: Git-Perf

#695 fix(定时任务): 修复定时任务为空时, 会触发报错的问题.
  function/core/qmw_2_load_settings.py
  function/core/qmw_3_service.py
Labels: Git-Fix

#697 fix(日志): 修复Error层级的日志也会导致弹窗的问题, 现在该类型的弹窗仅由Critical层级的日志触发!
  function/core/faa/faa_core.py
  function/core/todo.py
  function/globals/log.py
  logs/item_ranking_dag_graph.json
  requirements.txt
  打包 & 部署.md
  打包.bat
Labels: Git-Fix, 🕹️Module-UI
