Repository StareAbyss/FoodsVsMiceAutoAssistant, pull requests merged in 2025-01, with the labels that each got.

#569 perf(公会任务):不再仅获取1P任务, 而是取交集. 将所有'工会'文本修正为'公会'
  a_欢乐互娱bug.md
  function/core/FAA.py
  function/core/FAA_ActionInterfaceJump.py
  function/core/QMW_2_load_settings.py
  function/core/QMW_3_service.py
  function/core/Todo.py
Labels: Git-Perf

#571 feat(战斗执行器): 新增开局加速功能, 通过在开局启用游戏倍速(对总时长影响1s内), 使波次间隔缩短. 战斗时长最大缩短20%.
  config/settings_template.json
  function/core/FAA.py
  function/core/FAA_BattlePreparation.py
  function/core/QMW_2_load_settings.py
  function/core/Todo.py
  function/globals/EXTRA.py
  logs/item_ranking_dag_graph.json
  resource/image/common/战斗/变速.png
  resource/image/common/战斗/变速_被点击.png
  resource/image/common/战斗/变速_被选中.png
  resource/ui/FAA_3.0.ui
  test/capture_image/__init__.py
  test/capture_image/main.py
  test/match_png/test_match_image.py
  test/test_click.py
  test/test_screenshot.py
Labels: Git-Feat, 🗡️Module-Battle

#572 perf(战斗执行器): 判定是否点击继续战斗时, 如果选择不使用钥匙, 将点击领取奖励直接结束战斗, 不再发呆20s. 优化相关识图.
  function/core_battle/FAA_Battle.py
  resource/image/common/战斗/战斗中_继续作战.png
  resource/image/common/战斗/战斗中_领取奖品.png
Labels: 🗡️Module-Battle, Git-Perf

#573 feat(战斗执行器): 新增最大单局战斗时长功能.
  config/settings_template.json
  function/core/FAA.py
  function/core/QMW_2_load_settings.py
  function/core_battle/FAA_Battle.py
  function/globals/EXTRA.py
  resource/ui/FAA_3.0.ui
Labels: Git-Feat, 🗡️Module-Battle

#574 perf(战斗执行器): 翻牌. 使用Bug翻牌法, 降低耗时约8s.
  function/core/FAA_BattlePreparation.py
Labels: 🗡️Module-Battle, Git-Perf

#575 refactor(战斗方案编辑器): 重新布局. 调整为1280x720的横向布局. 1K屏150%也能完整显示UI. 更符合操作直觉.
  function/core/QMW_EditorOfBattlePlan.py
Labels: Git-Perf, ✏️Module-Editor

#570 feat(360游戏大厅开关): 新增自启动和关闭360游戏大厅功能. 新增弱保软按钮.
  config/settings_template.json
  function/core/QMW_2_load_settings.py
  function/core/QMW_3_service.py
  function/core/Todo.py
  function/core/Win_api.py
  function/scattered/get_channel_name.py
  resource/ui/FAA_3.0.ui
Labels: Git-Feat

#576 build(战斗方案): 金字塔SSS方案, 解决花火龙和棕榈吹风机摆放位置冲突的问题.
  battle_plan/EX-2-9-1P 金字塔 SSS.json
  battle_plan/EX-2-9-2P 金字塔 SSS.json
Labels: 🗡️Module-Battle, Git-Build

#577 refactor(战斗加速): 重构用户界面和操作逻辑. 新增结算加速.
  config/settings_template.json
  function/core/FAA_BattlePreparation.py
  function/core/QMW_2_load_settings.py
  function/core/Todo.py
  function/globals/EXTRA.py
  resource/ui/FAA_3.0.ui
Labels: 🗡️Module-Battle, 🕹️Module-UI, Git-Perf

#578 perf(UI): 进阶功能-战斗设定. 部分功能未启用时, 对应的详细参数设置框将被自动锁定无法编辑. 以提高用户体验.
  function/core/QMW_2_load_settings.py
Labels: 🕹️Module-UI, Git-Perf

#579 perf(登录): 跟进游戏更新, 替换 退出开屏时 假期特惠 所用的资源文件.
  function/core/FAA.py
  resource/image/common/登录/4_退出假期特惠.png
  resource/image/common/登录/4_退出每日必充.png
Labels: Git-Perf

#580 fix(战利品识别): 修复有向无环图校验和物品连续性校验的一项重大Bug. 游戏内掉落物(四叶草/香料)若在单局中以特定顺序同时出现绑定和非绑定, 不再会导致校验失败判定为无效数据.
  config/settings_template.json
  function/core/FAA_BattlePreparation.py
  function/core/Todo.py
  function/core/analyzer_of_loot_logs.py
Labels: Git-Fix, 🧐Module-Drop

#581 perf(战利品扫描): 结算战利品输出图片时, 将根据历史有向无环图的最长链, 对可以确定前后关系的部分自动排序
  function/core/Todo.py
  function/core/Win_api.py
  function/core_battle/FAA_Battle.py
  logs/item_ranking_dag_graph.json
Labels: Git-Perf, 🧐Module-Drop

#582 perf(进阶功能设定): 优化UI布局, 规范大量控件命名, 细化鼠标提示信息.
  config/settings_template.json
  function/core/QMW_2_load_settings.py
  function/core/QMW_3_service.py
  resource/ui/FAA_3.0.ui
Labels: 🕹️Module-UI, Git-Perf

#583 feat(战斗执行器): 允许用户在UI中自定义, 卡片放满自锁的时长.
  config/settings_template.json
  function/core/QMW_2_load_settings.py
  function/core_battle/Card.py
  function/globals/EXTRA.py
Labels: Git-Feat, 🗡️Module-Battle, 🕹️Module-UI

#584 fix(使用消耗品): 修正多物品礼包打开后的界面无法关闭的Bug
  function/core/FAA.py
  function/core/QMW_2_load_settings.py
Labels: Git-Fix

#585 build(版本号更新): v2.1.0
  function/globals/EXTRA.py
Labels: Git-Build

#587 perf(登录): 跟进游戏更新, 修改进入游戏成功判定点. 原判定将被 假期特惠遮挡.
  function/core/FAA.py
  function/core/FAA_ActionInterfaceJump.py
  resource/image/common/底部菜单/任务.png
  resource/image/common/底部菜单/公会.png
  resource/image/common/底部菜单/后退.png
  resource/image/common/底部菜单/背包.png
  resource/image/common/底部菜单/跳转.png
  resource/image/common/底部菜单/跳转_公会任务.png
  resource/image/common/底部菜单/跳转_公会副本.png
  resource/image/common/底部菜单/跳转_情侣任务.png
  resource/image/common/底部菜单/跳转_竞技场.png
  resource/image/common/底部菜单/跳转_缘分树.png
  resource/image/common/顶部菜单/大地图.png
Labels: Git-Perf

#588 perf(图像识别): 标准图像识别新增错误处理, 将以错误日志形式输出目标和源图像大小.
  function/common/bg_img_match.py
Labels: 👀Module-MatchImg, Git-Perf

#586 style(文本描述): 修正自动开关文本描述
  function/core/QMW_3_service.py
  resource/ui/FAA_3.0.ui
Labels: Git-Perf

#589 build(资源更新): 线上关卡信息 / 图优化优化 / 赞助名单 例行更新.
  config/stage_info_online.json
  function/tools/calculation_grind_chest.py
  logs/item_ranking_dag_graph.json
  新手入门 看我!!! 看我!!! 看我!!!.txt
  致谢名单.png
Labels: Git-Build

#591 perf(开关游戏大厅): 自动开启游戏后, 自动关闭小号列表, 避免造成界面错位.
  function/core/FAA.py
  resource/image/common/登录/小号列表.png
Labels: Git-Perf

#592 refactor(开关游戏大厅): 重构相关函数为窗口操作基本库; 改为使用对应的参数进行调用, 以完成原有功能; 改用多线程实现不再堵塞主线程; 补充大量注释和梳理代码逻辑.
  function/common/process_and_window_manager.py
  function/core/QMW_2_load_settings.py
  function/core/QMW_3_service.py
  function/core/QThread_360.py
  function/core/Todo.py
  function/core/Win_api.py
Labels: Git-Perf

#593 perf(开关游戏大厅): 结束流程后, 若选择关闭游戏大厅, 自然不用退出到登录页, 故锁定后者UI和无视相关操作.
  function/core/QMW_2_load_settings.py
  function/core/QMW_3_service.py
  function/core/QMW_EditorOfBattlePlan.py
  logs/item_ranking_dag_graph.json
  resource/ui/FAA_3.0.ui
  test/test.py
Labels: Git-Perf

#594 perf(开关游戏大厅): 增加Tip界面
  function/core/QMW_3_service.py
  function/core/QMW_TipLoginSettings.py
Labels: 🕹️Module-UI, Git-Perf

#597 perf(加速游戏): 增加关闭检测确保关闭加速. 优化资源和流程, 提高相关识别效率.
  function/core/FAA.py
  function/core/FAA_BattlePreparation.py
  resource/image/common/战斗/变速.png
  resource/image/common/战斗/变速_被点击.png
  resource/image/common/战斗/变速_被选中.png
  resource/image/common/战斗/变速_默认或被点击.png
  resource/image/common/战斗/未激活变速_被选中或被点击.png
  resource/image/common/战斗/未激活变速_默认.png
Labels: Git-Perf

#598 refactor(控制游戏大厅): 完全重构, 从主线程迁移至事项线程, 执行时不再阻塞主线程造成卡死. 重新梳理游戏大厅GAID的逻辑, 并以此为基础重写相关指南和填写UI.
  function/core/FAA.py
  function/core/QMW_3_service.py
  function/core/QMW_TipLoginSettings.py
  function/core/QThread_360.py
  function/core/Todo.py
  resource/ui/FAA_3.0.ui
Labels: Git-Docs, Git-Perf

#599 perf(控制游戏大厅): 根据GAID, 获取360游戏大厅.exe路径和小号名称的功能中, 获取小号名称已移除. 此乃反向弱保软, 加大了用户的使用难度.
  function/core/QMW_3_service.py
  resource/ui/FAA_3.0.ui
Labels: Git-Perf

#600 build(战斗方案): 多拿滋方案新增SSS平民方案 可以通过手动倍速强行完成公会任务.
  battle_plan/NO-6-10-1P 多拿滋 加速SSS.json
  battle_plan/NO-6-10-2P 多拿滋 加速SSS.json
Labels: 🗡️Module-Battle, Git-Build

#601 build(战斗方案): 多拿滋速刷方案, 修正少量错误并进行少量优化. 修正大量方案的2P的描述.
  battle_plan/1通用-花火-2P.json
  battle_plan/2速刷-生煎电棍-2P.json
  battle_plan/2速刷-生煎电棍花火-2P.json
  battle_plan/2速刷-生煎追踪电棍花火-2P.json
  battle_plan/3难关-魔塔双人-100-2P.json
  battle_plan/EX-2-9-1P 金字塔 SSS.json
  battle_plan/EX-2-9-2P 金字塔 SSS.json
  battle_plan/NO-6-10-1P 多拿滋.json
  battle_plan/NO-6-10-2P 多拿滋.json
  battle_plan/NO-6-7-2P 巴旦木-夜 10损 SSS.json
Labels: 🗡️Module-Battle, Git-Build

#602 build(关卡信息): 修补莓莓音乐节 - 夜的障碍物位置信息的缺失.
  config/stage_info.json
Labels: 🗡️Module-Battle, Git-Build

#603 perf(界面跳转): 跟进游戏更新, 支持悬赏关卡蛇年UI和第四个悬赏关卡.
  config/stage_info.json
  function/core/FAA_ActionInterfaceJump.py
  function/core/QMW_2_load_settings.py
  function/core/Todo.py
  resource/image/stage/OR-0-1.png
  resource/image/stage/OR-0-2.png
  resource/image/stage/OR-0-3.png
  resource/image/stage/OR-0-4.png
  resource/ui/FAA_3.0.ui
Labels: Git-Perf

#605 docs(战斗方案编辑器): 修正新版编辑器中, 点击保存后, 编辑器卡死的问题.
  function/core/QMW_EditorOfBattlePlan.py
Labels: Git-Fix, ✏️Module-Editor

#606 perf(日志): 新增一项警告, 当用户在仅有一个角色选择双人模式触发自动调整后, 将进行日志输出.
  function/core/Todo.py
  function/globals/thread_action_queue.py
  function/scattered/TodoTimerManager.py
  logs/item_ranking_dag_graph.json
  resource/image/common/悬赏任务_领取奖励.png
  resource/image/common/顶部菜单/X年活动.png
  resource/ui/FAA_3.0.ui
Labels: Git-Perf

#607 fix(任务序列编辑器): 修复其UI过窄导致战斗类任务显示不全的问题.
  function/core/QMW_EditorOfTaskSequence.py
Labels: Git-Fix

#608 fix(界面跳转): 修复公会副本进入房间偶尔失效的问题.
  function/core/Todo.py
Labels: Git-Fix

#610 build(战斗资源): 新增第四悬赏相关关卡信息, 方案, 关卡全局方案设定.
  battle_plan/悬赏-大扫除-星际-1P.json
  battle_plan/悬赏-大扫除-星际-2P.json
  config/settings_template.json
  config/stage_plan.json
Labels: 🗡️Module-Battle, Git-Build

#611 perf(删除道具): 默认删除道具新增三项冰冻小笼包和冰煮蛋器投手-终极技能书.
  config/cus_images/背包_道具_需删除的/三向冰冻小笼包-终级技能书.png
  config/cus_images/背包_道具_需删除的/冰煮蛋器投手-终极技能书.png
Labels: Git-Build

#612 perf(关卡信息): 勇士关卡中的海底, 不再使用苏打气泡作为承载. 因为会被击破.
  config/stage_info.json
Labels: Git-Perf

#613 feat(全局方案): 分离全局方案和关卡方案功能. 激活全局关卡方案功能后, 优先读取关卡方案, 没有则读取全局方案. 完成该功能的编辑…
  config/stage_plan.json
  function/core/QMW_EditorOfStagePlan.py
  function/core/Todo.py
  resource/ui/StagePlanEditor.ui
Labels: Git-Feat

#614 fix(战斗流程): 若用户完成方案设置后删除了对应方案, 将因找不到uuid对应的方案而卡死. 现在, 将提前检测, 跳过对应战斗, 并提示用户进行修正.
  function/core/FAA.py
  function/core/Todo.py
  resource/ui/FAA_3.0.ui
Labels: Git-Fix, 🕹️Module-UI

#615 perf(UI): 若用户填写了单人窗口名, 但激活了功能的双人模式. 将直接在UI而不仅是日志中弹出警告并纠正. 纠错范围额外增加,常规战斗将自动纠错为单人, 双人魔塔/公会任务/情侣任务/公会副本将直接跳过对应流程.
  function/core/Todo.py
Labels: 🕹️Module-UI, Git-Perf

#616 perf(自动战斗): 优化多复制卡的放置表现. 在用户使用不同的queue参数时采用分支策略, 确保不吞复制次数.
  function/core/FAA.py
  function/core_battle/Card.py
Labels: 🗡️Module-Battle, Git-Perf

#617 build(自动带卡): 新增类型"对空投手", 支持新卡.
  config/card_type.json
  resource/image/card/准备房间/五行蛇-0.png
  resource/image/card/准备房间/五行蛇-1.png
  resource/image/card/准备房间/五行蛇-2.png
  resource/image/card/准备房间/导弹蛇-0.png
  resource/image/card/准备房间/导弹蛇-1.png
  resource/image/card/准备房间/导弹蛇-2.png
  resource/image/card/准备房间/彩虹蛇-0.png
  resource/image/card/准备房间/彩虹蛇-1.png
  resource/image/card/准备房间/彩虹蛇-2.png
  resource/image/card/准备房间/恶作剧神-0.png
  resource/image/card/准备房间/恶作剧神-1.png
  resource/image/card/准备房间/恶作剧神-2.png
  resource/image/card/准备房间/樱桃反弹布丁-2.png
  resource/image/card/准备房间/法师蛇-0.png
  resource/image/card/准备房间/法师蛇-1.png
  resource/image/card/准备房间/法师蛇-2.png
  resource/image/card/准备房间/炸炸菇-0.png
  resource/image/card/准备房间/炸炸菇-1.png
  resource/image/card/准备房间/爆裂蛇-0.png
  resource/image/card/准备房间/爆裂蛇-1.png
  resource/image/card/准备房间/爆裂蛇-2.png
  resource/image/card/准备房间/百变蛇-0.png
  resource/image/card/准备房间/百变蛇-1.png
  resource/image/card/准备房间/百变蛇-2.png
  resource/image/card/准备房间/蛇羹煲-0.png
  resource/image/card/准备房间/蛇羹煲-1.png
  resource/image/card/准备房间/蛇羹煲-2.png
  resource/image/card/准备房间/赖皮蛇-0.png
  resource/image/card/准备房间/赖皮蛇-1.png
  resource/image/card/准备房间/赖皮蛇-2.png
Labels: 🗡️Module-Battle, Git-Build

#619 fix(战斗方案编辑器): 修正问题: 修改放卡位置, 修改放卡优先级时, 波次高亮未能正确刷新.
  function/core/QMW_EditorOfBattlePlan.py
Labels: Git-Fix

#620 fix(战斗执行器): 修正双人执行波次变阵时, 罕见情况下, 检测波次线程同步出现异常, 导致其中一角色无法完成变阵.
  function/core/Todo.py
  function/core_battle/CardManager.py
Labels: Git-Fix

#622 build(自动带卡): 优化类型"布丁/反弹", 加入二转樱桃反弹布丁并根据数值排序优先级.
  config/card_type.json
  function/core/QMW_EditorOfBattlePlan.py
Labels: Git-Build

#623 fix(战斗方案编辑器): 修复玩家位置无法正常高亮的bug
  config/stage_info.json
  logs/item_ranking_dag_graph.json
Labels: Git-Fix, ✏️Module-Editor

#624 perf(主要流程): 将主要流程(Todo)中, 部分在Todo线程中执行的耗时操作, 移动到子线程进行, 以尝试规避流程中的未知卡死问题. 拆出日氪/温馨礼包/二级密码模块并重新封装, 以优化流程和输出文本.
  function/common/thread_with_exception.py
  function/core/Todo.py
Labels: Git-Perf

#630 feat: 新增开机自启动功能 / 新增战斗方案搜索框控件.
  function/common/startup.py
  function/core/QMW_3_service.py
  function/widget/SearchableComboBox.py
  resource/ui/FAA_3.0.ui
  test/test.py
Labels: Git-Feat

#631 perf(UI): 战斗方案搜索框控件, 适配Windows黑夜主题. 重绘开启搜索框的图标, 融入当前美术设计.
  function/core/QMW_0_load_ui_file.py
  function/widget/CusIcon.py
  function/widget/SearchableComboBox.py
Labels: 🕹️Module-UI, Git-Perf

#632 perf(UI): 360游戏大厅Gaid设置项最大值修改(99->9999)
  resource/ui/FAA_3.0.ui
Labels: 🕹️Module-UI, Git-Perf

#634 fix(浇水 施肥 摘果): 为跟进可重复施肥的游戏改动进行的修正不完全, 导致两个角色间继承尝试次数计数, 进而在罕见情况下产生无限施肥. 对该问题进行了修正.
  function/core/FAA.py
  function/core/FAA_extra_readimage.py
  function/core/QMW_1_log.py
  function/core/Todo.py
  function/core/performance_analysis.py
  resource/ui/FAA_3.0.ui
Labels: Git-Fix

#636 perf(战斗执行器): 多复制卡优化, 采用先幻鸡后创造神的策略, 间隔1.5s, 最大限度缩短等待时间, 且不吞卡.
  function/core/FAA.py
  function/core_battle/Card.py
Labels: Git-Perf

#637 build(自动带卡): 新增40项常用卡片图片, 感谢群友轻狂的补充.
  battle_plan/2速刷-生煎电棍-1P.json
  battle_plan/2速刷-生煎电棍-2P.json
  battle_plan/2速刷-生煎电棍花火-1P.json
  battle_plan/2速刷-生煎电棍花火-2P.json
  battle_plan/2速刷-生煎追踪电棍花火-1P.json
  battle_plan/2速刷-生煎追踪电棍花火-2P.json
  battle_plan/EX-2-7-2P 鱼骨-日.json
  function/core/Todo.py
  logs/item_ranking_dag_graph.json
  resource/image/card/准备房间/9周年幸运草扇-0.png
  resource/image/card/准备房间/三线酒架-0.png
  resource/image/card/准备房间/三线酒架-1.png
  resource/image/card/准备房间/三线酒架-2.png
  resource/image/card/准备房间/上古神-0.png
  resource/image/card/准备房间/上古神-1.png
  resource/image/card/准备房间/上古神-2.png
  resource/image/card/准备房间/冰淇淋-0.png
  resource/image/card/准备房间/冰淇淋-1.png
  resource/image/card/准备房间/双子座精灵-0.png
  resource/image/card/准备房间/双子座精灵-1.png
  resource/image/card/准备房间/双子座精灵-2.png
  resource/image/card/准备房间/双鱼座精灵-0.png
  resource/image/card/准备房间/咖啡喷壶-0.png
  resource/image/card/准备房间/咖啡杯-0.png
  resource/image/card/准备房间/咖喱龙虾炮-0.png
  resource/image/card/准备房间/咖喱龙虾炮-1.png
  resource/image/card/准备房间/天蝎座精灵-0.png
  resource/image/card/准备房间/天蝎座精灵-1.png
  resource/image/card/准备房间/射手座精灵-0.png
  resource/image/card/准备房间/射手座精灵-1.png
  resource/image/card/准备房间/射手座精灵-2.png
  resource/image/card/准备房间/小笼包-0.png
  resource/image/card/准备房间/巧克力面包-0.png
  resource/image/card/准备房间/巨蟹座精灵-1.png
  resource/image/card/准备房间/巨蟹座精灵-2.png
  resource/image/card/准备房间/旋风牛-0.png
  resource/image/card/准备房间/月神-0.png
  resource/image/card/准备房间/月神-1.png
  resource/image/card/准备房间/月神-2.png
  resource/image/card/准备房间/月神-3.png
  resource/image/card/准备房间/派派鸡-0.png
  resource/image/card/准备房间/派派鸡-1.png
  resource/image/card/准备房间/派派鸡-2.png
  resource/image/card/准备房间/爆爆鸡-0.png
  resource/image/card/准备房间/爱神-0.png
  resource/image/card/准备房间/爱神-1.png
  resource/image/card/准备房间/爱神-2.png
  resource/image/card/准备房间/爱神-3.png
  resource/image/card/准备房间/酸柠檬爆弹-0.png
Labels: 🗡️Module-Battle, Git-Build

#638 feat(生肖副本): 新增生肖副本(铜树银花谷)的进入方式. 代号CZ-0-?(1-4). 并包含关卡信息和一套内置方案.
  battle_plan/CZ-0-4-1P 蛇来运转.json
  battle_plan/CZ-0-4-2P 蛇来运转.json
  config/stage_info.json
  config/stage_plan.json
  function/core/FAA_ActionInterfaceJump.py
  function/core/QMW_TipStageID.py
  function/core/Todo.py
Labels: Git-Feat

#639 build: 战斗方案命名部分修改, 部分重要流程的图像识别资源微调.
  battle_plan/1通用-海星-1P.json
  battle_plan/1通用-海星-2P.json
  battle_plan/1通用-花火海星-1P.json
  battle_plan/1通用-花火海星-2P.json
  battle_plan/2通用-花火散点-1P.json
  battle_plan/2通用-花火散点-2P.json
  battle_plan/3速刷-灰烬电棍-1P.json
  battle_plan/3速刷-灰烬电棍-2P.json
  battle_plan/3速刷-花火灰烬电棍-1P.json
  battle_plan/3速刷-花火灰烬电棍-2P.json
  battle_plan/3速刷-花火灰烬电棍散点-1P.json
  battle_plan/3速刷-花火灰烬电棍散点-2P.json
  battle_plan/3难关-花火追踪电棍驻场.json
  battle_plan/MT-2-100-1P.json
  battle_plan/MT-2-100-2P.json
  function/core/Todo.py
  function/core_battle/CardManager.py
  logs/item_ranking_dag_graph.json
  resource/image/common/二级密码.png
  resource/image/common/悬赏任务_退出_未选中.png
  resource/image/common/悬赏任务_退出_被选中.png
  resource/image/common/悬赏任务_领取奖励.png
  resource/image/common/战斗/战斗前_接受邀请.png
  resource/image/common/战斗/战斗前_系统提示.png
  resource/image/common/战斗/战斗前_魔塔_创建房间.png
  resource/image/common/战斗/战斗后_1_战利品.png
  resource/image/common/战斗/战斗后_2_战利品阴影版.png
  resource/image/common/战斗/战斗后_3_战斗结算.png
  resource/image/common/战斗/战斗后_4_翻宝箱.png
  resource/image/error/Flash爆炸.png
  resource/image/error/retry_btn.png
  resource/image/error/断开连接.png
  resource/image/error/登录超时.png
Labels: Git-Build

#640 build(使用物品): 更新悬赏礼包酬劳箱图标.
  config/cus_images/一些常用的图标/星际酬劳.png
  config/cus_images/一些常用的图标/浮空岛酬劳.png
  config/cus_images/一些常用的图标/浮空酬劳.png
  config/cus_images/一些常用的图标/火山岛酬劳.png
  config/cus_images/一些常用的图标/火山酬劳.png
  config/cus_images/一些常用的图标/美味岛酬劳.png
  config/cus_images/一些常用的图标/美味酬劳.png
  打包 - 资源文件.py
Labels: Git-Build

#641 perf(图标): 肥坨光荣退役，肥大表哥上位!
  function/core/QMW_0_load_ui_file.py
  function/core/QMW_EditorOfBattlePlan.py
  function/core/QMW_EditorOfStagePlan.py
  function/core/QMW_EditorOfTaskSequence.py
  function/core/QMW_SettingsMigrator.py
  function/core/QMW_UsefulToolsWidget.py
  function/tools/useful_tools.py
  resource/logo/FetDeathWing-450x.png
  resource/logo/FetTuo-192x.png
  resource/logo/FetTuo-512x.png
  resource/logo/圆角-FetDeathWing-256x-AllSize.ico
  resource/logo/圆角-FetDeathWing-450x.png
  resource/logo/圆角-FetTuo-192x.png
  resource/logo/圆角-FetTuo-48x.ico
  resource/logo/圆角-FetTuo-512x.png
  resource/ui/FAA_3.0.ui
  打包 & 部署.md
Labels: Git-Perf

#642 build: 版本号更新v2.1.2. 更新设置模板.
  .gitignore
  config/settings_template.json
  function/globals/EXTRA.py
Labels: Git-Build

#643 perf(自建房对战): 现在支持输入关卡和勾选全局方案, 以应用关卡方案/全局方案/应用自动承载.
  config/settings_template.json
  config/stage_info_extra.json
  function/core/QMW_2_load_settings.py
  function/core/QMW_3_service.py
  function/core/Todo.py
  function/scattered/read_json_to_stage_info.py
  logs/item_ranking_dag_graph.json
  resource/ui/FAA_3.0.ui
Labels: Git-Perf

#644 feat(配置迁移器): 支持迁移公会管理器历史扫描信息, 支持自定义任务序列迁移(暂无uuid支持).
  function/core/QMW_SettingsMigrator.py
  logs/item_ranking_dag_graph.json
  resource_other/be_transformed.xlsx
  resource_other/transformer_of_todo_json_from_excel.py
  resource_other/自定义作战序列 - 用前必读!.txt
Labels: Git-Feat

#647 perf(UI): 解禁部分战斗相关UI单次启动, 最大运行次数(99->999)
  function/core/QMW_EditorOfTaskSequence.py
  resource/ui/FAA_3.0.ui
Labels: 🕹️Module-UI, Git-Perf

#648 perf(战斗流程): 用户在同时出现 没有带对策卡 + 背包满 + 经验满后 仍可继续战斗.
  function/core/FAA_BattlePreparation.py
Labels: Git-Perf

#649 perf(施肥): 提高每轮尝试的最大次数(5->15), 避免当天太多公会注销后无法完成任务.
  function/core/FAA.py
Labels: Git-Perf

#650 fix(战斗执行器内核): 修正一个罕见的问题, 该问题导致僵尸检测线程出现, 虽不影响流程, 但会输出大量warning日志.
  function/core_battle/CardManager.py
Labels: Git-Fix, 🗡️Module-Battle
